import { StyleSheet } from 'react-native';
import { DS } from '@/constants/premiumTheme';
import { MENU_SCAN_C as C } from './menuScanColors';

export const menuScanStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  b: { fontWeight: '700', color: C.text },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: C.card,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  headerIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: C.greenSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 16, fontWeight: '700', color: C.text },
  subtitle: { fontSize: 12, color: C.muted, marginTop: 1 },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: C.dangerSoft,
    borderColor: 'rgba(255,90,90,0.35)',
    borderWidth: 1,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 10,
    padding: 12,
  },
  errorText: { flex: 1, fontSize: 12, color: C.danger, lineHeight: 17 },
  saveHintBox: {
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 10,
    padding: 12,
    backgroundColor: C.warningSoft,
    borderWidth: 1,
    borderColor: C.warningBorder,
  },
  saveHintText: { fontSize: 12, color: C.body, lineHeight: 17 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10, paddingHorizontal: 32 },
  chooseWrap: { padding: 16, gap: 12 },
  hintCard: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    backgroundColor: C.warningSoft,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: C.warningBorder,
  },
  hintText: { flex: 1, fontSize: 13, color: C.body, lineHeight: 19 },
  sourceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: C.card,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: C.border,
  },
  sourceIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.greenSoft,
  },
  sourceTitle: { fontSize: 15, fontWeight: '700', color: C.text },
  sourceSub: { fontSize: 12, color: C.muted, marginTop: 2 },
  analyzingTitle: { fontSize: 16, fontWeight: '700', color: C.text, marginTop: 6 },
  analyzingSub: { fontSize: 13, color: C.muted },

  editContent: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 12 },
  editHint: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: C.greenSoft,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,255,136,0.25)',
  },
  editHintText: { flex: 1, fontSize: 12, color: C.body, lineHeight: 16 },
  aiSuggestBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: C.green,
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 14,
    ...DS.shadow.greenGlow,
  },
  aiSuggestBtnText: { fontSize: 15, fontWeight: '800', color: C.blackOnGreen },
  dishCard: {
    backgroundColor: C.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.border,
    gap: 10,
  },
  dishHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dishName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: C.text,
    backgroundColor: C.inputBg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dishRemove: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: C.dangerSoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,90,90,0.35)',
  },
  dishMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  catChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: C.greenSoft,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,255,136,0.25)',
  },
  catChipText: { fontSize: 12, fontWeight: '700', color: C.green },
  priceField: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.inputBg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  priceInput: { flex: 1, fontSize: 14, fontWeight: '700', color: C.text, paddingVertical: 0 },
  priceSuffix: { fontSize: 12, fontWeight: '600', color: C.muted, marginLeft: 4 },
  weightRow: { gap: 6 },
  weightLabelWrap: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  weightLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: C.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  weightControls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  weightInput: {
    flex: 1,
    fontSize: 14,
    color: C.text,
    backgroundColor: C.inputBg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  weightUnitToggle: {
    flexDirection: 'row',
    backgroundColor: C.inputBg,
    borderRadius: 8,
    padding: 2,
    borderWidth: 1,
    borderColor: C.border,
  },
  weightUnitBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6 },
  weightUnitBtnActive: { backgroundColor: C.green },
  weightUnitText: { fontSize: 12, fontWeight: '700', color: C.muted },
  weightUnitTextActive: { color: C.blackOnGreen },

  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: C.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: 6,
    marginBottom: 4,
  },
  emptyIngredients: { fontSize: 12, color: C.muted, fontStyle: 'italic', paddingVertical: 6 },
  ingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  ingBlock: { marginBottom: 8 },
  pieceWeightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: -2,
    marginBottom: 4,
    paddingLeft: 4,
  },
  pieceWeightLabel: { fontSize: 11, fontWeight: '700', color: C.muted, minWidth: 88 },
  pieceWeightInput: { width: 88 },
  ingInput: {
    backgroundColor: C.inputBg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 7,
    fontSize: 12,
    color: C.text,
  },
  ingName: { flex: 1 },
  ingQty: { width: 58, textAlign: 'right' },
  ingUnitToggle: {
    flexDirection: 'row',
    backgroundColor: C.inputBg,
    borderRadius: 6,
    padding: 2,
    borderWidth: 1,
    borderColor: C.border,
  },
  ingUnitBtn: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 4 },
  ingUnitBtnActive: { backgroundColor: C.green },
  ingUnitText: { fontSize: 10, fontWeight: '700', color: C.muted },
  ingUnitTextActive: { color: C.blackOnGreen },
  ingRemove: {
    width: 26,
    height: 26,
    borderRadius: 6,
    backgroundColor: C.dangerSoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,90,90,0.35)',
  },
  addIngBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: C.green,
    borderStyle: 'dashed',
    backgroundColor: C.greenSoft,
    marginTop: 4,
  },
  addIngText: { fontSize: 12, fontWeight: '700', color: C.green },

  footer: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.card,
  },
  confirmBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: C.green,
    borderRadius: 12,
    paddingVertical: 15,
  },
  confirmBtnText: { fontSize: 15, fontWeight: '700', color: C.blackOnGreen },

  resultWrap: { padding: 24, alignItems: 'center', gap: 10 },
  successCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: C.greenSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  resultTitle: { fontSize: 19, fontWeight: '800', color: C.text, marginTop: 4 },
  resultSub: { fontSize: 13, color: C.body, textAlign: 'center' },
  warnBox: {
    alignSelf: 'stretch',
    backgroundColor: C.warningSoft,
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: C.warningBorder,
    gap: 4,
  },
  warnText: { fontSize: 11, color: C.warning, lineHeight: 16 },
  inventoryBox: {
    alignSelf: 'stretch',
    backgroundColor: C.greenSoft,
    borderRadius: 12,
    padding: 14,
    marginTop: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,255,136,0.28)',
    gap: 3,
  },
  inventoryTitle: { fontSize: 13, fontWeight: '800', color: C.green, lineHeight: 19 },
  inventorySub: { fontSize: 12, color: C.body, marginBottom: 6 },
  inventoryItem: { fontSize: 11.5, color: C.body, lineHeight: 17 },
  primaryBtn: {
    alignSelf: 'stretch',
    backgroundColor: C.green,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 20,
  },
  primaryBtnText: { fontSize: 15, fontWeight: '700', color: C.blackOnGreen },

  pickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'flex-end' },
  pickerSheet: {
    backgroundColor: C.elevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
  },
  pickerTitle: { fontSize: 15, fontWeight: '800', color: C.text, marginBottom: 10 },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  pickerRowActive: { backgroundColor: C.greenSoft },
  pickerRowText: { fontSize: 14, color: C.text, fontWeight: '500' },
  pickerRowTextActive: { color: C.green, fontWeight: '700' },
});
