import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';
import { DS } from '@/constants/premiumTheme';

export const dishCardStyles = StyleSheet.create({
  container: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  premCard: {
    backgroundColor: DS.color.surfaceCard,
    borderRadius: DS.radius.card,
    marginBottom: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: DS.color.borderSubtle,
    overflow: 'hidden',
    ...DS.shadow.card,
  },
  premHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
  },
  premThumb: {
    width: 68,
    height: 68,
    borderRadius: DS.radius.image,
    backgroundColor: DS.color.bgTertiary,
  },
  premThumbPh: {
    width: 68,
    height: 68,
    borderRadius: DS.radius.image,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  stdThumb: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: Colors.borderLight,
    marginRight: 2,
  },
  premThumbWrap: {
    width: 68,
  },
  premName: {
    color: DS.color.heading,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  premPos: { color: DS.color.muted, fontSize: 11 },
  premPrice: { color: DS.color.heading, fontSize: 14, fontWeight: '700' },
  premBody: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: DS.color.borderSubtle,
    gap: 6,
  },
  premRecipeLabel: { color: DS.color.muted, fontSize: 11, fontWeight: '600', marginTop: 8 },
  premMuted: { color: DS.color.muted, fontSize: 12 },
  premIngRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  premIngName: { color: DS.color.body, fontSize: 13, flex: 1 },
  premIngQty: { color: DS.color.heading, fontSize: 12, fontWeight: '600' },
  premEdit: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: DS.radius.button,
    backgroundColor: 'rgba(0,255,120,0.08)',
  },
  premDel: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: DS.radius.button,
    backgroundColor: DS.color.dangerSoft,
  },
  premBatch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: DS.radius.button,
    backgroundColor: DS.color.greenEnd,
    marginTop: 4,
    ...DS.shadow.greenGlow,
  },
  premBatchText: { color: '#0A0A0A', fontWeight: '800', fontSize: 13 },
  header: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  catDot: { width: 10, height: 10, borderRadius: 5 },
  headerText: { flex: 1, gap: 3 },
  name: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
  meta: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  category: { fontSize: 11, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.3 },
  sep: { fontSize: 11, color: Colors.textTertiary },
  posId: { fontSize: 11, color: Colors.textTertiary },
  right: { alignItems: 'flex-end', gap: 4 },
  price: { fontSize: 15, fontWeight: '700', color: Colors.textPrimary },
  body: {
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingHorizontal: 14,
    paddingBottom: 14,
    paddingTop: 10,
  },
  recipeLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  noRecipe: { fontSize: 13, color: Colors.textTertiary, fontStyle: 'italic', paddingVertical: 8 },
  ingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    gap: 10,
  },
  ingRowLast: { borderBottomWidth: 0 },
  bullet: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.accent },
  ingName: { flex: 1, fontSize: 13, color: Colors.textPrimary },
  ingQty: { fontSize: 13, fontWeight: '600', color: Colors.accent },
  costRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 12,
  },
  costLabel: { fontSize: 11, color: Colors.textSecondary },
  priceBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  priceBadgeText: { fontSize: 12, fontWeight: '700' },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingTop: 12,
  },
  editBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: Colors.accentLight,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  editBtnText: { fontSize: 13, fontWeight: '600', color: Colors.accent },
  deleteBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: Colors.dangerLight,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  deleteBtnText: { fontSize: 13, fontWeight: '600', color: Colors.danger },
});
