import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

export const ingredientRowStyles = StyleSheet.create({
  outerWrap: { marginBottom: 10, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: Colors.borderLight },
  wrap: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  indexWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.accentLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  index: { fontSize: 10, fontWeight: '700', color: Colors.accent },
  fields: { flex: 1, gap: 6 },
  nameInput: { flex: 1 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  statusPlaceholder: { width: 26, height: 26 },
  statusWrap: { position: 'relative' },
  statusIcon: {
    width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center',
  },
  statusOk: { backgroundColor: Colors.success },
  statusBad: { backgroundColor: Colors.danger },
  tooltip: {
    position: 'absolute', top: 32, right: 0, backgroundColor: Colors.textPrimary,
    paddingHorizontal: 10, paddingVertical: 7, borderRadius: 8, minWidth: 150, zIndex: 50,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 6,
  },
  tooltipText: { fontSize: 12, color: Colors.white, fontWeight: '600' },
  qtyRow: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  qtyInput: { width: 72 },
  pieceWeightBox: {
    marginTop: 4,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.background,
    gap: 6,
  },
  pieceWeightLabel: { fontSize: 11, fontWeight: '700', color: Colors.textSecondary, letterSpacing: 0.2 },
  pieceWeightInput: { width: 100 },
  pieceWeightHint: { fontSize: 10, color: Colors.textTertiary, lineHeight: 14 },
  input: {
    backgroundColor: Colors.background,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 13,
    color: Colors.textPrimary,
  },
  unitWrap: { flex: 1, flexDirection: 'row', gap: 4, flexWrap: 'wrap' },
  unitBtn: {
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  unitBtnActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  unitText: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary },
  unitTextActive: { color: Colors.white },
  removeBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: Colors.dangerLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  suggestionsBox: {
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 8,
    marginTop: 3,
    overflow: 'hidden',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    gap: 6,
  },
  suggestionText: { flex: 1, fontSize: 13, color: Colors.textPrimary, fontWeight: '500' },
});
