import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';
import { DS } from '@/constants/premiumTheme';

export const menuRecipeRowStyles = StyleSheet.create({
  card: {
    borderRadius: 14,
    marginBottom: 10,
    overflow: 'hidden',
    borderWidth: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  headerText: { flex: 1 },
  itemName: {
    fontSize: 15,
    fontWeight: '600',
  },
  itemCategory: {
    fontSize: 12,
    marginTop: 1,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  posLinkedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#DCFCE7',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  posLinkedBadgePrem: {
    backgroundColor: 'rgba(0,255,120,0.12)',
  },
  posLinkedText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16A34A',
  },
  badge: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeGray: { backgroundColor: '#F1F5F9' },
  badgeGreen: { backgroundColor: '#DCFCE7' },
  badgeOrange: { backgroundColor: '#FEF3C7' },
  badgeRed: { backgroundColor: '#FEE2E2' },
  badgeGrayPrem: { backgroundColor: 'rgba(255,255,255,0.06)' },
  badgeGreenPrem: { backgroundColor: 'rgba(0,255,120,0.14)' },
  badgeOrangePrem: { backgroundColor: 'rgba(245,197,66,0.14)' },
  badgeRedPrem: { backgroundColor: 'rgba(255,90,90,0.14)' },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E293B',
  },
  body: {
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderTopWidth: 1,
  },
  posSection: {
    paddingTop: 14,
    paddingBottom: 4,
  },
  posLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 6,
  },
  posLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  posInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  posInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  posInputDirty: {
    borderColor: '#3B82F6',
    backgroundColor: '#EFF6FF',
  },
  posInputDirtyPrem: {
    borderColor: DS.color.greenEnd,
  },
  posSaveBtn: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  posSavedIndicator: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  posHint: {
    fontSize: 11,
    marginTop: 6,
    lineHeight: 16,
  },
  ingredientsDivider: {
    height: 1,
    marginVertical: 12,
  },
  ingredientsTitle: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  recipeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 8,
  },
  saveRecipeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  saveRecipeBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  availRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
  },
  stockHint: {
    fontSize: 11,
    fontWeight: '600',
    flex: 1,
  },
  loader: { marginVertical: 16 },
  emptyBox: {
    paddingVertical: 8,
    gap: 10,
  },
  emptyText: {
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: 4,
    lineHeight: 18,
  },
  suggestBtn: {
    alignSelf: 'center',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 200,
    alignItems: 'center',
  },
  suggestBtnText: {
    fontSize: 13,
    fontWeight: '700',
  },
  ingredientCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 10,
    marginBottom: 8,
    gap: 8,
  },
  ingredientTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  indexBadge: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  indexText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
  },
  nameInput: {
    flex: 1,
    height: 36,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 13,
  },
  deleteBtn: {
    padding: 4,
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyInput: {
    minWidth: 78,
    width: 86,
    height: 44,
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  pieceWeightBox: {
    marginTop: 2,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
  },
  pieceWeightLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  pieceWeightInput: {
    width: 100,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 14,
    fontWeight: '600',
  },
  pieceWeightHint: {
    fontSize: 10,
    lineHeight: 14,
  },
  unitWrap: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  unitBtn: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
  },
  unitBtnText: {
    fontSize: 11,
    fontWeight: '600',
  },
  mapRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ingredientAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  linkedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#DCFCE7',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    maxWidth: 100,
  },
  linkedBadgePrem: {
    backgroundColor: 'rgba(0,255,120,0.12)',
  },
  linkedBadgeText: {
    fontSize: 11,
    color: '#15803D',
    fontWeight: '500',
    flexShrink: 1,
  },
  changeBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#EFF6FF',
  },
  changeBtnPrem: {
    backgroundColor: 'rgba(0,255,120,0.1)',
  },
  changeBtnText: {
    fontSize: 11,
    color: '#3B82F6',
    fontWeight: '600',
  },
  unlinkBtn: {
    padding: 4,
  },
  mapBtn: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 7,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  mapBtnText: {
    fontSize: 12,
    fontWeight: '600',
  },
  footerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  addIngBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
  },
  addIngBtnText: {
    fontSize: 13,
    fontWeight: '700',
  },
  suggestBtnSmall: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
  },
  suggestBtnSmallText: {
    fontSize: 12,
    fontWeight: '700',
  },
  modal: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  searchBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  searchInput: {
    height: 40,
    borderRadius: 10,
    paddingHorizontal: 14,
    fontSize: 14,
    borderWidth: 1,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  pickerName: {
    fontSize: 15,
    fontWeight: '500',
  },
  pickerUnit: {
    fontSize: 13,
  },
  separator: {
    height: 1,
    marginLeft: 20,
  },
});
