import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/constants/colors';

export const cardStyles = StyleSheet.create({
  container: { backgroundColor: Colors.card, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: Colors.border, shadowColor: Colors.shadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2, overflow: 'hidden' },
  header: { flexDirection: 'row', alignItems: 'center' },
  headerMain: { flex: 1, flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  headerCartBtn: { paddingRight: 14, paddingVertical: 14 },
  iconWrap: { width: 40, height: 40, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  titleWrap: { flex: 1, gap: 4 },
  name: { fontSize: 15, fontWeight: '700', color: Colors.textPrimary },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  category: { fontSize: 11, color: Colors.textSecondary, fontWeight: '500' },
  nip: { fontSize: 11, color: Colors.textTertiary },
  details: { borderTopWidth: 1, borderTopColor: Colors.borderLight, padding: 14, gap: 10 },
  contactRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  contactText: { fontSize: 13, color: Colors.textSecondary },
  notes: { fontSize: 12, color: Colors.textSecondary, lineHeight: 17, backgroundColor: Colors.borderLight, borderRadius: 6, padding: 8 },
  minOrderText: { fontSize: 12, color: Colors.textSecondary, fontWeight: '600' },
  manageRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingTop: 4, flexWrap: 'wrap' },
  managePanel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.borderLight,
    padding: 10,
    gap: 8,
  },
  managePanelTitle: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: Colors.textTertiary,
  },
  managePanelRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  managePanelBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 10,
    minHeight: 40,
  },
  managePanelBtnFull: {
    flex: 0,
    width: '100%',
    paddingVertical: 12,
    marginTop: 2,
  },
  managePanelBtnText: { fontSize: 11, fontWeight: '800' },
  dataBlock: {
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 12,
    backgroundColor: Colors.borderLight,
  },
  dataRow: {
    gap: 4,
  },
  dataLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: Colors.textTertiary,
  },
  dataLabelPrem: {
    color: 'rgba(255,255,255,0.45)',
  },
  dataValue: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textPrimary,
    lineHeight: 20,
  },
  dataValuePrem: {
    color: '#FFFFFF',
  },
  dataLine: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
    lineHeight: 18,
  },
  dataLinePrem: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  manageBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, borderWidth: 1,
  },
  manageBtnText: { fontSize: 12.5, fontWeight: '800' },
  editRowLegacy: { backgroundColor: Colors.accentLight, borderColor: '#BFDBFE' },
  deleteRowLegacy: { backgroundColor: Colors.dangerLight, borderColor: '#FECACA' },
  editRow: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 2 },
  editText: { fontSize: 12, color: Colors.accent, fontWeight: '600' },
  actions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  actionBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1 },
  actionBtnGreen: { backgroundColor: Colors.successLight, borderColor: '#BBF7D0' },
  actionBtnBlue: { backgroundColor: Colors.accentLight, borderColor: '#BFDBFE' },
  actionBtnText: { fontSize: 13, fontWeight: '600' },
  deleteRow: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingTop: 2 },
  deleteText: { fontSize: 12, color: Colors.danger, fontWeight: '500' },
  pdfSection: { borderTopWidth: 1, borderTopColor: Colors.borderLight, padding: 14, gap: 10, backgroundColor: '#F8FAFF' },
  pdfSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pdfSectionTitle: { flex: 1, fontSize: 12, fontWeight: '700', color: Colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.4 },
  pdfInfo: { gap: 8 },
  pdfFileName: { fontSize: 12, fontWeight: '600', color: Colors.textPrimary },
  resultRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.borderLight, borderRadius: 10, padding: 10, gap: 4 },
  resultStat: { flex: 1, alignItems: 'center', gap: 2 },
  resultStatNum: { fontSize: 18, fontWeight: '700', color: Colors.textPrimary },
  resultStatNumZero: { color: Colors.warning },
  resultStatLabel: { fontSize: 10, color: Colors.textTertiary, textAlign: 'center' },
  resultDivider: { width: 1, height: 28, backgroundColor: Colors.border },
  noMatchBox: { flexDirection: 'row', gap: 8, backgroundColor: Colors.warningLight, borderRadius: 8, padding: 10, borderWidth: 1, borderColor: '#FDE68A', alignItems: 'flex-start' },
  noMatchText: { flex: 1, fontSize: 12, color: Colors.warning, lineHeight: 17 },
  analysisRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  analysisText: { fontSize: 11, color: Colors.textTertiary },
  errorBox: { flexDirection: 'row', gap: 8, backgroundColor: Colors.dangerLight, borderRadius: 8, padding: 10, borderWidth: 1, borderColor: '#FECACA', alignItems: 'flex-start' },
  errorBoxText: { flex: 1, fontSize: 12, color: Colors.danger, lineHeight: 17 },
  uploadBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Colors.accentLight, borderWidth: 1.5, borderColor: '#BFDBFE', borderStyle: 'dashed', borderRadius: 10, paddingVertical: 12 },
  scanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.accent,
    borderRadius: 10,
    paddingVertical: 13,
    paddingHorizontal: 12,
    minHeight: 52,
    overflow: 'hidden',
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 3,
  },
  scanBtnGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 12,
    minHeight: 52,
    width: '100%',
  },
  scanBtnText: { flexShrink: 1, fontSize: 13, fontWeight: '700', color: Colors.white, textAlign: 'center' },
  scanBtnTextPrem: { flexShrink: 1, flex: 1, fontSize: 13, fontWeight: '800', color: '#0A0A0A', textAlign: 'center' },
  orderTotalBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', marginTop: 5, backgroundColor: '#F0FDF4', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, borderWidth: 1, borderColor: '#BBF7D0' },
  orderTotalText: { fontSize: 11, fontWeight: '700', color: Colors.success },
  uploadBtnDisabled: { opacity: 0.5 },
  uploadBtnText: { fontSize: 13, fontWeight: '600', color: Colors.accent },
  manualAddBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: Colors.borderLight, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, paddingVertical: 10, overflow: 'hidden' },
  manualAddGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    width: '100%',
  },
  manualAddText: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary },
  manualAddTextPrem: { fontSize: 12, fontWeight: '800', color: '#0A0A0A' },
  loadingRow: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 14 },
  loadingText: { fontSize: 13, color: Colors.textTertiary },
  catalogHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: Colors.borderLight, borderTopWidth: 1, borderTopColor: Colors.border },
  catalogLabel: { flex: 1, fontSize: 11, fontWeight: '700', color: Colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.4 },
  catalogCount: { fontSize: 11, color: Colors.textTertiary, fontWeight: '500' },
  catalogHint: {
    fontSize: 11, color: Colors.textTertiary, lineHeight: 15,
    paddingHorizontal: 14, paddingTop: 8, paddingBottom: 2,
  },
  sectionToggle: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 14, paddingVertical: 10,
    backgroundColor: Colors.card, borderTopWidth: 1, borderTopColor: Colors.borderLight,
  },
  sectionToggleText: { fontSize: 12.5, fontWeight: '800', color: Colors.textSecondary, letterSpacing: 0.1 },
  toggleHiddenBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 10, borderTopWidth: 1, borderTopColor: Colors.borderLight },
  toggleHiddenText: { fontSize: 12, color: Colors.textTertiary, fontWeight: '500', fontStyle: 'italic' },
  // Manual product modal
  modalOverlay: { flex: 1, backgroundColor: Colors.overlay, justifyContent: 'flex-end' },
  manualSheet: { backgroundColor: Colors.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: Platform.OS === 'ios' ? 36 : 20 },
  manualHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  manualTitle: { fontSize: 16, fontWeight: '700', color: Colors.textPrimary },
  manualLabel: { fontSize: 13, fontWeight: '600', color: Colors.textSecondary, marginBottom: 7, marginTop: 4 },
  manualInput: { backgroundColor: Colors.borderLight, borderRadius: 10, paddingHorizontal: 14, paddingVertical: Platform.OS === 'ios' ? 12 : 10, fontSize: 14, color: Colors.textPrimary, marginBottom: 14, borderWidth: 1, borderColor: Colors.border },
  unitPill: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20, backgroundColor: Colors.borderLight, borderWidth: 1.5, borderColor: 'transparent' },
  unitPillActive: { backgroundColor: Colors.accentLight, borderColor: Colors.accent },
  unitPillText: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary },
  unitPillTextActive: { color: Colors.accent },
  manualSaveBtn: { backgroundColor: Colors.accent, borderRadius: 12, paddingVertical: 13, alignItems: 'center', justifyContent: 'center' },
  manualSaveGrad: {
    width: '100%',
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manualSaveBtnDisabled: { opacity: 0.6 },
  manualSaveBtnText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  manualSaveBtnTextPrem: { color: '#0A0A0A', fontSize: 15, fontWeight: '800' },
});
