import { StyleSheet } from 'react-native';
import { PremiumColors, PremiumTokens } from '@/constants/premiumTheme';

export const premiumFinanceStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: PremiumColors.bg },
  content: { padding: PremiumTokens.space.screen, paddingBottom: 56 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: PremiumTokens.space.headerGap },
  logo: { width: 72, height: 72 },
  brand: {
    color: PremiumColors.neon,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  brandSub: {
    color: PremiumTokens.color.textMuted,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1.4,
    marginTop: 4,
  },
  monthLabel: { color: PremiumColors.textSecondary, fontSize: 13, marginTop: 6 },
  devToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: PremiumColors.card,
    borderRadius: PremiumTokens.radius.md,
    borderWidth: 1,
    borderColor: PremiumColors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  devToggleText: { color: PremiumColors.neon, fontSize: 12, fontWeight: '700' },
  metaRow: {
    marginBottom: PremiumTokens.space.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  voiceStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'center',
  },
  voiceStatusText: {
    color: PremiumColors.neon,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  reportBtnWrap: { alignItems: 'center', marginBottom: PremiumTokens.space.lg },
  pdfExportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: PremiumTokens.color.card,
    borderRadius: PremiumTokens.radius.lg,
    borderWidth: 1,
    borderColor: PremiumTokens.color.neonLine,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: PremiumTokens.space.md,
  },
  pdfExportTitle: { color: PremiumColors.text, fontSize: 14, fontWeight: '700' },
  pdfExportSub: { color: PremiumColors.textMuted, fontSize: 11, marginTop: 2 },
  collapseHead: { flexDirection: 'row', alignItems: 'center', gap: PremiumTokens.icon.gap },
  segment: {
    flexDirection: 'row',
    backgroundColor: PremiumTokens.color.bgMid,
    borderRadius: PremiumTokens.radius.lg,
    padding: 5,
    marginBottom: PremiumTokens.space.lg,
    borderWidth: 1,
    borderColor: PremiumColors.border,
  },
  segmentBtn: { flex: 1, paddingVertical: 11, borderRadius: 14, alignItems: 'center' },
  segmentBtnActive: { backgroundColor: PremiumColors.cardElevated },
  segmentText: { fontSize: 13, fontWeight: '600', color: PremiumColors.textMuted },
  segmentTextActive: { color: PremiumColors.neon },
  jarvisCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: PremiumColors.card,
    borderRadius: PremiumTokens.radius.xl,
    padding: PremiumTokens.space.cardPad,
    borderWidth: 1,
    borderColor: PremiumColors.border,
    marginBottom: PremiumTokens.space.cardGap,
    shadowColor: '#00FF88',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
  },
  jarvisText: { color: PremiumColors.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 6 },
  sectionLabel: {
    color: PremiumColors.textMuted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.4,
    marginBottom: PremiumTokens.space.headerGap,
    textTransform: 'uppercase',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: PremiumTokens.space.headerGap,
  },
  sectionAdd: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: PremiumColors.neonSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiRow: { flexDirection: 'row', gap: PremiumTokens.space.cardGap, marginBottom: PremiumTokens.space.cardGap },
  kpi: {
    flex: 1,
    backgroundColor: PremiumColors.card,
    borderRadius: PremiumTokens.radius.xl,
    padding: PremiumTokens.space.cardPad,
    borderWidth: 1,
    borderColor: PremiumColors.border,
  },
  kpiTitle: { color: PremiumColors.textMuted, fontSize: 11, fontWeight: '500', marginBottom: 6 },
  kpiValue: { color: PremiumColors.text, fontSize: 18, fontWeight: '700', letterSpacing: -0.4 },
  kpiSub: { color: PremiumColors.textSecondary, fontSize: 12, marginTop: 6 },
  kpiTap: { paddingRight: 28 },
  kpiAdd: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: PremiumColors.neonSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    backgroundColor: PremiumColors.card,
    borderRadius: PremiumTokens.radius.xl,
    padding: PremiumTokens.space.cardPad,
    borderWidth: 1,
    borderColor: PremiumColors.border,
    marginBottom: PremiumTokens.space.cardGap,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 6,
  },
  cardTitle: {
    color: PremiumColors.text,
    fontSize: PremiumTokens.type.cardTitle.fontSize,
    fontWeight: PremiumTokens.type.cardTitle.fontWeight,
    marginBottom: 12,
  },
  cardHeadRow: { flexDirection: 'row', alignItems: 'center', gap: PremiumTokens.icon.gap, marginBottom: 6 },
  seeAll: { color: PremiumColors.neon, fontSize: 13, fontWeight: '700' },
  chartTabs: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    marginBottom: 12,
  },
  chartTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: PremiumTokens.radius.md,
    backgroundColor: PremiumTokens.color.bgMid,
    borderWidth: 1,
    borderColor: PremiumColors.border,
    alignItems: 'center',
  },
  chartTabActive: {
    borderColor: PremiumColors.neon,
    backgroundColor: PremiumColors.neonSoft,
  },
  chartTabText: { color: PremiumColors.textMuted, fontSize: 12, fontWeight: '600' },
  chartTabTextActive: { color: PremiumColors.neon },
  customRangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  dateInput: {
    flex: 1,
    backgroundColor: '#0E0E0E',
    borderWidth: 1,
    borderColor: PremiumColors.border,
    borderRadius: 8,
    color: PremiumColors.text,
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  costRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PremiumColors.border,
  },
  costName: { color: PremiumColors.text, fontSize: 13, fontWeight: '600' },
  costAmt: { color: PremiumColors.textSecondary, fontSize: 13, fontWeight: '700' },
  iconBtn: { padding: 4 },
  empty: { color: PremiumColors.textMuted, fontSize: 13, textAlign: 'center', padding: 12 },
  noteBox: { marginTop: 8, gap: 8 },
  noteInput: {
    backgroundColor: '#0F0F0F',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: PremiumColors.border,
    color: PremiumColors.text,
    padding: 10,
    minHeight: 56,
    textAlignVertical: 'top',
  },
  noteSave: {
    alignSelf: 'flex-end',
    backgroundColor: PremiumColors.neon,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  noteSaveText: { color: '#0A0A0A', fontWeight: '800', fontSize: 12 },
  syncHint: {
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(0,255,120,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0,255,120,0.22)',
  },
  syncHintTitle: { color: PremiumColors.text, fontSize: 13, fontWeight: '700' },
  syncHintBody: { color: PremiumColors.textMuted, fontSize: 12, marginTop: 4, lineHeight: 17 },
  lowRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  lowBadge: {
    backgroundColor: PremiumColors.alertSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  lowBadgeText: { color: PremiumColors.alert, fontSize: 10, fontWeight: '800' },
});
