/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'app_01.webp': require('@/assets/premium/dishes/apps/app_01.webp'),
  'app_02.webp': require('@/assets/premium/dishes/apps/app_02.webp'),
  'app_03.webp': require('@/assets/premium/dishes/apps/app_03.webp'),
  'app_04.webp': require('@/assets/premium/dishes/apps/app_04.webp'),
  'app_05.webp': require('@/assets/premium/dishes/apps/app_05.webp'),
  'app_06.webp': require('@/assets/premium/dishes/apps/app_06.webp'),
  'app_07.webp': require('@/assets/premium/dishes/apps/app_07.webp'),
  'app_08.webp': require('@/assets/premium/dishes/apps/app_08.webp'),
  'app_09.webp': require('@/assets/premium/dishes/apps/app_09.webp'),
  'app_10.webp': require('@/assets/premium/dishes/apps/app_10.webp'),
  'app_11.webp': require('@/assets/premium/dishes/apps/app_11.webp'),
  'app_12.webp': require('@/assets/premium/dishes/apps/app_12.webp'),
  'app_13.webp': require('@/assets/premium/dishes/apps/app_13.webp'),
  'app_14.webp': require('@/assets/premium/dishes/apps/app_14.webp'),
  'app_15.webp': require('@/assets/premium/dishes/apps/app_15.webp'),
  'app_16.webp': require('@/assets/premium/dishes/apps/app_16.webp'),
  'app_17.webp': require('@/assets/premium/dishes/apps/app_17.webp'),
  'app_18.webp': require('@/assets/premium/dishes/apps/app_18.webp'),
  'app_19.webp': require('@/assets/premium/dishes/apps/app_19.webp'),
  'app_20.webp': require('@/assets/premium/dishes/apps/app_20.webp'),
  'app_21.webp': require('@/assets/premium/dishes/apps/app_21.webp'),
  'app_22.webp': require('@/assets/premium/dishes/apps/app_22.webp'),
  'app_23.webp': require('@/assets/premium/dishes/apps/app_23.webp'),
  'app_24.webp': require('@/assets/premium/dishes/apps/app_24.webp'),
  'app_25.webp': require('@/assets/premium/dishes/apps/app_25.webp'),
};
