/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'asian_01.webp': require('@/assets/premium/dishes/asian/asian_01.webp'),
  'asian_02.webp': require('@/assets/premium/dishes/asian/asian_02.webp'),
  'asian_03.webp': require('@/assets/premium/dishes/asian/asian_03.webp'),
  'asian_04.webp': require('@/assets/premium/dishes/asian/asian_04.webp'),
  'asian_05.webp': require('@/assets/premium/dishes/asian/asian_05.webp'),
  'asian_06.webp': require('@/assets/premium/dishes/asian/asian_06.webp'),
  'asian_07.webp': require('@/assets/premium/dishes/asian/asian_07.webp'),
  'asian_08.webp': require('@/assets/premium/dishes/asian/asian_08.webp'),
  'asian_09.webp': require('@/assets/premium/dishes/asian/asian_09.webp'),
  'asian_10.webp': require('@/assets/premium/dishes/asian/asian_10.webp'),
  'asian_11.webp': require('@/assets/premium/dishes/asian/asian_11.webp'),
  'asian_12.webp': require('@/assets/premium/dishes/asian/asian_12.webp'),
  'asian_13.webp': require('@/assets/premium/dishes/asian/asian_13.webp'),
  'asian_14.webp': require('@/assets/premium/dishes/asian/asian_14.webp'),
  'asian_15.webp': require('@/assets/premium/dishes/asian/asian_15.webp'),
  'asian_16.webp': require('@/assets/premium/dishes/asian/asian_16.webp'),
  'asian_17.webp': require('@/assets/premium/dishes/asian/asian_17.webp'),
  'asian_18.webp': require('@/assets/premium/dishes/asian/asian_18.webp'),
  'asian_19.webp': require('@/assets/premium/dishes/asian/asian_19.webp'),
  'asian_20.webp': require('@/assets/premium/dishes/asian/asian_20.webp'),
  'asian_21.webp': require('@/assets/premium/dishes/asian/asian_21.webp'),
  'asian_22.webp': require('@/assets/premium/dishes/asian/asian_22.webp'),
  'asian_23.webp': require('@/assets/premium/dishes/asian/asian_23.webp'),
  'asian_24.webp': require('@/assets/premium/dishes/asian/asian_24.webp'),
  'asian_25.webp': require('@/assets/premium/dishes/asian/asian_25.webp'),
};
