/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'bbq_01.webp': require('@/assets/premium/dishes/bbq/bbq_01.webp'),
  'bbq_02.webp': require('@/assets/premium/dishes/bbq/bbq_02.webp'),
  'bbq_03.webp': require('@/assets/premium/dishes/bbq/bbq_03.webp'),
  'bbq_04.webp': require('@/assets/premium/dishes/bbq/bbq_04.webp'),
  'bbq_05.webp': require('@/assets/premium/dishes/bbq/bbq_05.webp'),
  'bbq_06.webp': require('@/assets/premium/dishes/bbq/bbq_06.webp'),
  'bbq_07.webp': require('@/assets/premium/dishes/bbq/bbq_07.webp'),
  'bbq_08.webp': require('@/assets/premium/dishes/bbq/bbq_08.webp'),
  'bbq_09.webp': require('@/assets/premium/dishes/bbq/bbq_09.webp'),
  'bbq_10.webp': require('@/assets/premium/dishes/bbq/bbq_10.webp'),
  'bbq_11.webp': require('@/assets/premium/dishes/bbq/bbq_11.webp'),
  'bbq_12.webp': require('@/assets/premium/dishes/bbq/bbq_12.webp'),
  'bbq_13.webp': require('@/assets/premium/dishes/bbq/bbq_13.webp'),
  'bbq_14.webp': require('@/assets/premium/dishes/bbq/bbq_14.webp'),
  'bbq_15.webp': require('@/assets/premium/dishes/bbq/bbq_15.webp'),
  'bbq_16.webp': require('@/assets/premium/dishes/bbq/bbq_16.webp'),
  'bbq_17.webp': require('@/assets/premium/dishes/bbq/bbq_17.webp'),
  'bbq_18.webp': require('@/assets/premium/dishes/bbq/bbq_18.webp'),
  'bbq_19.webp': require('@/assets/premium/dishes/bbq/bbq_19.webp'),
  'bbq_20.webp': require('@/assets/premium/dishes/bbq/bbq_20.webp'),
  'bbq_21.webp': require('@/assets/premium/dishes/bbq/bbq_21.webp'),
  'bbq_22.webp': require('@/assets/premium/dishes/bbq/bbq_22.webp'),
  'bbq_23.webp': require('@/assets/premium/dishes/bbq/bbq_23.webp'),
  'bbq_24.webp': require('@/assets/premium/dishes/bbq/bbq_24.webp'),
  'bbq_25.webp': require('@/assets/premium/dishes/bbq/bbq_25.webp'),
};
