/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'beer_01.webp': require('@/assets/premium/dishes/beers/beer_01.webp'),
  'beer_02.webp': require('@/assets/premium/dishes/beers/beer_02.webp'),
  'beer_03.webp': require('@/assets/premium/dishes/beers/beer_03.webp'),
  'beer_04.webp': require('@/assets/premium/dishes/beers/beer_04.webp'),
  'beer_05.webp': require('@/assets/premium/dishes/beers/beer_05.webp'),
  'beer_06.webp': require('@/assets/premium/dishes/beers/beer_06.webp'),
  'beer_07.webp': require('@/assets/premium/dishes/beers/beer_07.webp'),
  'beer_08.webp': require('@/assets/premium/dishes/beers/beer_08.webp'),
  'beer_09.webp': require('@/assets/premium/dishes/beers/beer_09.webp'),
  'beer_10.webp': require('@/assets/premium/dishes/beers/beer_10.webp'),
  'beer_11.webp': require('@/assets/premium/dishes/beers/beer_11.webp'),
  'beer_12.webp': require('@/assets/premium/dishes/beers/beer_12.webp'),
  'beer_13.webp': require('@/assets/premium/dishes/beers/beer_13.webp'),
  'beer_14.webp': require('@/assets/premium/dishes/beers/beer_14.webp'),
  'beer_15.webp': require('@/assets/premium/dishes/beers/beer_15.webp'),
  'beer_16.webp': require('@/assets/premium/dishes/beers/beer_16.webp'),
  'beer_17.webp': require('@/assets/premium/dishes/beers/beer_17.webp'),
  'beer_18.webp': require('@/assets/premium/dishes/beers/beer_18.webp'),
  'beer_19.webp': require('@/assets/premium/dishes/beers/beer_19.webp'),
  'beer_20.webp': require('@/assets/premium/dishes/beers/beer_20.webp'),
  'beer_21.webp': require('@/assets/premium/dishes/beers/beer_21.webp'),
  'beer_22.webp': require('@/assets/premium/dishes/beers/beer_22.webp'),
  'beer_23.webp': require('@/assets/premium/dishes/beers/beer_23.webp'),
  'beer_24.webp': require('@/assets/premium/dishes/beers/beer_24.webp'),
  'beer_25.webp': require('@/assets/premium/dishes/beers/beer_25.webp'),
};
