/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'breakfast_01.webp': require('@/assets/premium/dishes/breakfast/breakfast_01.webp'),
  'breakfast_02.webp': require('@/assets/premium/dishes/breakfast/breakfast_02.webp'),
  'breakfast_03.webp': require('@/assets/premium/dishes/breakfast/breakfast_03.webp'),
  'breakfast_04.webp': require('@/assets/premium/dishes/breakfast/breakfast_04.webp'),
  'breakfast_05.webp': require('@/assets/premium/dishes/breakfast/breakfast_05.webp'),
  'breakfast_06.webp': require('@/assets/premium/dishes/breakfast/breakfast_06.webp'),
  'breakfast_07.webp': require('@/assets/premium/dishes/breakfast/breakfast_07.webp'),
  'breakfast_08.webp': require('@/assets/premium/dishes/breakfast/breakfast_08.webp'),
  'breakfast_09.webp': require('@/assets/premium/dishes/breakfast/breakfast_09.webp'),
  'breakfast_10.webp': require('@/assets/premium/dishes/breakfast/breakfast_10.webp'),
  'breakfast_11.webp': require('@/assets/premium/dishes/breakfast/breakfast_11.webp'),
  'breakfast_12.webp': require('@/assets/premium/dishes/breakfast/breakfast_12.webp'),
  'breakfast_13.webp': require('@/assets/premium/dishes/breakfast/breakfast_13.webp'),
  'breakfast_14.webp': require('@/assets/premium/dishes/breakfast/breakfast_14.webp'),
  'breakfast_15.webp': require('@/assets/premium/dishes/breakfast/breakfast_15.webp'),
  'breakfast_16.webp': require('@/assets/premium/dishes/breakfast/breakfast_16.webp'),
  'breakfast_17.webp': require('@/assets/premium/dishes/breakfast/breakfast_17.webp'),
  'breakfast_18.webp': require('@/assets/premium/dishes/breakfast/breakfast_18.webp'),
  'breakfast_19.webp': require('@/assets/premium/dishes/breakfast/breakfast_19.webp'),
  'breakfast_20.webp': require('@/assets/premium/dishes/breakfast/breakfast_20.webp'),
  'breakfast_21.webp': require('@/assets/premium/dishes/breakfast/breakfast_21.webp'),
  'breakfast_22.webp': require('@/assets/premium/dishes/breakfast/breakfast_22.webp'),
  'breakfast_23.webp': require('@/assets/premium/dishes/breakfast/breakfast_23.webp'),
  'breakfast_24.webp': require('@/assets/premium/dishes/breakfast/breakfast_24.webp'),
  'breakfast_25.webp': require('@/assets/premium/dishes/breakfast/breakfast_25.webp'),
};
