/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'burger_01.webp': require('@/assets/premium/dishes/burgers/burger_01.webp'),
  'burger_02.webp': require('@/assets/premium/dishes/burgers/burger_02.webp'),
  'burger_03.webp': require('@/assets/premium/dishes/burgers/burger_03.webp'),
  'burger_04.webp': require('@/assets/premium/dishes/burgers/burger_04.webp'),
  'burger_05.webp': require('@/assets/premium/dishes/burgers/burger_05.webp'),
  'burger_06.webp': require('@/assets/premium/dishes/burgers/burger_06.webp'),
  'burger_07.webp': require('@/assets/premium/dishes/burgers/burger_07.webp'),
  'burger_08.webp': require('@/assets/premium/dishes/burgers/burger_08.webp'),
  'burger_09.webp': require('@/assets/premium/dishes/burgers/burger_09.webp'),
  'burger_10.webp': require('@/assets/premium/dishes/burgers/burger_10.webp'),
  'burger_11.webp': require('@/assets/premium/dishes/burgers/burger_11.webp'),
  'burger_12.webp': require('@/assets/premium/dishes/burgers/burger_12.webp'),
  'burger_13.webp': require('@/assets/premium/dishes/burgers/burger_13.webp'),
  'burger_14.webp': require('@/assets/premium/dishes/burgers/burger_14.webp'),
  'burger_15.webp': require('@/assets/premium/dishes/burgers/burger_15.webp'),
  'burger_16.webp': require('@/assets/premium/dishes/burgers/burger_16.webp'),
  'burger_17.webp': require('@/assets/premium/dishes/burgers/burger_17.webp'),
  'burger_18.webp': require('@/assets/premium/dishes/burgers/burger_18.webp'),
  'burger_19.webp': require('@/assets/premium/dishes/burgers/burger_19.webp'),
  'burger_20.webp': require('@/assets/premium/dishes/burgers/burger_20.webp'),
  'burger_21.webp': require('@/assets/premium/dishes/burgers/burger_21.webp'),
  'burger_22.webp': require('@/assets/premium/dishes/burgers/burger_22.webp'),
  'burger_23.webp': require('@/assets/premium/dishes/burgers/burger_23.webp'),
  'burger_24.webp': require('@/assets/premium/dishes/burgers/burger_24.webp'),
  'burger_25.webp': require('@/assets/premium/dishes/burgers/burger_25.webp'),
};
