/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'cake_01.webp': require('@/assets/premium/dishes/cakes/cake_01.webp'),
  'cake_02.webp': require('@/assets/premium/dishes/cakes/cake_02.webp'),
  'cake_03.webp': require('@/assets/premium/dishes/cakes/cake_03.webp'),
  'cake_04.webp': require('@/assets/premium/dishes/cakes/cake_04.webp'),
  'cake_05.webp': require('@/assets/premium/dishes/cakes/cake_05.webp'),
  'cake_06.webp': require('@/assets/premium/dishes/cakes/cake_06.webp'),
  'cake_07.webp': require('@/assets/premium/dishes/cakes/cake_07.webp'),
  'cake_08.webp': require('@/assets/premium/dishes/cakes/cake_08.webp'),
  'cake_09.webp': require('@/assets/premium/dishes/cakes/cake_09.webp'),
  'cake_10.webp': require('@/assets/premium/dishes/cakes/cake_10.webp'),
  'cake_11.webp': require('@/assets/premium/dishes/cakes/cake_11.webp'),
  'cake_12.webp': require('@/assets/premium/dishes/cakes/cake_12.webp'),
  'cake_13.webp': require('@/assets/premium/dishes/cakes/cake_13.webp'),
  'cake_14.webp': require('@/assets/premium/dishes/cakes/cake_14.webp'),
  'cake_15.webp': require('@/assets/premium/dishes/cakes/cake_15.webp'),
  'cake_16.webp': require('@/assets/premium/dishes/cakes/cake_16.webp'),
  'cake_17.webp': require('@/assets/premium/dishes/cakes/cake_17.webp'),
  'cake_18.webp': require('@/assets/premium/dishes/cakes/cake_18.webp'),
  'cake_19.webp': require('@/assets/premium/dishes/cakes/cake_19.webp'),
  'cake_20.webp': require('@/assets/premium/dishes/cakes/cake_20.webp'),
  'cake_21.webp': require('@/assets/premium/dishes/cakes/cake_21.webp'),
  'cake_22.webp': require('@/assets/premium/dishes/cakes/cake_22.webp'),
  'cake_23.webp': require('@/assets/premium/dishes/cakes/cake_23.webp'),
  'cake_24.webp': require('@/assets/premium/dishes/cakes/cake_24.webp'),
  'cake_25.webp': require('@/assets/premium/dishes/cakes/cake_25.webp'),
};
