/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'catering_01.webp': require('@/assets/premium/dishes/catering/catering_01.webp'),
  'catering_02.webp': require('@/assets/premium/dishes/catering/catering_02.webp'),
  'catering_03.webp': require('@/assets/premium/dishes/catering/catering_03.webp'),
  'catering_04.webp': require('@/assets/premium/dishes/catering/catering_04.webp'),
  'catering_05.webp': require('@/assets/premium/dishes/catering/catering_05.webp'),
  'catering_06.webp': require('@/assets/premium/dishes/catering/catering_06.webp'),
  'catering_07.webp': require('@/assets/premium/dishes/catering/catering_07.webp'),
  'catering_08.webp': require('@/assets/premium/dishes/catering/catering_08.webp'),
  'catering_09.webp': require('@/assets/premium/dishes/catering/catering_09.webp'),
  'catering_10.webp': require('@/assets/premium/dishes/catering/catering_10.webp'),
  'catering_11.webp': require('@/assets/premium/dishes/catering/catering_11.webp'),
  'catering_12.webp': require('@/assets/premium/dishes/catering/catering_12.webp'),
  'catering_13.webp': require('@/assets/premium/dishes/catering/catering_13.webp'),
  'catering_14.webp': require('@/assets/premium/dishes/catering/catering_14.webp'),
  'catering_15.webp': require('@/assets/premium/dishes/catering/catering_15.webp'),
  'catering_16.webp': require('@/assets/premium/dishes/catering/catering_16.webp'),
  'catering_17.webp': require('@/assets/premium/dishes/catering/catering_17.webp'),
  'catering_18.webp': require('@/assets/premium/dishes/catering/catering_18.webp'),
  'catering_19.webp': require('@/assets/premium/dishes/catering/catering_19.webp'),
  'catering_20.webp': require('@/assets/premium/dishes/catering/catering_20.webp'),
  'catering_21.webp': require('@/assets/premium/dishes/catering/catering_21.webp'),
  'catering_22.webp': require('@/assets/premium/dishes/catering/catering_22.webp'),
  'catering_23.webp': require('@/assets/premium/dishes/catering/catering_23.webp'),
  'catering_24.webp': require('@/assets/premium/dishes/catering/catering_24.webp'),
  'catering_25.webp': require('@/assets/premium/dishes/catering/catering_25.webp'),
};
