/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'caucasian_01.webp': require('@/assets/premium/dishes/caucasian/caucasian_01.webp'),
  'caucasian_02.webp': require('@/assets/premium/dishes/caucasian/caucasian_02.webp'),
  'caucasian_03.webp': require('@/assets/premium/dishes/caucasian/caucasian_03.webp'),
  'caucasian_04.webp': require('@/assets/premium/dishes/caucasian/caucasian_04.webp'),
  'caucasian_05.webp': require('@/assets/premium/dishes/caucasian/caucasian_05.webp'),
  'caucasian_06.webp': require('@/assets/premium/dishes/caucasian/caucasian_06.webp'),
  'caucasian_07.webp': require('@/assets/premium/dishes/caucasian/caucasian_07.webp'),
  'caucasian_08.webp': require('@/assets/premium/dishes/caucasian/caucasian_08.webp'),
  'caucasian_09.webp': require('@/assets/premium/dishes/caucasian/caucasian_09.webp'),
  'caucasian_10.webp': require('@/assets/premium/dishes/caucasian/caucasian_10.webp'),
  'caucasian_11.webp': require('@/assets/premium/dishes/caucasian/caucasian_11.webp'),
  'caucasian_12.webp': require('@/assets/premium/dishes/caucasian/caucasian_12.webp'),
  'caucasian_13.webp': require('@/assets/premium/dishes/caucasian/caucasian_13.webp'),
  'caucasian_14.webp': require('@/assets/premium/dishes/caucasian/caucasian_14.webp'),
  'caucasian_15.webp': require('@/assets/premium/dishes/caucasian/caucasian_15.webp'),
  'caucasian_16.webp': require('@/assets/premium/dishes/caucasian/caucasian_16.webp'),
  'caucasian_17.webp': require('@/assets/premium/dishes/caucasian/caucasian_17.webp'),
  'caucasian_18.webp': require('@/assets/premium/dishes/caucasian/caucasian_18.webp'),
  'caucasian_19.webp': require('@/assets/premium/dishes/caucasian/caucasian_19.webp'),
  'caucasian_20.webp': require('@/assets/premium/dishes/caucasian/caucasian_20.webp'),
  'caucasian_21.webp': require('@/assets/premium/dishes/caucasian/caucasian_21.webp'),
  'caucasian_22.webp': require('@/assets/premium/dishes/caucasian/caucasian_22.webp'),
  'caucasian_23.webp': require('@/assets/premium/dishes/caucasian/caucasian_23.webp'),
  'caucasian_24.webp': require('@/assets/premium/dishes/caucasian/caucasian_24.webp'),
  'caucasian_25.webp': require('@/assets/premium/dishes/caucasian/caucasian_25.webp'),
};
