/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'cocktail_01.webp': require('@/assets/premium/dishes/cocktails/cocktail_01.webp'),
  'cocktail_02.webp': require('@/assets/premium/dishes/cocktails/cocktail_02.webp'),
  'cocktail_03.webp': require('@/assets/premium/dishes/cocktails/cocktail_03.webp'),
  'cocktail_04.webp': require('@/assets/premium/dishes/cocktails/cocktail_04.webp'),
  'cocktail_05.webp': require('@/assets/premium/dishes/cocktails/cocktail_05.webp'),
  'cocktail_06.webp': require('@/assets/premium/dishes/cocktails/cocktail_06.webp'),
  'cocktail_07.webp': require('@/assets/premium/dishes/cocktails/cocktail_07.webp'),
  'cocktail_08.webp': require('@/assets/premium/dishes/cocktails/cocktail_08.webp'),
  'cocktail_09.webp': require('@/assets/premium/dishes/cocktails/cocktail_09.webp'),
  'cocktail_10.webp': require('@/assets/premium/dishes/cocktails/cocktail_10.webp'),
  'cocktail_11.webp': require('@/assets/premium/dishes/cocktails/cocktail_11.webp'),
  'cocktail_12.webp': require('@/assets/premium/dishes/cocktails/cocktail_12.webp'),
  'cocktail_13.webp': require('@/assets/premium/dishes/cocktails/cocktail_13.webp'),
  'cocktail_14.webp': require('@/assets/premium/dishes/cocktails/cocktail_14.webp'),
  'cocktail_15.webp': require('@/assets/premium/dishes/cocktails/cocktail_15.webp'),
  'cocktail_16.webp': require('@/assets/premium/dishes/cocktails/cocktail_16.webp'),
  'cocktail_17.webp': require('@/assets/premium/dishes/cocktails/cocktail_17.webp'),
  'cocktail_18.webp': require('@/assets/premium/dishes/cocktails/cocktail_18.webp'),
  'cocktail_19.webp': require('@/assets/premium/dishes/cocktails/cocktail_19.webp'),
  'cocktail_20.webp': require('@/assets/premium/dishes/cocktails/cocktail_20.webp'),
  'cocktail_21.webp': require('@/assets/premium/dishes/cocktails/cocktail_21.webp'),
  'cocktail_22.webp': require('@/assets/premium/dishes/cocktails/cocktail_22.webp'),
  'cocktail_23.webp': require('@/assets/premium/dishes/cocktails/cocktail_23.webp'),
  'cocktail_24.webp': require('@/assets/premium/dishes/cocktails/cocktail_24.webp'),
  'cocktail_25.webp': require('@/assets/premium/dishes/cocktails/cocktail_25.webp'),
};
