/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'coffee_01.webp': require('@/assets/premium/dishes/coffees/coffee_01.webp'),
  'coffee_02.webp': require('@/assets/premium/dishes/coffees/coffee_02.webp'),
  'coffee_03.webp': require('@/assets/premium/dishes/coffees/coffee_03.webp'),
  'coffee_04.webp': require('@/assets/premium/dishes/coffees/coffee_04.webp'),
  'coffee_05.webp': require('@/assets/premium/dishes/coffees/coffee_05.webp'),
  'coffee_06.webp': require('@/assets/premium/dishes/coffees/coffee_06.webp'),
  'coffee_07.webp': require('@/assets/premium/dishes/coffees/coffee_07.webp'),
  'coffee_08.webp': require('@/assets/premium/dishes/coffees/coffee_08.webp'),
  'coffee_09.webp': require('@/assets/premium/dishes/coffees/coffee_09.webp'),
  'coffee_10.webp': require('@/assets/premium/dishes/coffees/coffee_10.webp'),
  'coffee_11.webp': require('@/assets/premium/dishes/coffees/coffee_11.webp'),
  'coffee_12.webp': require('@/assets/premium/dishes/coffees/coffee_12.webp'),
  'coffee_13.webp': require('@/assets/premium/dishes/coffees/coffee_13.webp'),
  'coffee_14.webp': require('@/assets/premium/dishes/coffees/coffee_14.webp'),
  'coffee_15.webp': require('@/assets/premium/dishes/coffees/coffee_15.webp'),
  'coffee_16.webp': require('@/assets/premium/dishes/coffees/coffee_16.webp'),
  'coffee_17.webp': require('@/assets/premium/dishes/coffees/coffee_17.webp'),
  'coffee_18.webp': require('@/assets/premium/dishes/coffees/coffee_18.webp'),
  'coffee_19.webp': require('@/assets/premium/dishes/coffees/coffee_19.webp'),
  'coffee_20.webp': require('@/assets/premium/dishes/coffees/coffee_20.webp'),
  'coffee_21.webp': require('@/assets/premium/dishes/coffees/coffee_21.webp'),
  'coffee_22.webp': require('@/assets/premium/dishes/coffees/coffee_22.webp'),
  'coffee_23.webp': require('@/assets/premium/dishes/coffees/coffee_23.webp'),
  'coffee_24.webp': require('@/assets/premium/dishes/coffees/coffee_24.webp'),
  'coffee_25.webp': require('@/assets/premium/dishes/coffees/coffee_25.webp'),
};
