/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'dessert_cup_01.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_01.webp'),
  'dessert_cup_02.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_02.webp'),
  'dessert_cup_03.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_03.webp'),
  'dessert_cup_04.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_04.webp'),
  'dessert_cup_05.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_05.webp'),
  'dessert_cup_06.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_06.webp'),
  'dessert_cup_07.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_07.webp'),
  'dessert_cup_08.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_08.webp'),
  'dessert_cup_09.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_09.webp'),
  'dessert_cup_10.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_10.webp'),
  'dessert_cup_11.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_11.webp'),
  'dessert_cup_12.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_12.webp'),
  'dessert_cup_13.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_13.webp'),
  'dessert_cup_14.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_14.webp'),
  'dessert_cup_15.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_15.webp'),
  'dessert_cup_16.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_16.webp'),
  'dessert_cup_17.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_17.webp'),
  'dessert_cup_18.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_18.webp'),
  'dessert_cup_19.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_19.webp'),
  'dessert_cup_20.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_20.webp'),
  'dessert_cup_21.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_21.webp'),
  'dessert_cup_22.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_22.webp'),
  'dessert_cup_23.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_23.webp'),
  'dessert_cup_24.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_24.webp'),
  'dessert_cup_25.webp': require('@/assets/premium/dishes/desserts_cups/dessert_cup_25.webp'),
};
