/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'dinner_01.webp': require('@/assets/premium/dishes/dinners/dinner_01.webp'),
  'dinner_02.webp': require('@/assets/premium/dishes/dinners/dinner_02.webp'),
  'dinner_03.webp': require('@/assets/premium/dishes/dinners/dinner_03.webp'),
  'dinner_04.webp': require('@/assets/premium/dishes/dinners/dinner_04.webp'),
  'dinner_05.webp': require('@/assets/premium/dishes/dinners/dinner_05.webp'),
  'dinner_06.webp': require('@/assets/premium/dishes/dinners/dinner_06.webp'),
  'dinner_07.webp': require('@/assets/premium/dishes/dinners/dinner_07.webp'),
  'dinner_08.webp': require('@/assets/premium/dishes/dinners/dinner_08.webp'),
  'dinner_09.webp': require('@/assets/premium/dishes/dinners/dinner_09.webp'),
  'dinner_10.webp': require('@/assets/premium/dishes/dinners/dinner_10.webp'),
  'dinner_11.webp': require('@/assets/premium/dishes/dinners/dinner_11.webp'),
  'dinner_12.webp': require('@/assets/premium/dishes/dinners/dinner_12.webp'),
  'dinner_13.webp': require('@/assets/premium/dishes/dinners/dinner_13.webp'),
  'dinner_14.webp': require('@/assets/premium/dishes/dinners/dinner_14.webp'),
  'dinner_15.webp': require('@/assets/premium/dishes/dinners/dinner_15.webp'),
  'dinner_16.webp': require('@/assets/premium/dishes/dinners/dinner_16.webp'),
  'dinner_17.webp': require('@/assets/premium/dishes/dinners/dinner_17.webp'),
  'dinner_18.webp': require('@/assets/premium/dishes/dinners/dinner_18.webp'),
  'dinner_19.webp': require('@/assets/premium/dishes/dinners/dinner_19.webp'),
  'dinner_20.webp': require('@/assets/premium/dishes/dinners/dinner_20.webp'),
  'dinner_21.webp': require('@/assets/premium/dishes/dinners/dinner_21.webp'),
  'dinner_22.webp': require('@/assets/premium/dishes/dinners/dinner_22.webp'),
  'dinner_23.webp': require('@/assets/premium/dishes/dinners/dinner_23.webp'),
  'dinner_24.webp': require('@/assets/premium/dishes/dinners/dinner_24.webp'),
  'dinner_25.webp': require('@/assets/premium/dishes/dinners/dinner_25.webp'),
};
