/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'energy_01.webp': require('@/assets/premium/dishes/energy_drinks/energy_01.webp'),
  'energy_02.webp': require('@/assets/premium/dishes/energy_drinks/energy_02.webp'),
  'energy_03.webp': require('@/assets/premium/dishes/energy_drinks/energy_03.webp'),
  'energy_04.webp': require('@/assets/premium/dishes/energy_drinks/energy_04.webp'),
  'energy_05.webp': require('@/assets/premium/dishes/energy_drinks/energy_05.webp'),
  'energy_06.webp': require('@/assets/premium/dishes/energy_drinks/energy_06.webp'),
  'energy_07.webp': require('@/assets/premium/dishes/energy_drinks/energy_07.webp'),
  'energy_08.webp': require('@/assets/premium/dishes/energy_drinks/energy_08.webp'),
  'energy_09.webp': require('@/assets/premium/dishes/energy_drinks/energy_09.webp'),
  'energy_10.webp': require('@/assets/premium/dishes/energy_drinks/energy_10.webp'),
  'energy_11.webp': require('@/assets/premium/dishes/energy_drinks/energy_11.webp'),
  'energy_12.webp': require('@/assets/premium/dishes/energy_drinks/energy_12.webp'),
  'energy_13.webp': require('@/assets/premium/dishes/energy_drinks/energy_13.webp'),
  'energy_14.webp': require('@/assets/premium/dishes/energy_drinks/energy_14.webp'),
  'energy_15.webp': require('@/assets/premium/dishes/energy_drinks/energy_15.webp'),
  'energy_16.webp': require('@/assets/premium/dishes/energy_drinks/energy_16.webp'),
  'energy_17.webp': require('@/assets/premium/dishes/energy_drinks/energy_17.webp'),
  'energy_18.webp': require('@/assets/premium/dishes/energy_drinks/energy_18.webp'),
  'energy_19.webp': require('@/assets/premium/dishes/energy_drinks/energy_19.webp'),
  'energy_20.webp': require('@/assets/premium/dishes/energy_drinks/energy_20.webp'),
  'energy_21.webp': require('@/assets/premium/dishes/energy_drinks/energy_21.webp'),
  'energy_22.webp': require('@/assets/premium/dishes/energy_drinks/energy_22.webp'),
  'energy_23.webp': require('@/assets/premium/dishes/energy_drinks/energy_23.webp'),
  'energy_24.webp': require('@/assets/premium/dishes/energy_drinks/energy_24.webp'),
  'energy_25.webp': require('@/assets/premium/dishes/energy_drinks/energy_25.webp'),
};
