/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'fish_01.webp': require('@/assets/premium/dishes/fish/fish_01.webp'),
  'fish_02.webp': require('@/assets/premium/dishes/fish/fish_02.webp'),
  'fish_03.webp': require('@/assets/premium/dishes/fish/fish_03.webp'),
  'fish_04.webp': require('@/assets/premium/dishes/fish/fish_04.webp'),
  'fish_05.webp': require('@/assets/premium/dishes/fish/fish_05.webp'),
  'fish_06.webp': require('@/assets/premium/dishes/fish/fish_06.webp'),
  'fish_07.webp': require('@/assets/premium/dishes/fish/fish_07.webp'),
  'fish_08.webp': require('@/assets/premium/dishes/fish/fish_08.webp'),
  'fish_09.webp': require('@/assets/premium/dishes/fish/fish_09.webp'),
  'fish_10.webp': require('@/assets/premium/dishes/fish/fish_10.webp'),
  'fish_11.webp': require('@/assets/premium/dishes/fish/fish_11.webp'),
  'fish_12.webp': require('@/assets/premium/dishes/fish/fish_12.webp'),
  'fish_13.webp': require('@/assets/premium/dishes/fish/fish_13.webp'),
  'fish_14.webp': require('@/assets/premium/dishes/fish/fish_14.webp'),
  'fish_15.webp': require('@/assets/premium/dishes/fish/fish_15.webp'),
  'fish_16.webp': require('@/assets/premium/dishes/fish/fish_16.webp'),
  'fish_17.webp': require('@/assets/premium/dishes/fish/fish_17.webp'),
  'fish_18.webp': require('@/assets/premium/dishes/fish/fish_18.webp'),
  'fish_19.webp': require('@/assets/premium/dishes/fish/fish_19.webp'),
  'fish_20.webp': require('@/assets/premium/dishes/fish/fish_20.webp'),
  'fish_21.webp': require('@/assets/premium/dishes/fish/fish_21.webp'),
  'fish_22.webp': require('@/assets/premium/dishes/fish/fish_22.webp'),
  'fish_23.webp': require('@/assets/premium/dishes/fish/fish_23.webp'),
  'fish_24.webp': require('@/assets/premium/dishes/fish/fish_24.webp'),
  'fish_25.webp': require('@/assets/premium/dishes/fish/fish_25.webp'),
};
