/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'french_01.webp': require('@/assets/premium/dishes/french_desserts/french_01.webp'),
  'french_02.webp': require('@/assets/premium/dishes/french_desserts/french_02.webp'),
  'french_03.webp': require('@/assets/premium/dishes/french_desserts/french_03.webp'),
  'french_04.webp': require('@/assets/premium/dishes/french_desserts/french_04.webp'),
  'french_05.webp': require('@/assets/premium/dishes/french_desserts/french_05.webp'),
  'french_06.webp': require('@/assets/premium/dishes/french_desserts/french_06.webp'),
  'french_07.webp': require('@/assets/premium/dishes/french_desserts/french_07.webp'),
  'french_08.webp': require('@/assets/premium/dishes/french_desserts/french_08.webp'),
  'french_09.webp': require('@/assets/premium/dishes/french_desserts/french_09.webp'),
  'french_10.webp': require('@/assets/premium/dishes/french_desserts/french_10.webp'),
  'french_11.webp': require('@/assets/premium/dishes/french_desserts/french_11.webp'),
  'french_12.webp': require('@/assets/premium/dishes/french_desserts/french_12.webp'),
  'french_13.webp': require('@/assets/premium/dishes/french_desserts/french_13.webp'),
  'french_14.webp': require('@/assets/premium/dishes/french_desserts/french_14.webp'),
  'french_15.webp': require('@/assets/premium/dishes/french_desserts/french_15.webp'),
  'french_16.webp': require('@/assets/premium/dishes/french_desserts/french_16.webp'),
  'french_17.webp': require('@/assets/premium/dishes/french_desserts/french_17.webp'),
  'french_18.webp': require('@/assets/premium/dishes/french_desserts/french_18.webp'),
  'french_19.webp': require('@/assets/premium/dishes/french_desserts/french_19.webp'),
  'french_20.webp': require('@/assets/premium/dishes/french_desserts/french_20.webp'),
  'french_21.webp': require('@/assets/premium/dishes/french_desserts/french_21.webp'),
  'french_22.webp': require('@/assets/premium/dishes/french_desserts/french_22.webp'),
  'french_23.webp': require('@/assets/premium/dishes/french_desserts/french_23.webp'),
  'french_24.webp': require('@/assets/premium/dishes/french_desserts/french_24.webp'),
  'french_25.webp': require('@/assets/premium/dishes/french_desserts/french_25.webp'),
};
