/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'ice_01.webp': require('@/assets/premium/dishes/ice_cream/ice_01.webp'),
  'ice_02.webp': require('@/assets/premium/dishes/ice_cream/ice_02.webp'),
  'ice_03.webp': require('@/assets/premium/dishes/ice_cream/ice_03.webp'),
  'ice_04.webp': require('@/assets/premium/dishes/ice_cream/ice_04.webp'),
  'ice_05.webp': require('@/assets/premium/dishes/ice_cream/ice_05.webp'),
  'ice_06.webp': require('@/assets/premium/dishes/ice_cream/ice_06.webp'),
  'ice_07.webp': require('@/assets/premium/dishes/ice_cream/ice_07.webp'),
  'ice_08.webp': require('@/assets/premium/dishes/ice_cream/ice_08.webp'),
  'ice_09.webp': require('@/assets/premium/dishes/ice_cream/ice_09.webp'),
  'ice_10.webp': require('@/assets/premium/dishes/ice_cream/ice_10.webp'),
  'ice_11.webp': require('@/assets/premium/dishes/ice_cream/ice_11.webp'),
  'ice_12.webp': require('@/assets/premium/dishes/ice_cream/ice_12.webp'),
  'ice_13.webp': require('@/assets/premium/dishes/ice_cream/ice_13.webp'),
  'ice_14.webp': require('@/assets/premium/dishes/ice_cream/ice_14.webp'),
  'ice_15.webp': require('@/assets/premium/dishes/ice_cream/ice_15.webp'),
  'ice_16.webp': require('@/assets/premium/dishes/ice_cream/ice_16.webp'),
  'ice_17.webp': require('@/assets/premium/dishes/ice_cream/ice_17.webp'),
  'ice_18.webp': require('@/assets/premium/dishes/ice_cream/ice_18.webp'),
  'ice_19.webp': require('@/assets/premium/dishes/ice_cream/ice_19.webp'),
  'ice_20.webp': require('@/assets/premium/dishes/ice_cream/ice_20.webp'),
  'ice_21.webp': require('@/assets/premium/dishes/ice_cream/ice_21.webp'),
  'ice_22.webp': require('@/assets/premium/dishes/ice_cream/ice_22.webp'),
  'ice_23.webp': require('@/assets/premium/dishes/ice_cream/ice_23.webp'),
  'ice_24.webp': require('@/assets/premium/dishes/ice_cream/ice_24.webp'),
  'ice_25.webp': require('@/assets/premium/dishes/ice_cream/ice_25.webp'),
};
