/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'indian_01.webp': require('@/assets/premium/dishes/indian/indian_01.webp'),
  'indian_02.webp': require('@/assets/premium/dishes/indian/indian_02.webp'),
  'indian_03.webp': require('@/assets/premium/dishes/indian/indian_03.webp'),
  'indian_04.webp': require('@/assets/premium/dishes/indian/indian_04.webp'),
  'indian_05.webp': require('@/assets/premium/dishes/indian/indian_05.webp'),
  'indian_06.webp': require('@/assets/premium/dishes/indian/indian_06.webp'),
  'indian_07.webp': require('@/assets/premium/dishes/indian/indian_07.webp'),
  'indian_08.webp': require('@/assets/premium/dishes/indian/indian_08.webp'),
  'indian_09.webp': require('@/assets/premium/dishes/indian/indian_09.webp'),
  'indian_10.webp': require('@/assets/premium/dishes/indian/indian_10.webp'),
  'indian_11.webp': require('@/assets/premium/dishes/indian/indian_11.webp'),
  'indian_12.webp': require('@/assets/premium/dishes/indian/indian_12.webp'),
  'indian_13.webp': require('@/assets/premium/dishes/indian/indian_13.webp'),
  'indian_14.webp': require('@/assets/premium/dishes/indian/indian_14.webp'),
  'indian_15.webp': require('@/assets/premium/dishes/indian/indian_15.webp'),
  'indian_16.webp': require('@/assets/premium/dishes/indian/indian_16.webp'),
  'indian_17.webp': require('@/assets/premium/dishes/indian/indian_17.webp'),
  'indian_18.webp': require('@/assets/premium/dishes/indian/indian_18.webp'),
  'indian_19.webp': require('@/assets/premium/dishes/indian/indian_19.webp'),
  'indian_20.webp': require('@/assets/premium/dishes/indian/indian_20.webp'),
  'indian_21.webp': require('@/assets/premium/dishes/indian/indian_21.webp'),
  'indian_22.webp': require('@/assets/premium/dishes/indian/indian_22.webp'),
  'indian_23.webp': require('@/assets/premium/dishes/indian/indian_23.webp'),
  'indian_24.webp': require('@/assets/premium/dishes/indian/indian_24.webp'),
  'indian_25.webp': require('@/assets/premium/dishes/indian/indian_25.webp'),
};
