/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'juice_01.webp': require('@/assets/premium/dishes/juices/juice_01.webp'),
  'juice_02.webp': require('@/assets/premium/dishes/juices/juice_02.webp'),
  'juice_03.webp': require('@/assets/premium/dishes/juices/juice_03.webp'),
  'juice_04.webp': require('@/assets/premium/dishes/juices/juice_04.webp'),
  'juice_05.webp': require('@/assets/premium/dishes/juices/juice_05.webp'),
  'juice_06.webp': require('@/assets/premium/dishes/juices/juice_06.webp'),
  'juice_07.webp': require('@/assets/premium/dishes/juices/juice_07.webp'),
  'juice_08.webp': require('@/assets/premium/dishes/juices/juice_08.webp'),
  'juice_09.webp': require('@/assets/premium/dishes/juices/juice_09.webp'),
  'juice_10.webp': require('@/assets/premium/dishes/juices/juice_10.webp'),
  'juice_11.webp': require('@/assets/premium/dishes/juices/juice_11.webp'),
  'juice_12.webp': require('@/assets/premium/dishes/juices/juice_12.webp'),
  'juice_13.webp': require('@/assets/premium/dishes/juices/juice_13.webp'),
  'juice_14.webp': require('@/assets/premium/dishes/juices/juice_14.webp'),
  'juice_15.webp': require('@/assets/premium/dishes/juices/juice_15.webp'),
  'juice_16.webp': require('@/assets/premium/dishes/juices/juice_16.webp'),
  'juice_17.webp': require('@/assets/premium/dishes/juices/juice_17.webp'),
  'juice_18.webp': require('@/assets/premium/dishes/juices/juice_18.webp'),
  'juice_19.webp': require('@/assets/premium/dishes/juices/juice_19.webp'),
  'juice_20.webp': require('@/assets/premium/dishes/juices/juice_20.webp'),
  'juice_21.webp': require('@/assets/premium/dishes/juices/juice_21.webp'),
  'juice_22.webp': require('@/assets/premium/dishes/juices/juice_22.webp'),
  'juice_23.webp': require('@/assets/premium/dishes/juices/juice_23.webp'),
  'juice_24.webp': require('@/assets/premium/dishes/juices/juice_24.webp'),
  'juice_25.webp': require('@/assets/premium/dishes/juices/juice_25.webp'),
};
