/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'kebab_01.webp': require('@/assets/premium/dishes/kebabs/kebab_01.webp'),
  'kebab_02.webp': require('@/assets/premium/dishes/kebabs/kebab_02.webp'),
  'kebab_03.webp': require('@/assets/premium/dishes/kebabs/kebab_03.webp'),
  'kebab_04.webp': require('@/assets/premium/dishes/kebabs/kebab_04.webp'),
  'kebab_05.webp': require('@/assets/premium/dishes/kebabs/kebab_05.webp'),
  'kebab_06.webp': require('@/assets/premium/dishes/kebabs/kebab_06.webp'),
  'kebab_07.webp': require('@/assets/premium/dishes/kebabs/kebab_07.webp'),
  'kebab_08.webp': require('@/assets/premium/dishes/kebabs/kebab_08.webp'),
  'kebab_09.webp': require('@/assets/premium/dishes/kebabs/kebab_09.webp'),
  'kebab_10.webp': require('@/assets/premium/dishes/kebabs/kebab_10.webp'),
  'kebab_11.webp': require('@/assets/premium/dishes/kebabs/kebab_11.webp'),
  'kebab_12.webp': require('@/assets/premium/dishes/kebabs/kebab_12.webp'),
  'kebab_13.webp': require('@/assets/premium/dishes/kebabs/kebab_13.webp'),
  'kebab_14.webp': require('@/assets/premium/dishes/kebabs/kebab_14.webp'),
  'kebab_15.webp': require('@/assets/premium/dishes/kebabs/kebab_15.webp'),
  'kebab_16.webp': require('@/assets/premium/dishes/kebabs/kebab_16.webp'),
  'kebab_17.webp': require('@/assets/premium/dishes/kebabs/kebab_17.webp'),
  'kebab_18.webp': require('@/assets/premium/dishes/kebabs/kebab_18.webp'),
  'kebab_19.webp': require('@/assets/premium/dishes/kebabs/kebab_19.webp'),
  'kebab_20.webp': require('@/assets/premium/dishes/kebabs/kebab_20.webp'),
  'kebab_21.webp': require('@/assets/premium/dishes/kebabs/kebab_21.webp'),
  'kebab_22.webp': require('@/assets/premium/dishes/kebabs/kebab_22.webp'),
  'kebab_23.webp': require('@/assets/premium/dishes/kebabs/kebab_23.webp'),
  'kebab_24.webp': require('@/assets/premium/dishes/kebabs/kebab_24.webp'),
  'kebab_25.webp': require('@/assets/premium/dishes/kebabs/kebab_25.webp'),
};
