/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'lemonade_01.webp': require('@/assets/premium/dishes/lemonades/lemonade_01.webp'),
  'lemonade_02.webp': require('@/assets/premium/dishes/lemonades/lemonade_02.webp'),
  'lemonade_03.webp': require('@/assets/premium/dishes/lemonades/lemonade_03.webp'),
  'lemonade_04.webp': require('@/assets/premium/dishes/lemonades/lemonade_04.webp'),
  'lemonade_05.webp': require('@/assets/premium/dishes/lemonades/lemonade_05.webp'),
  'lemonade_06.webp': require('@/assets/premium/dishes/lemonades/lemonade_06.webp'),
  'lemonade_07.webp': require('@/assets/premium/dishes/lemonades/lemonade_07.webp'),
  'lemonade_08.webp': require('@/assets/premium/dishes/lemonades/lemonade_08.webp'),
  'lemonade_09.webp': require('@/assets/premium/dishes/lemonades/lemonade_09.webp'),
  'lemonade_10.webp': require('@/assets/premium/dishes/lemonades/lemonade_10.webp'),
  'lemonade_11.webp': require('@/assets/premium/dishes/lemonades/lemonade_11.webp'),
  'lemonade_12.webp': require('@/assets/premium/dishes/lemonades/lemonade_12.webp'),
  'lemonade_13.webp': require('@/assets/premium/dishes/lemonades/lemonade_13.webp'),
  'lemonade_14.webp': require('@/assets/premium/dishes/lemonades/lemonade_14.webp'),
  'lemonade_15.webp': require('@/assets/premium/dishes/lemonades/lemonade_15.webp'),
  'lemonade_16.webp': require('@/assets/premium/dishes/lemonades/lemonade_16.webp'),
  'lemonade_17.webp': require('@/assets/premium/dishes/lemonades/lemonade_17.webp'),
  'lemonade_18.webp': require('@/assets/premium/dishes/lemonades/lemonade_18.webp'),
  'lemonade_19.webp': require('@/assets/premium/dishes/lemonades/lemonade_19.webp'),
  'lemonade_20.webp': require('@/assets/premium/dishes/lemonades/lemonade_20.webp'),
  'lemonade_21.webp': require('@/assets/premium/dishes/lemonades/lemonade_21.webp'),
  'lemonade_22.webp': require('@/assets/premium/dishes/lemonades/lemonade_22.webp'),
  'lemonade_23.webp': require('@/assets/premium/dishes/lemonades/lemonade_23.webp'),
  'lemonade_24.webp': require('@/assets/premium/dishes/lemonades/lemonade_24.webp'),
  'lemonade_25.webp': require('@/assets/premium/dishes/lemonades/lemonade_25.webp'),
};
