/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'mediterranean_01.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_01.webp'),
  'mediterranean_02.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_02.webp'),
  'mediterranean_03.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_03.webp'),
  'mediterranean_04.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_04.webp'),
  'mediterranean_05.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_05.webp'),
  'mediterranean_06.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_06.webp'),
  'mediterranean_07.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_07.webp'),
  'mediterranean_08.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_08.webp'),
  'mediterranean_09.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_09.webp'),
  'mediterranean_10.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_10.webp'),
  'mediterranean_11.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_11.webp'),
  'mediterranean_12.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_12.webp'),
  'mediterranean_13.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_13.webp'),
  'mediterranean_14.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_14.webp'),
  'mediterranean_15.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_15.webp'),
  'mediterranean_16.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_16.webp'),
  'mediterranean_17.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_17.webp'),
  'mediterranean_18.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_18.webp'),
  'mediterranean_19.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_19.webp'),
  'mediterranean_20.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_20.webp'),
  'mediterranean_21.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_21.webp'),
  'mediterranean_22.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_22.webp'),
  'mediterranean_23.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_23.webp'),
  'mediterranean_24.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_24.webp'),
  'mediterranean_25.webp': require('@/assets/premium/dishes/mediterranean/mediterranean_25.webp'),
};
