/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'mexican_01.webp': require('@/assets/premium/dishes/mexican/mexican_01.webp'),
  'mexican_02.webp': require('@/assets/premium/dishes/mexican/mexican_02.webp'),
  'mexican_03.webp': require('@/assets/premium/dishes/mexican/mexican_03.webp'),
  'mexican_04.webp': require('@/assets/premium/dishes/mexican/mexican_04.webp'),
  'mexican_05.webp': require('@/assets/premium/dishes/mexican/mexican_05.webp'),
  'mexican_06.webp': require('@/assets/premium/dishes/mexican/mexican_06.webp'),
  'mexican_07.webp': require('@/assets/premium/dishes/mexican/mexican_07.webp'),
  'mexican_08.webp': require('@/assets/premium/dishes/mexican/mexican_08.webp'),
  'mexican_09.webp': require('@/assets/premium/dishes/mexican/mexican_09.webp'),
  'mexican_10.webp': require('@/assets/premium/dishes/mexican/mexican_10.webp'),
  'mexican_11.webp': require('@/assets/premium/dishes/mexican/mexican_11.webp'),
  'mexican_12.webp': require('@/assets/premium/dishes/mexican/mexican_12.webp'),
  'mexican_13.webp': require('@/assets/premium/dishes/mexican/mexican_13.webp'),
  'mexican_14.webp': require('@/assets/premium/dishes/mexican/mexican_14.webp'),
  'mexican_15.webp': require('@/assets/premium/dishes/mexican/mexican_15.webp'),
  'mexican_16.webp': require('@/assets/premium/dishes/mexican/mexican_16.webp'),
  'mexican_17.webp': require('@/assets/premium/dishes/mexican/mexican_17.webp'),
  'mexican_18.webp': require('@/assets/premium/dishes/mexican/mexican_18.webp'),
  'mexican_19.webp': require('@/assets/premium/dishes/mexican/mexican_19.webp'),
  'mexican_20.webp': require('@/assets/premium/dishes/mexican/mexican_20.webp'),
  'mexican_21.webp': require('@/assets/premium/dishes/mexican/mexican_21.webp'),
  'mexican_22.webp': require('@/assets/premium/dishes/mexican/mexican_22.webp'),
  'mexican_23.webp': require('@/assets/premium/dishes/mexican/mexican_23.webp'),
  'mexican_24.webp': require('@/assets/premium/dishes/mexican/mexican_24.webp'),
  'mexican_25.webp': require('@/assets/premium/dishes/mexican/mexican_25.webp'),
};
