/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'pancake_01.webp': require('@/assets/premium/dishes/pancakes/pancake_01.webp'),
  'pancake_02.webp': require('@/assets/premium/dishes/pancakes/pancake_02.webp'),
  'pancake_03.webp': require('@/assets/premium/dishes/pancakes/pancake_03.webp'),
  'pancake_04.webp': require('@/assets/premium/dishes/pancakes/pancake_04.webp'),
  'pancake_05.webp': require('@/assets/premium/dishes/pancakes/pancake_05.webp'),
  'pancake_06.webp': require('@/assets/premium/dishes/pancakes/pancake_06.webp'),
  'pancake_07.webp': require('@/assets/premium/dishes/pancakes/pancake_07.webp'),
  'pancake_08.webp': require('@/assets/premium/dishes/pancakes/pancake_08.webp'),
  'pancake_09.webp': require('@/assets/premium/dishes/pancakes/pancake_09.webp'),
  'pancake_10.webp': require('@/assets/premium/dishes/pancakes/pancake_10.webp'),
  'pancake_11.webp': require('@/assets/premium/dishes/pancakes/pancake_11.webp'),
  'pancake_12.webp': require('@/assets/premium/dishes/pancakes/pancake_12.webp'),
  'pancake_13.webp': require('@/assets/premium/dishes/pancakes/pancake_13.webp'),
  'pancake_14.webp': require('@/assets/premium/dishes/pancakes/pancake_14.webp'),
  'pancake_15.webp': require('@/assets/premium/dishes/pancakes/pancake_15.webp'),
  'pancake_16.webp': require('@/assets/premium/dishes/pancakes/pancake_16.webp'),
  'pancake_17.webp': require('@/assets/premium/dishes/pancakes/pancake_17.webp'),
  'pancake_18.webp': require('@/assets/premium/dishes/pancakes/pancake_18.webp'),
  'pancake_19.webp': require('@/assets/premium/dishes/pancakes/pancake_19.webp'),
  'pancake_20.webp': require('@/assets/premium/dishes/pancakes/pancake_20.webp'),
  'pancake_21.webp': require('@/assets/premium/dishes/pancakes/pancake_21.webp'),
  'pancake_22.webp': require('@/assets/premium/dishes/pancakes/pancake_22.webp'),
  'pancake_23.webp': require('@/assets/premium/dishes/pancakes/pancake_23.webp'),
  'pancake_24.webp': require('@/assets/premium/dishes/pancakes/pancake_24.webp'),
  'pancake_25.webp': require('@/assets/premium/dishes/pancakes/pancake_25.webp'),
};
