/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'pasta_01.webp': require('@/assets/premium/dishes/pastas/pasta_01.webp'),
  'pasta_02.webp': require('@/assets/premium/dishes/pastas/pasta_02.webp'),
  'pasta_03.webp': require('@/assets/premium/dishes/pastas/pasta_03.webp'),
  'pasta_04.webp': require('@/assets/premium/dishes/pastas/pasta_04.webp'),
  'pasta_05.webp': require('@/assets/premium/dishes/pastas/pasta_05.webp'),
  'pasta_06.webp': require('@/assets/premium/dishes/pastas/pasta_06.webp'),
  'pasta_07.webp': require('@/assets/premium/dishes/pastas/pasta_07.webp'),
  'pasta_08.webp': require('@/assets/premium/dishes/pastas/pasta_08.webp'),
  'pasta_09.webp': require('@/assets/premium/dishes/pastas/pasta_09.webp'),
  'pasta_10.webp': require('@/assets/premium/dishes/pastas/pasta_10.webp'),
  'pasta_11.webp': require('@/assets/premium/dishes/pastas/pasta_11.webp'),
  'pasta_12.webp': require('@/assets/premium/dishes/pastas/pasta_12.webp'),
  'pasta_13.webp': require('@/assets/premium/dishes/pastas/pasta_13.webp'),
  'pasta_14.webp': require('@/assets/premium/dishes/pastas/pasta_14.webp'),
  'pasta_15.webp': require('@/assets/premium/dishes/pastas/pasta_15.webp'),
  'pasta_16.webp': require('@/assets/premium/dishes/pastas/pasta_16.webp'),
  'pasta_17.webp': require('@/assets/premium/dishes/pastas/pasta_17.webp'),
  'pasta_18.webp': require('@/assets/premium/dishes/pastas/pasta_18.webp'),
  'pasta_19.webp': require('@/assets/premium/dishes/pastas/pasta_19.webp'),
  'pasta_20.webp': require('@/assets/premium/dishes/pastas/pasta_20.webp'),
  'pasta_21.webp': require('@/assets/premium/dishes/pastas/pasta_21.webp'),
  'pasta_22.webp': require('@/assets/premium/dishes/pastas/pasta_22.webp'),
  'pasta_23.webp': require('@/assets/premium/dishes/pastas/pasta_23.webp'),
  'pasta_24.webp': require('@/assets/premium/dishes/pastas/pasta_24.webp'),
  'pasta_25.webp': require('@/assets/premium/dishes/pastas/pasta_25.webp'),
};
