/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'pastry_01.webp': require('@/assets/premium/dishes/pastries/pastry_01.webp'),
  'pastry_02.webp': require('@/assets/premium/dishes/pastries/pastry_02.webp'),
  'pastry_03.webp': require('@/assets/premium/dishes/pastries/pastry_03.webp'),
  'pastry_04.webp': require('@/assets/premium/dishes/pastries/pastry_04.webp'),
  'pastry_05.webp': require('@/assets/premium/dishes/pastries/pastry_05.webp'),
  'pastry_06.webp': require('@/assets/premium/dishes/pastries/pastry_06.webp'),
  'pastry_07.webp': require('@/assets/premium/dishes/pastries/pastry_07.webp'),
  'pastry_08.webp': require('@/assets/premium/dishes/pastries/pastry_08.webp'),
  'pastry_09.webp': require('@/assets/premium/dishes/pastries/pastry_09.webp'),
  'pastry_10.webp': require('@/assets/premium/dishes/pastries/pastry_10.webp'),
  'pastry_11.webp': require('@/assets/premium/dishes/pastries/pastry_11.webp'),
  'pastry_12.webp': require('@/assets/premium/dishes/pastries/pastry_12.webp'),
  'pastry_13.webp': require('@/assets/premium/dishes/pastries/pastry_13.webp'),
  'pastry_14.webp': require('@/assets/premium/dishes/pastries/pastry_14.webp'),
  'pastry_15.webp': require('@/assets/premium/dishes/pastries/pastry_15.webp'),
  'pastry_16.webp': require('@/assets/premium/dishes/pastries/pastry_16.webp'),
  'pastry_17.webp': require('@/assets/premium/dishes/pastries/pastry_17.webp'),
  'pastry_18.webp': require('@/assets/premium/dishes/pastries/pastry_18.webp'),
  'pastry_19.webp': require('@/assets/premium/dishes/pastries/pastry_19.webp'),
  'pastry_20.webp': require('@/assets/premium/dishes/pastries/pastry_20.webp'),
  'pastry_21.webp': require('@/assets/premium/dishes/pastries/pastry_21.webp'),
  'pastry_22.webp': require('@/assets/premium/dishes/pastries/pastry_22.webp'),
  'pastry_23.webp': require('@/assets/premium/dishes/pastries/pastry_23.webp'),
  'pastry_24.webp': require('@/assets/premium/dishes/pastries/pastry_24.webp'),
  'pastry_25.webp': require('@/assets/premium/dishes/pastries/pastry_25.webp'),
};
