/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'pizza_01.webp': require('@/assets/premium/dishes/pizzas/pizza_01.webp'),
  'pizza_02.webp': require('@/assets/premium/dishes/pizzas/pizza_02.webp'),
  'pizza_03.webp': require('@/assets/premium/dishes/pizzas/pizza_03.webp'),
  'pizza_04.webp': require('@/assets/premium/dishes/pizzas/pizza_04.webp'),
  'pizza_05.webp': require('@/assets/premium/dishes/pizzas/pizza_05.webp'),
  'pizza_06.webp': require('@/assets/premium/dishes/pizzas/pizza_06.webp'),
  'pizza_07.webp': require('@/assets/premium/dishes/pizzas/pizza_07.webp'),
  'pizza_08.webp': require('@/assets/premium/dishes/pizzas/pizza_08.webp'),
  'pizza_09.webp': require('@/assets/premium/dishes/pizzas/pizza_09.webp'),
  'pizza_10.webp': require('@/assets/premium/dishes/pizzas/pizza_10.webp'),
  'pizza_11.webp': require('@/assets/premium/dishes/pizzas/pizza_11.webp'),
  'pizza_12.webp': require('@/assets/premium/dishes/pizzas/pizza_12.webp'),
  'pizza_13.webp': require('@/assets/premium/dishes/pizzas/pizza_13.webp'),
  'pizza_14.webp': require('@/assets/premium/dishes/pizzas/pizza_14.webp'),
  'pizza_15.webp': require('@/assets/premium/dishes/pizzas/pizza_15.webp'),
  'pizza_16.webp': require('@/assets/premium/dishes/pizzas/pizza_16.webp'),
  'pizza_17.webp': require('@/assets/premium/dishes/pizzas/pizza_17.webp'),
  'pizza_18.webp': require('@/assets/premium/dishes/pizzas/pizza_18.webp'),
  'pizza_19.webp': require('@/assets/premium/dishes/pizzas/pizza_19.webp'),
  'pizza_20.webp': require('@/assets/premium/dishes/pizzas/pizza_20.webp'),
  'pizza_21.webp': require('@/assets/premium/dishes/pizzas/pizza_21.webp'),
  'pizza_22.webp': require('@/assets/premium/dishes/pizzas/pizza_22.webp'),
  'pizza_23.webp': require('@/assets/premium/dishes/pizzas/pizza_23.webp'),
  'pizza_24.webp': require('@/assets/premium/dishes/pizzas/pizza_24.webp'),
  'pizza_25.webp': require('@/assets/premium/dishes/pizzas/pizza_25.webp'),
};
