/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'polish_01.webp': require('@/assets/premium/dishes/polish/polish_01.webp'),
  'polish_02.webp': require('@/assets/premium/dishes/polish/polish_02.webp'),
  'polish_03.webp': require('@/assets/premium/dishes/polish/polish_03.webp'),
  'polish_04.webp': require('@/assets/premium/dishes/polish/polish_04.webp'),
  'polish_05.webp': require('@/assets/premium/dishes/polish/polish_05.webp'),
  'polish_06.webp': require('@/assets/premium/dishes/polish/polish_06.webp'),
  'polish_07.webp': require('@/assets/premium/dishes/polish/polish_07.webp'),
  'polish_08.webp': require('@/assets/premium/dishes/polish/polish_08.webp'),
  'polish_09.webp': require('@/assets/premium/dishes/polish/polish_09.webp'),
  'polish_10.webp': require('@/assets/premium/dishes/polish/polish_10.webp'),
  'polish_11.webp': require('@/assets/premium/dishes/polish/polish_11.webp'),
  'polish_12.webp': require('@/assets/premium/dishes/polish/polish_12.webp'),
  'polish_13.webp': require('@/assets/premium/dishes/polish/polish_13.webp'),
  'polish_14.webp': require('@/assets/premium/dishes/polish/polish_14.webp'),
  'polish_15.webp': require('@/assets/premium/dishes/polish/polish_15.webp'),
  'polish_16.webp': require('@/assets/premium/dishes/polish/polish_16.webp'),
  'polish_17.webp': require('@/assets/premium/dishes/polish/polish_17.webp'),
  'polish_18.webp': require('@/assets/premium/dishes/polish/polish_18.webp'),
  'polish_19.webp': require('@/assets/premium/dishes/polish/polish_19.webp'),
  'polish_20.webp': require('@/assets/premium/dishes/polish/polish_20.webp'),
  'polish_21.webp': require('@/assets/premium/dishes/polish/polish_21.webp'),
  'polish_22.webp': require('@/assets/premium/dishes/polish/polish_22.webp'),
  'polish_23.webp': require('@/assets/premium/dishes/polish/polish_23.webp'),
  'polish_24.webp': require('@/assets/premium/dishes/polish/polish_24.webp'),
  'polish_25.webp': require('@/assets/premium/dishes/polish/polish_25.webp'),
};
