/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'roast_01.webp': require('@/assets/premium/dishes/roasts/roast_01.webp'),
  'roast_02.webp': require('@/assets/premium/dishes/roasts/roast_02.webp'),
  'roast_03.webp': require('@/assets/premium/dishes/roasts/roast_03.webp'),
  'roast_04.webp': require('@/assets/premium/dishes/roasts/roast_04.webp'),
  'roast_05.webp': require('@/assets/premium/dishes/roasts/roast_05.webp'),
  'roast_06.webp': require('@/assets/premium/dishes/roasts/roast_06.webp'),
  'roast_07.webp': require('@/assets/premium/dishes/roasts/roast_07.webp'),
  'roast_08.webp': require('@/assets/premium/dishes/roasts/roast_08.webp'),
  'roast_09.webp': require('@/assets/premium/dishes/roasts/roast_09.webp'),
  'roast_10.webp': require('@/assets/premium/dishes/roasts/roast_10.webp'),
  'roast_11.webp': require('@/assets/premium/dishes/roasts/roast_11.webp'),
  'roast_12.webp': require('@/assets/premium/dishes/roasts/roast_12.webp'),
  'roast_13.webp': require('@/assets/premium/dishes/roasts/roast_13.webp'),
  'roast_14.webp': require('@/assets/premium/dishes/roasts/roast_14.webp'),
  'roast_15.webp': require('@/assets/premium/dishes/roasts/roast_15.webp'),
  'roast_16.webp': require('@/assets/premium/dishes/roasts/roast_16.webp'),
  'roast_17.webp': require('@/assets/premium/dishes/roasts/roast_17.webp'),
  'roast_18.webp': require('@/assets/premium/dishes/roasts/roast_18.webp'),
  'roast_19.webp': require('@/assets/premium/dishes/roasts/roast_19.webp'),
  'roast_20.webp': require('@/assets/premium/dishes/roasts/roast_20.webp'),
  'roast_21.webp': require('@/assets/premium/dishes/roasts/roast_21.webp'),
  'roast_22.webp': require('@/assets/premium/dishes/roasts/roast_22.webp'),
  'roast_23.webp': require('@/assets/premium/dishes/roasts/roast_23.webp'),
  'roast_24.webp': require('@/assets/premium/dishes/roasts/roast_24.webp'),
  'roast_25.webp': require('@/assets/premium/dishes/roasts/roast_25.webp'),
};
