/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'salad_01.webp': require('@/assets/premium/dishes/salads/salad_01.webp'),
  'salad_02.webp': require('@/assets/premium/dishes/salads/salad_02.webp'),
  'salad_03.webp': require('@/assets/premium/dishes/salads/salad_03.webp'),
  'salad_04.webp': require('@/assets/premium/dishes/salads/salad_04.webp'),
  'salad_05.webp': require('@/assets/premium/dishes/salads/salad_05.webp'),
  'salad_06.webp': require('@/assets/premium/dishes/salads/salad_06.webp'),
  'salad_07.webp': require('@/assets/premium/dishes/salads/salad_07.webp'),
  'salad_08.webp': require('@/assets/premium/dishes/salads/salad_08.webp'),
  'salad_09.webp': require('@/assets/premium/dishes/salads/salad_09.webp'),
  'salad_10.webp': require('@/assets/premium/dishes/salads/salad_10.webp'),
  'salad_11.webp': require('@/assets/premium/dishes/salads/salad_11.webp'),
  'salad_12.webp': require('@/assets/premium/dishes/salads/salad_12.webp'),
  'salad_13.webp': require('@/assets/premium/dishes/salads/salad_13.webp'),
  'salad_14.webp': require('@/assets/premium/dishes/salads/salad_14.webp'),
  'salad_15.webp': require('@/assets/premium/dishes/salads/salad_15.webp'),
  'salad_16.webp': require('@/assets/premium/dishes/salads/salad_16.webp'),
  'salad_17.webp': require('@/assets/premium/dishes/salads/salad_17.webp'),
  'salad_18.webp': require('@/assets/premium/dishes/salads/salad_18.webp'),
  'salad_19.webp': require('@/assets/premium/dishes/salads/salad_19.webp'),
  'salad_20.webp': require('@/assets/premium/dishes/salads/salad_20.webp'),
  'salad_21.webp': require('@/assets/premium/dishes/salads/salad_21.webp'),
  'salad_22.webp': require('@/assets/premium/dishes/salads/salad_22.webp'),
  'salad_23.webp': require('@/assets/premium/dishes/salads/salad_23.webp'),
  'salad_24.webp': require('@/assets/premium/dishes/salads/salad_24.webp'),
  'salad_25.webp': require('@/assets/premium/dishes/salads/salad_25.webp'),
};
