/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'sauce_01.webp': require('@/assets/premium/dishes/sauces/sauce_01.webp'),
  'sauce_02.webp': require('@/assets/premium/dishes/sauces/sauce_02.webp'),
  'sauce_03.webp': require('@/assets/premium/dishes/sauces/sauce_03.webp'),
  'sauce_04.webp': require('@/assets/premium/dishes/sauces/sauce_04.webp'),
  'sauce_05.webp': require('@/assets/premium/dishes/sauces/sauce_05.webp'),
  'sauce_06.webp': require('@/assets/premium/dishes/sauces/sauce_06.webp'),
  'sauce_07.webp': require('@/assets/premium/dishes/sauces/sauce_07.webp'),
  'sauce_08.webp': require('@/assets/premium/dishes/sauces/sauce_08.webp'),
  'sauce_09.webp': require('@/assets/premium/dishes/sauces/sauce_09.webp'),
  'sauce_10.webp': require('@/assets/premium/dishes/sauces/sauce_10.webp'),
  'sauce_11.webp': require('@/assets/premium/dishes/sauces/sauce_11.webp'),
  'sauce_12.webp': require('@/assets/premium/dishes/sauces/sauce_12.webp'),
  'sauce_13.webp': require('@/assets/premium/dishes/sauces/sauce_13.webp'),
  'sauce_14.webp': require('@/assets/premium/dishes/sauces/sauce_14.webp'),
  'sauce_15.webp': require('@/assets/premium/dishes/sauces/sauce_15.webp'),
  'sauce_16.webp': require('@/assets/premium/dishes/sauces/sauce_16.webp'),
  'sauce_17.webp': require('@/assets/premium/dishes/sauces/sauce_17.webp'),
  'sauce_18.webp': require('@/assets/premium/dishes/sauces/sauce_18.webp'),
  'sauce_19.webp': require('@/assets/premium/dishes/sauces/sauce_19.webp'),
  'sauce_20.webp': require('@/assets/premium/dishes/sauces/sauce_20.webp'),
  'sauce_21.webp': require('@/assets/premium/dishes/sauces/sauce_21.webp'),
  'sauce_22.webp': require('@/assets/premium/dishes/sauces/sauce_22.webp'),
  'sauce_23.webp': require('@/assets/premium/dishes/sauces/sauce_23.webp'),
  'sauce_24.webp': require('@/assets/premium/dishes/sauces/sauce_24.webp'),
  'sauce_25.webp': require('@/assets/premium/dishes/sauces/sauce_25.webp'),
};
