/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'side_01.webp': require('@/assets/premium/dishes/sides/side_01.webp'),
  'side_02.webp': require('@/assets/premium/dishes/sides/side_02.webp'),
  'side_03.webp': require('@/assets/premium/dishes/sides/side_03.webp'),
  'side_04.webp': require('@/assets/premium/dishes/sides/side_04.webp'),
  'side_05.webp': require('@/assets/premium/dishes/sides/side_05.webp'),
  'side_06.webp': require('@/assets/premium/dishes/sides/side_06.webp'),
  'side_07.webp': require('@/assets/premium/dishes/sides/side_07.webp'),
  'side_08.webp': require('@/assets/premium/dishes/sides/side_08.webp'),
  'side_09.webp': require('@/assets/premium/dishes/sides/side_09.webp'),
  'side_10.webp': require('@/assets/premium/dishes/sides/side_10.webp'),
  'side_11.webp': require('@/assets/premium/dishes/sides/side_11.webp'),
  'side_12.webp': require('@/assets/premium/dishes/sides/side_12.webp'),
  'side_13.webp': require('@/assets/premium/dishes/sides/side_13.webp'),
  'side_14.webp': require('@/assets/premium/dishes/sides/side_14.webp'),
  'side_15.webp': require('@/assets/premium/dishes/sides/side_15.webp'),
  'side_16.webp': require('@/assets/premium/dishes/sides/side_16.webp'),
  'side_17.webp': require('@/assets/premium/dishes/sides/side_17.webp'),
  'side_18.webp': require('@/assets/premium/dishes/sides/side_18.webp'),
  'side_19.webp': require('@/assets/premium/dishes/sides/side_19.webp'),
  'side_20.webp': require('@/assets/premium/dishes/sides/side_20.webp'),
  'side_21.webp': require('@/assets/premium/dishes/sides/side_21.webp'),
  'side_22.webp': require('@/assets/premium/dishes/sides/side_22.webp'),
  'side_23.webp': require('@/assets/premium/dishes/sides/side_23.webp'),
  'side_24.webp': require('@/assets/premium/dishes/sides/side_24.webp'),
  'side_25.webp': require('@/assets/premium/dishes/sides/side_25.webp'),
};
