/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'soup_pl_01.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_01.webp'),
  'soup_pl_02.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_02.webp'),
  'soup_pl_03.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_03.webp'),
  'soup_pl_04.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_04.webp'),
  'soup_pl_05.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_05.webp'),
  'soup_pl_06.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_06.webp'),
  'soup_pl_07.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_07.webp'),
  'soup_pl_08.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_08.webp'),
  'soup_pl_09.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_09.webp'),
  'soup_pl_10.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_10.webp'),
  'soup_pl_11.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_11.webp'),
  'soup_pl_12.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_12.webp'),
  'soup_pl_13.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_13.webp'),
  'soup_pl_14.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_14.webp'),
  'soup_pl_15.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_15.webp'),
  'soup_pl_16.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_16.webp'),
  'soup_pl_17.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_17.webp'),
  'soup_pl_18.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_18.webp'),
  'soup_pl_19.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_19.webp'),
  'soup_pl_20.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_20.webp'),
  'soup_pl_21.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_21.webp'),
  'soup_pl_22.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_22.webp'),
  'soup_pl_23.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_23.webp'),
  'soup_pl_24.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_24.webp'),
  'soup_pl_25.webp': require('@/assets/premium/dishes/soups_pl/soup_pl_25.webp'),
};
