/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'soup_pl_classic_01.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_01.webp'),
  'soup_pl_classic_02.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_02.webp'),
  'soup_pl_classic_03.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_03.webp'),
  'soup_pl_classic_04.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_04.webp'),
  'soup_pl_classic_05.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_05.webp'),
  'soup_pl_classic_06.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_06.webp'),
  'soup_pl_classic_07.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_07.webp'),
  'soup_pl_classic_08.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_08.webp'),
  'soup_pl_classic_09.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_09.webp'),
  'soup_pl_classic_10.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_10.webp'),
  'soup_pl_classic_11.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_11.webp'),
  'soup_pl_classic_12.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_12.webp'),
  'soup_pl_classic_13.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_13.webp'),
  'soup_pl_classic_14.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_14.webp'),
  'soup_pl_classic_15.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_15.webp'),
  'soup_pl_classic_16.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_16.webp'),
  'soup_pl_classic_17.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_17.webp'),
  'soup_pl_classic_18.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_18.webp'),
  'soup_pl_classic_19.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_19.webp'),
  'soup_pl_classic_20.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_20.webp'),
  'soup_pl_classic_21.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_21.webp'),
  'soup_pl_classic_22.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_22.webp'),
  'soup_pl_classic_23.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_23.webp'),
  'soup_pl_classic_24.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_24.webp'),
  'soup_pl_classic_25.webp': require('@/assets/premium/dishes/soups_polish/soup_pl_classic_25.webp'),
};
