/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'soup_asia_01.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_01.webp'),
  'soup_asia_02.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_02.webp'),
  'soup_asia_03.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_03.webp'),
  'soup_asia_04.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_04.webp'),
  'soup_asia_05.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_05.webp'),
  'soup_asia_06.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_06.webp'),
  'soup_asia_07.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_07.webp'),
  'soup_asia_08.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_08.webp'),
  'soup_asia_09.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_09.webp'),
  'soup_asia_10.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_10.webp'),
  'soup_asia_11.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_11.webp'),
  'soup_asia_12.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_12.webp'),
  'soup_asia_13.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_13.webp'),
  'soup_asia_14.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_14.webp'),
  'soup_asia_15.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_15.webp'),
  'soup_asia_16.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_16.webp'),
  'soup_asia_17.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_17.webp'),
  'soup_asia_18.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_18.webp'),
  'soup_asia_19.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_19.webp'),
  'soup_asia_20.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_20.webp'),
  'soup_asia_21.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_21.webp'),
  'soup_asia_22.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_22.webp'),
  'soup_asia_23.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_23.webp'),
  'soup_asia_24.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_24.webp'),
  'soup_asia_25.webp': require('@/assets/premium/dishes/soups_asia/soup_asia_25.webp'),
};
