/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'spirit_01.webp': require('@/assets/premium/dishes/spirits/spirit_01.webp'),
  'spirit_02.webp': require('@/assets/premium/dishes/spirits/spirit_02.webp'),
  'spirit_03.webp': require('@/assets/premium/dishes/spirits/spirit_03.webp'),
  'spirit_04.webp': require('@/assets/premium/dishes/spirits/spirit_04.webp'),
  'spirit_05.webp': require('@/assets/premium/dishes/spirits/spirit_05.webp'),
  'spirit_06.webp': require('@/assets/premium/dishes/spirits/spirit_06.webp'),
  'spirit_07.webp': require('@/assets/premium/dishes/spirits/spirit_07.webp'),
  'spirit_08.webp': require('@/assets/premium/dishes/spirits/spirit_08.webp'),
  'spirit_09.webp': require('@/assets/premium/dishes/spirits/spirit_09.webp'),
  'spirit_10.webp': require('@/assets/premium/dishes/spirits/spirit_10.webp'),
  'spirit_11.webp': require('@/assets/premium/dishes/spirits/spirit_11.webp'),
  'spirit_12.webp': require('@/assets/premium/dishes/spirits/spirit_12.webp'),
  'spirit_13.webp': require('@/assets/premium/dishes/spirits/spirit_13.webp'),
  'spirit_14.webp': require('@/assets/premium/dishes/spirits/spirit_14.webp'),
  'spirit_15.webp': require('@/assets/premium/dishes/spirits/spirit_15.webp'),
  'spirit_16.webp': require('@/assets/premium/dishes/spirits/spirit_16.webp'),
  'spirit_17.webp': require('@/assets/premium/dishes/spirits/spirit_17.webp'),
  'spirit_18.webp': require('@/assets/premium/dishes/spirits/spirit_18.webp'),
  'spirit_19.webp': require('@/assets/premium/dishes/spirits/spirit_19.webp'),
  'spirit_20.webp': require('@/assets/premium/dishes/spirits/spirit_20.webp'),
  'spirit_21.webp': require('@/assets/premium/dishes/spirits/spirit_21.webp'),
  'spirit_22.webp': require('@/assets/premium/dishes/spirits/spirit_22.webp'),
  'spirit_23.webp': require('@/assets/premium/dishes/spirits/spirit_23.webp'),
  'spirit_24.webp': require('@/assets/premium/dishes/spirits/spirit_24.webp'),
  'spirit_25.webp': require('@/assets/premium/dishes/spirits/spirit_25.webp'),
};
