/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'starter_01.webp': require('@/assets/premium/dishes/starters/starter_01.webp'),
  'starter_02.webp': require('@/assets/premium/dishes/starters/starter_02.webp'),
  'starter_03.webp': require('@/assets/premium/dishes/starters/starter_03.webp'),
  'starter_04.webp': require('@/assets/premium/dishes/starters/starter_04.webp'),
  'starter_05.webp': require('@/assets/premium/dishes/starters/starter_05.webp'),
  'starter_06.webp': require('@/assets/premium/dishes/starters/starter_06.webp'),
  'starter_07.webp': require('@/assets/premium/dishes/starters/starter_07.webp'),
  'starter_08.webp': require('@/assets/premium/dishes/starters/starter_08.webp'),
  'starter_09.webp': require('@/assets/premium/dishes/starters/starter_09.webp'),
  'starter_10.webp': require('@/assets/premium/dishes/starters/starter_10.webp'),
  'starter_11.webp': require('@/assets/premium/dishes/starters/starter_11.webp'),
  'starter_12.webp': require('@/assets/premium/dishes/starters/starter_12.webp'),
  'starter_13.webp': require('@/assets/premium/dishes/starters/starter_13.webp'),
  'starter_14.webp': require('@/assets/premium/dishes/starters/starter_14.webp'),
  'starter_15.webp': require('@/assets/premium/dishes/starters/starter_15.webp'),
  'starter_16.webp': require('@/assets/premium/dishes/starters/starter_16.webp'),
  'starter_17.webp': require('@/assets/premium/dishes/starters/starter_17.webp'),
  'starter_18.webp': require('@/assets/premium/dishes/starters/starter_18.webp'),
  'starter_19.webp': require('@/assets/premium/dishes/starters/starter_19.webp'),
  'starter_20.webp': require('@/assets/premium/dishes/starters/starter_20.webp'),
  'starter_21.webp': require('@/assets/premium/dishes/starters/starter_21.webp'),
  'starter_22.webp': require('@/assets/premium/dishes/starters/starter_22.webp'),
  'starter_23.webp': require('@/assets/premium/dishes/starters/starter_23.webp'),
  'starter_24.webp': require('@/assets/premium/dishes/starters/starter_24.webp'),
  'starter_25.webp': require('@/assets/premium/dishes/starters/starter_25.webp'),
};
