/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'street_01.webp': require('@/assets/premium/dishes/street/street_01.webp'),
  'street_02.webp': require('@/assets/premium/dishes/street/street_02.webp'),
  'street_03.webp': require('@/assets/premium/dishes/street/street_03.webp'),
  'street_04.webp': require('@/assets/premium/dishes/street/street_04.webp'),
  'street_05.webp': require('@/assets/premium/dishes/street/street_05.webp'),
  'street_06.webp': require('@/assets/premium/dishes/street/street_06.webp'),
  'street_07.webp': require('@/assets/premium/dishes/street/street_07.webp'),
  'street_08.webp': require('@/assets/premium/dishes/street/street_08.webp'),
  'street_09.webp': require('@/assets/premium/dishes/street/street_09.webp'),
  'street_10.webp': require('@/assets/premium/dishes/street/street_10.webp'),
  'street_11.webp': require('@/assets/premium/dishes/street/street_11.webp'),
  'street_12.webp': require('@/assets/premium/dishes/street/street_12.webp'),
  'street_13.webp': require('@/assets/premium/dishes/street/street_13.webp'),
  'street_14.webp': require('@/assets/premium/dishes/street/street_14.webp'),
  'street_15.webp': require('@/assets/premium/dishes/street/street_15.webp'),
  'street_16.webp': require('@/assets/premium/dishes/street/street_16.webp'),
  'street_17.webp': require('@/assets/premium/dishes/street/street_17.webp'),
  'street_18.webp': require('@/assets/premium/dishes/street/street_18.webp'),
  'street_19.webp': require('@/assets/premium/dishes/street/street_19.webp'),
  'street_20.webp': require('@/assets/premium/dishes/street/street_20.webp'),
  'street_21.webp': require('@/assets/premium/dishes/street/street_21.webp'),
  'street_22.webp': require('@/assets/premium/dishes/street/street_22.webp'),
  'street_23.webp': require('@/assets/premium/dishes/street/street_23.webp'),
  'street_24.webp': require('@/assets/premium/dishes/street/street_24.webp'),
  'street_25.webp': require('@/assets/premium/dishes/street/street_25.webp'),
};
