/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'sushi_01.webp': require('@/assets/premium/dishes/sushi/sushi_01.webp'),
  'sushi_02.webp': require('@/assets/premium/dishes/sushi/sushi_02.webp'),
  'sushi_03.webp': require('@/assets/premium/dishes/sushi/sushi_03.webp'),
  'sushi_04.webp': require('@/assets/premium/dishes/sushi/sushi_04.webp'),
  'sushi_05.webp': require('@/assets/premium/dishes/sushi/sushi_05.webp'),
  'sushi_06.webp': require('@/assets/premium/dishes/sushi/sushi_06.webp'),
  'sushi_07.webp': require('@/assets/premium/dishes/sushi/sushi_07.webp'),
  'sushi_08.webp': require('@/assets/premium/dishes/sushi/sushi_08.webp'),
  'sushi_09.webp': require('@/assets/premium/dishes/sushi/sushi_09.webp'),
  'sushi_10.webp': require('@/assets/premium/dishes/sushi/sushi_10.webp'),
  'sushi_11.webp': require('@/assets/premium/dishes/sushi/sushi_11.webp'),
  'sushi_12.webp': require('@/assets/premium/dishes/sushi/sushi_12.webp'),
  'sushi_13.webp': require('@/assets/premium/dishes/sushi/sushi_13.webp'),
  'sushi_14.webp': require('@/assets/premium/dishes/sushi/sushi_14.webp'),
  'sushi_15.webp': require('@/assets/premium/dishes/sushi/sushi_15.webp'),
  'sushi_16.webp': require('@/assets/premium/dishes/sushi/sushi_16.webp'),
  'sushi_17.webp': require('@/assets/premium/dishes/sushi/sushi_17.webp'),
  'sushi_18.webp': require('@/assets/premium/dishes/sushi/sushi_18.webp'),
  'sushi_19.webp': require('@/assets/premium/dishes/sushi/sushi_19.webp'),
  'sushi_20.webp': require('@/assets/premium/dishes/sushi/sushi_20.webp'),
  'sushi_21.webp': require('@/assets/premium/dishes/sushi/sushi_21.webp'),
  'sushi_22.webp': require('@/assets/premium/dishes/sushi/sushi_22.webp'),
  'sushi_23.webp': require('@/assets/premium/dishes/sushi/sushi_23.webp'),
  'sushi_24.webp': require('@/assets/premium/dishes/sushi/sushi_24.webp'),
  'sushi_25.webp': require('@/assets/premium/dishes/sushi/sushi_25.webp'),
};
