/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'tea_01.webp': require('@/assets/premium/dishes/teas/tea_01.webp'),
  'tea_02.webp': require('@/assets/premium/dishes/teas/tea_02.webp'),
  'tea_03.webp': require('@/assets/premium/dishes/teas/tea_03.webp'),
  'tea_04.webp': require('@/assets/premium/dishes/teas/tea_04.webp'),
  'tea_05.webp': require('@/assets/premium/dishes/teas/tea_05.webp'),
  'tea_06.webp': require('@/assets/premium/dishes/teas/tea_06.webp'),
  'tea_07.webp': require('@/assets/premium/dishes/teas/tea_07.webp'),
  'tea_08.webp': require('@/assets/premium/dishes/teas/tea_08.webp'),
  'tea_09.webp': require('@/assets/premium/dishes/teas/tea_09.webp'),
  'tea_10.webp': require('@/assets/premium/dishes/teas/tea_10.webp'),
  'tea_11.webp': require('@/assets/premium/dishes/teas/tea_11.webp'),
  'tea_12.webp': require('@/assets/premium/dishes/teas/tea_12.webp'),
  'tea_13.webp': require('@/assets/premium/dishes/teas/tea_13.webp'),
  'tea_14.webp': require('@/assets/premium/dishes/teas/tea_14.webp'),
  'tea_15.webp': require('@/assets/premium/dishes/teas/tea_15.webp'),
  'tea_16.webp': require('@/assets/premium/dishes/teas/tea_16.webp'),
  'tea_17.webp': require('@/assets/premium/dishes/teas/tea_17.webp'),
  'tea_18.webp': require('@/assets/premium/dishes/teas/tea_18.webp'),
  'tea_19.webp': require('@/assets/premium/dishes/teas/tea_19.webp'),
  'tea_20.webp': require('@/assets/premium/dishes/teas/tea_20.webp'),
  'tea_21.webp': require('@/assets/premium/dishes/teas/tea_21.webp'),
  'tea_22.webp': require('@/assets/premium/dishes/teas/tea_22.webp'),
  'tea_23.webp': require('@/assets/premium/dishes/teas/tea_23.webp'),
  'tea_24.webp': require('@/assets/premium/dishes/teas/tea_24.webp'),
  'tea_25.webp': require('@/assets/premium/dishes/teas/tea_25.webp'),
};
