/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'vegan_01.webp': require('@/assets/premium/dishes/vegan/vegan_01.webp'),
  'vegan_02.webp': require('@/assets/premium/dishes/vegan/vegan_02.webp'),
  'vegan_03.webp': require('@/assets/premium/dishes/vegan/vegan_03.webp'),
  'vegan_04.webp': require('@/assets/premium/dishes/vegan/vegan_04.webp'),
  'vegan_05.webp': require('@/assets/premium/dishes/vegan/vegan_05.webp'),
  'vegan_06.webp': require('@/assets/premium/dishes/vegan/vegan_06.webp'),
  'vegan_07.webp': require('@/assets/premium/dishes/vegan/vegan_07.webp'),
  'vegan_08.webp': require('@/assets/premium/dishes/vegan/vegan_08.webp'),
  'vegan_09.webp': require('@/assets/premium/dishes/vegan/vegan_09.webp'),
  'vegan_10.webp': require('@/assets/premium/dishes/vegan/vegan_10.webp'),
  'vegan_11.webp': require('@/assets/premium/dishes/vegan/vegan_11.webp'),
  'vegan_12.webp': require('@/assets/premium/dishes/vegan/vegan_12.webp'),
  'vegan_13.webp': require('@/assets/premium/dishes/vegan/vegan_13.webp'),
  'vegan_14.webp': require('@/assets/premium/dishes/vegan/vegan_14.webp'),
  'vegan_15.webp': require('@/assets/premium/dishes/vegan/vegan_15.webp'),
  'vegan_16.webp': require('@/assets/premium/dishes/vegan/vegan_16.webp'),
  'vegan_17.webp': require('@/assets/premium/dishes/vegan/vegan_17.webp'),
  'vegan_18.webp': require('@/assets/premium/dishes/vegan/vegan_18.webp'),
  'vegan_19.webp': require('@/assets/premium/dishes/vegan/vegan_19.webp'),
  'vegan_20.webp': require('@/assets/premium/dishes/vegan/vegan_20.webp'),
  'vegan_21.webp': require('@/assets/premium/dishes/vegan/vegan_21.webp'),
  'vegan_22.webp': require('@/assets/premium/dishes/vegan/vegan_22.webp'),
  'vegan_23.webp': require('@/assets/premium/dishes/vegan/vegan_23.webp'),
  'vegan_24.webp': require('@/assets/premium/dishes/vegan/vegan_24.webp'),
  'vegan_25.webp': require('@/assets/premium/dishes/vegan/vegan_25.webp'),
};
