/** Auto-generated — nie edytuj ręcznie. */
export const ASSETS: Record<string, number> = {
  'wine_01.webp': require('@/assets/premium/dishes/wines/wine_01.webp'),
  'wine_02.webp': require('@/assets/premium/dishes/wines/wine_02.webp'),
  'wine_03.webp': require('@/assets/premium/dishes/wines/wine_03.webp'),
  'wine_04.webp': require('@/assets/premium/dishes/wines/wine_04.webp'),
  'wine_05.webp': require('@/assets/premium/dishes/wines/wine_05.webp'),
  'wine_06.webp': require('@/assets/premium/dishes/wines/wine_06.webp'),
  'wine_07.webp': require('@/assets/premium/dishes/wines/wine_07.webp'),
  'wine_08.webp': require('@/assets/premium/dishes/wines/wine_08.webp'),
  'wine_09.webp': require('@/assets/premium/dishes/wines/wine_09.webp'),
  'wine_10.webp': require('@/assets/premium/dishes/wines/wine_10.webp'),
  'wine_11.webp': require('@/assets/premium/dishes/wines/wine_11.webp'),
  'wine_12.webp': require('@/assets/premium/dishes/wines/wine_12.webp'),
  'wine_13.webp': require('@/assets/premium/dishes/wines/wine_13.webp'),
  'wine_14.webp': require('@/assets/premium/dishes/wines/wine_14.webp'),
  'wine_15.webp': require('@/assets/premium/dishes/wines/wine_15.webp'),
  'wine_16.webp': require('@/assets/premium/dishes/wines/wine_16.webp'),
  'wine_17.webp': require('@/assets/premium/dishes/wines/wine_17.webp'),
  'wine_18.webp': require('@/assets/premium/dishes/wines/wine_18.webp'),
  'wine_19.webp': require('@/assets/premium/dishes/wines/wine_19.webp'),
  'wine_20.webp': require('@/assets/premium/dishes/wines/wine_20.webp'),
  'wine_21.webp': require('@/assets/premium/dishes/wines/wine_21.webp'),
  'wine_22.webp': require('@/assets/premium/dishes/wines/wine_22.webp'),
  'wine_23.webp': require('@/assets/premium/dishes/wines/wine_23.webp'),
  'wine_24.webp': require('@/assets/premium/dishes/wines/wine_24.webp'),
  'wine_25.webp': require('@/assets/premium/dishes/wines/wine_25.webp'),
};
