import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/constants/colors';
import { DS } from '@/constants/premiumTheme';

export const magazynScreenStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  scanSyncOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(6, 12, 10, 0.82)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 80,
    paddingHorizontal: 28,
  },
  scanSyncCard: {
    backgroundColor: DS.color.surfaceCard,
    borderWidth: 1,
    borderColor: DS.color.borderSubtle,
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
    gap: 10,
    maxWidth: 320,
    width: '100%',
  },
  scanSyncTitle: {
    color: DS.color.heading,
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  scanSyncSub: {
    color: DS.color.muted,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: '800', color: Colors.textPrimary, letterSpacing: -0.5 },
  subtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2, fontWeight: '500' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8, justifyContent: 'flex-end' },
  actionBtnsWrap: {
    paddingHorizontal: DS.space.screen,
    marginBottom: 14,
    alignItems: 'stretch',
  },
  actionBtnsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  magPillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 6,
    paddingRight: 14,
    paddingVertical: 8,
    borderRadius: 22,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  magPillIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  magPillText: {
    color: '#0F172A',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  addHeaderBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: Colors.accentLight, borderRadius: 8, borderWidth: 1, borderColor: '#BFDBFE' },
  addHeaderBtnText: { fontSize: 12, fontWeight: '600', color: Colors.accent },
  wasteBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: Colors.dangerLight, borderRadius: 8, borderWidth: 1, borderColor: '#FECACA' },
  wasteBtnText: { fontSize: 12, fontWeight: '600', color: Colors.danger },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.card, borderRadius: 10, marginHorizontal: 16, marginBottom: 10, paddingHorizontal: 12, paddingVertical: 10, gap: 8, borderWidth: 1, borderColor: Colors.border },
  searchInput: { flex: 1, fontSize: 13, color: Colors.textPrimary, padding: 0 },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 16 },
  catSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 10, paddingHorizontal: 2 },
  catSectionTitle: { fontSize: 12, fontWeight: '700', color: Colors.textSecondary, letterSpacing: 0.5 },
  addCatBtnWrap: { borderRadius: 8 },
  addCatBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  addCatBtnText: { fontSize: 11, fontWeight: '600', color: Colors.accent },
  addCatBtnTextPrem: { fontSize: 11, fontWeight: '800', color: '#0A0A0A' },
  searchResultLabel: { fontSize: 11, fontWeight: '600', color: Colors.textTertiary, letterSpacing: 0.4, marginBottom: 10, paddingHorizontal: 2 },
  emptyWrap: { alignItems: 'center', paddingVertical: 56, gap: 10 },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: Colors.textPrimary },
  emptyText: { fontSize: 13, color: Colors.textSecondary, textAlign: 'center', maxWidth: 280 },
  fabContainer: { position: 'absolute', bottom: 24, right: 20, alignItems: 'flex-end' },
  fabWrap: { borderRadius: 28 },
  fab: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  fabMini: { position: 'absolute', bottom: 0, right: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  fabMiniBtn: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', shadowColor: Colors.shadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 5, elevation: 5 },
  fabMiniLabel: { backgroundColor: Colors.textPrimary, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 7 },
  fabMiniLabelText: { color: Colors.white, fontSize: 12, fontWeight: '600' },
  modalSafe: { flex: 1, backgroundColor: Colors.background },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.card },
  modalTitle: { fontSize: 18, fontWeight: '700', color: Colors.textPrimary },
  modalSubtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 1 },
  closeBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: Colors.borderLight, alignItems: 'center', justifyContent: 'center' },
  modalContent: { padding: 16 },
  formScroll: { padding: 20 },
  formSection: { fontSize: 11, fontWeight: '700', color: Colors.textSecondary, letterSpacing: 0.5, marginBottom: 12, marginTop: 20 },
  fieldWrap: { marginBottom: 14 },
  fieldRow: { flexDirection: 'row', gap: 10 },
  fieldHint: { fontSize: 11, color: Colors.textTertiary, marginTop: 5 },
  pillRow: { flexDirection: 'row', gap: 8, paddingBottom: 2 },
  formPill: { flexDirection: 'row', alignItems: 'center', borderRadius: 20, borderWidth: 1.5, borderColor: Colors.border, backgroundColor: Colors.card, overflow: 'hidden' },
  formPillMain: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 8 },
  formPillDelete: { paddingRight: 10, paddingLeft: 2, paddingVertical: 8 },
  formPillText: { fontSize: 12, fontWeight: '500', color: Colors.textSecondary },
  formPillCount: { fontSize: 10, fontWeight: '700', color: Colors.textTertiary },
  unitRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  unitBtn: { paddingHorizontal: 16, paddingVertical: 11, borderRadius: 10, borderWidth: 1.5, borderColor: Colors.border, backgroundColor: Colors.card, alignItems: 'center', minWidth: 48 },
  unitBtnActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  unitBtnText: { fontSize: 14, fontWeight: '600', color: Colors.textSecondary },
  unitBtnTextActive: { color: Colors.white },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border, marginBottom: 14 },
  portionInfoBox: { marginBottom: 14, backgroundColor: Colors.accentLight, borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: Colors.accent },
  portionInfoText: { fontSize: 12, color: Colors.textSecondary, lineHeight: 17 },
  wvRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  wvToggle: { flexDirection: 'row', backgroundColor: Colors.borderLight, borderRadius: 10, padding: 3, borderWidth: 1.5, borderColor: Colors.border },
  wvToggleBtn: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 8 },
  wvToggleBtnActive: { backgroundColor: Colors.accent },
  wvToggleText: { fontSize: 14, fontWeight: '700', color: Colors.textSecondary },
  wvToggleTextActive: { color: Colors.white },
  switchInfo: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, flex: 1 },
  switchLabel: { fontSize: 14, fontWeight: '600', color: Colors.textPrimary },
  switchHint: { fontSize: 11, color: Colors.textSecondary, marginTop: 2, lineHeight: 15 },
  previewWrap: { marginTop: 8, marginBottom: 4 },
  previewLabel: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary, letterSpacing: 0.4, marginBottom: 8 },
  saveBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: Colors.accent, paddingVertical: 15, borderRadius: 12, marginTop: 8, shadowColor: Colors.accent, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 5 },
  saveBtnText: { fontSize: 16, fontWeight: '700', color: Colors.white },
  wasteRow: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: Colors.card, borderRadius: 10, padding: 14, marginBottom: 8, borderWidth: 1, borderColor: Colors.border, gap: 12 },
  wasteLeft: { flex: 1, gap: 3 },
  wasteName: { fontSize: 14, fontWeight: '600', color: Colors.textPrimary },
  wasteReason: { fontSize: 12, color: Colors.textSecondary, lineHeight: 16 },
  wasteDate: { fontSize: 11, color: Colors.textTertiary, marginTop: 2 },
  wasteRight: { alignItems: 'flex-end', justifyContent: 'center' },
  wasteQty: { fontSize: 15, fontWeight: '700', color: Colors.danger },
  catOverlay: { flex: 1, backgroundColor: Colors.overlay, alignItems: 'center', justifyContent: 'center', padding: 24 },
  catModal: { backgroundColor: Colors.card, borderRadius: 20, padding: 24, width: '100%', maxWidth: 360, gap: 16 },
  catModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  catModalTitle: { fontSize: 17, fontWeight: '700', color: Colors.textPrimary },
  catInput: { backgroundColor: Colors.borderLight, borderRadius: 10, paddingHorizontal: 14, paddingVertical: Platform.OS === 'ios' ? 12 : 10, fontSize: 15, color: Colors.textPrimary, borderWidth: 1.5, borderColor: Colors.border },
  catModalBtns: { flexDirection: 'row', gap: 10 },
  catCancelBtn: { flex: 1, backgroundColor: Colors.borderLight, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  catCancelText: { fontSize: 14, fontWeight: '600', color: Colors.textSecondary },
  catSaveBtn: { flex: 2, backgroundColor: Colors.accent, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  catSaveText: { fontSize: 14, fontWeight: '700', color: Colors.white },
});
