/**
 * Katalog grafik — piwa i napoje piwne (plansza 5×5).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const BEERS_CATALOG: DishImageEntry[] = [
  { slug: 'hazy_ipa', category: 'kuchnia_polska', labelPl: 'Piwo kraftowe Hazy IPA', aliases: ['hazy ipa', 'ipa', 'kraftowe ipa'], storagePath: 'dania/beers/beer_01.webp', localAsset: require('@/assets/premium/dishes/beers/beer_01.webp') },
  { slug: 'lager_klasyczny', category: 'kuchnia_polska', labelPl: 'Jasny Lager klasyczny', aliases: ['lager', 'jasne piwo', 'pilsner glass'], storagePath: 'dania/beers/beer_02.webp', localAsset: require('@/assets/premium/dishes/beers/beer_02.webp') },
  { slug: 'stout', category: 'kuchnia_polska', labelPl: 'Ciemny Stout', aliases: ['stout', 'ciemne piwo stout'], storagePath: 'dania/beers/beer_03.webp', localAsset: require('@/assets/premium/dishes/beers/beer_03.webp') },
  { slug: 'amber_ale', category: 'kuchnia_polska', labelPl: 'Bursztynowe Ale (Amber Ale)', aliases: ['amber ale', 'bursztynowe ale'], storagePath: 'dania/beers/beer_04.webp', localAsset: require('@/assets/premium/dishes/beers/beer_04.webp') },
  { slug: 'hefeweizen', category: 'kuchnia_polska', labelPl: 'Piwo pszeniczne (Hefeweizen)', aliases: ['hefeweizen', 'pszeniczne', 'weissbier'], storagePath: 'dania/beers/beer_05.webp', localAsset: require('@/assets/premium/dishes/beers/beer_05.webp') },
  { slug: 'sour_ale', category: 'kuchnia_polska', labelPl: 'Kwaśne piwo owocowe (Sour Ale)', aliases: ['sour ale', 'kwaśne piwo', 'sour'], storagePath: 'dania/beers/beer_06.webp', localAsset: require('@/assets/premium/dishes/beers/beer_06.webp') },
  { slug: 'dubbel', category: 'kuchnia_polska', labelPl: 'Belgijskie piwo Dubbel', aliases: ['dubbel', 'belgian dubbel', 'belgijskie'], storagePath: 'dania/beers/beer_07.webp', localAsset: require('@/assets/premium/dishes/beers/beer_07.webp') },
  { slug: 'porter', category: 'kuchnia_polska', labelPl: 'Piwo ciemne typu Porter', aliases: ['porter', 'piwo porter'], storagePath: 'dania/beers/beer_08.webp', localAsset: require('@/assets/premium/dishes/beers/beer_08.webp') },
  { slug: 'puszka_hazy_ipa', category: 'kuchnia_polska', labelPl: 'Puszka piwa rzemieślniczego Hazy IPA', aliases: ['puszka hazy ipa', 'hazy ipa can'], storagePath: 'dania/beers/beer_09.webp', localAsset: require('@/assets/premium/dishes/beers/beer_09.webp') },
  { slug: 'butelka_kraftowa', category: 'kuchnia_polska', labelPl: 'Brązowa butelka piwa kraftowego', aliases: ['butelka piwa', 'brown bottle', 'kraftowa butelka'], storagePath: 'dania/beers/beer_10.webp', localAsset: require('@/assets/premium/dishes/beers/beer_10.webp') },
  { slug: 'piwo_miodowe', category: 'kuchnia_polska', labelPl: 'Piwo miodowe / jasne pełne', aliases: ['piwo miodowe', 'jasne pełne', 'honey beer'], storagePath: 'dania/beers/beer_11.webp', localAsset: require('@/assets/premium/dishes/beers/beer_11.webp') },
  { slug: 'butelka_lager_zielona', category: 'kuchnia_polska', labelPl: 'Zielona butelka klasycznego lagera', aliases: ['zielona butelka', 'lager bottle', 'butelka lager'], storagePath: 'dania/beers/beer_12.webp', localAsset: require('@/assets/premium/dishes/beers/beer_12.webp') },
  { slug: 'radler_grejpfrut', category: 'kuchnia_polska', labelPl: 'Radler grejpfrutowy', aliases: ['radler', 'radler grejpfrutowy', 'shandy'], storagePath: 'dania/beers/beer_13.webp', localAsset: require('@/assets/premium/dishes/beers/beer_13.webp') },
  { slug: 'piwo_bezalkoholowe', category: 'kuchnia_polska', labelPl: 'Piwo bezalkoholowe z limonką', aliases: ['piwo bezalkoholowe', '0%', 'non alcoholic beer'], storagePath: 'dania/beers/beer_14.webp', localAsset: require('@/assets/premium/dishes/beers/beer_14.webp') },
  { slug: 'cider_jablkowy', category: 'kuchnia_polska', labelPl: 'Cider (Cydr jabłkowy) z lodem', aliases: ['cider', 'cydr', 'apple cider'], storagePath: 'dania/beers/beer_15.webp', localAsset: require('@/assets/premium/dishes/beers/beer_15.webp') },
  { slug: 'imperial_stout', category: 'kuchnia_polska', labelPl: 'Imperial Stout', aliases: ['imperial stout', 'rusky imperial'], storagePath: 'dania/beers/beer_16.webp', localAsset: require('@/assets/premium/dishes/beers/beer_16.webp') },
  { slug: 'black_ipa', category: 'kuchnia_polska', labelPl: 'Black IPA', aliases: ['black ipa', 'cascadian dark'], storagePath: 'dania/beers/beer_17.webp', localAsset: require('@/assets/premium/dishes/beers/beer_17.webp') },
  { slug: 'puszka_pale_ale', category: 'kuchnia_polska', labelPl: 'Puszka piwa Pale Ale', aliases: ['pale ale', 'puszka pale ale'], storagePath: 'dania/beers/beer_18.webp', localAsset: require('@/assets/premium/dishes/beers/beer_18.webp') },
  { slug: 'dunkel', category: 'kuchnia_polska', labelPl: 'Tradycyjne piwo ciemne (Dunkel)', aliases: ['dunkel', 'ciemny lager', 'munich dunkel'], storagePath: 'dania/beers/beer_19.webp', localAsset: require('@/assets/premium/dishes/beers/beer_19.webp') },
  { slug: 'puszka_pilsner', category: 'kuchnia_polska', labelPl: 'Puszka jasnego lagera / pilsnera', aliases: ['pilsner', 'puszka pilsner', 'pilsner lager'], storagePath: 'dania/beers/beer_20.webp', localAsset: require('@/assets/premium/dishes/beers/beer_20.webp') },
  { slug: 'irish_red_ale', category: 'kuchnia_polska', labelPl: 'Czerwone Ale irlandzkie (Irish Red Ale)', aliases: ['irish red', 'red ale', 'irlandzkie ale'], storagePath: 'dania/beers/beer_21.webp', localAsset: require('@/assets/premium/dishes/beers/beer_21.webp') },
  { slug: 'stout_czekoladowy_kufel', category: 'kuchnia_polska', labelPl: 'Ciemny Stout czekoladowy w kuflu', aliases: ['stout czekoladowy', 'chocolate stout', 'kufel stout'], storagePath: 'dania/beers/beer_22.webp', localAsset: require('@/assets/premium/dishes/beers/beer_22.webp') },
  { slug: 'ginger_beer_bar', category: 'kuchnia_polska', labelPl: 'Piwo imbirowe z lodem (Ginger Beer)', aliases: ['ginger beer', 'piwo imbirowe'], storagePath: 'dania/beers/beer_23.webp', localAsset: require('@/assets/premium/dishes/beers/beer_23.webp') },
  { slug: 'marzen_dymione', category: 'kuchnia_polska', labelPl: 'Klasyczne piwo marcowe / dymione', aliases: ['märzen', 'marzen', 'rauchbier', 'marcowe'], storagePath: 'dania/beers/beer_24.webp', localAsset: require('@/assets/premium/dishes/beers/beer_24.webp') },
  { slug: 'precelki_barowe', category: 'kuchnia_polska', labelPl: 'Miseczka z chrupiącymi precelkami', aliases: ['precelki', 'pretzels', 'przekąska barowa'], storagePath: 'dania/beers/beer_25.webp', localAsset: require('@/assets/premium/dishes/beers/beer_25.webp'), recipeEligible: false },
];
