/**
 * Katalog grafik — ciasta + desery w kubkach (plansze 5×5).
 */
type DishImageEntry = {
  slug: string;
  category: 'kuchnia_polska';
  labelPl: string;
  aliases: string[];
  storagePath: string;
  localAsset: number;
  recipeEligible?: boolean;
};

export const CAKES_CATALOG: DishImageEntry[] = [
  { slug: 'sernik_nowojorski', category: 'kuchnia_polska', labelPl: 'Sernik nowojorski z polewą malinową', aliases: ['sernik nowojorski', 'new york cheesecake', 'cheesecake'], storagePath: 'dania/cakes/cake_01.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_01.webp') },
  { slug: 'szarlotka_tradycyjna', category: 'kuchnia_polska', labelPl: 'Szarlotka tradycyjna z jabłkami', aliases: ['szarlotka', 'apple pie', 'ciasto jabłkowe'], storagePath: 'dania/cakes/cake_02.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_02.webp') },
  { slug: 'brownie_czekoladowe', category: 'kuchnia_polska', labelPl: 'Brownie czekoladowe', aliases: ['brownie', 'brownie czekoladowe'], storagePath: 'dania/cakes/cake_03.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_03.webp') },
  { slug: 'ciasto_marchewkowe', category: 'kuchnia_polska', labelPl: 'Ciasto marchewkowe z kremem', aliases: ['ciasto marchewkowe', 'carrot cake', 'marchewkowe'], storagePath: 'dania/cakes/cake_04.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_04.webp') },
  { slug: 'tarta_owocowa', category: 'kuchnia_polska', labelPl: 'Tarta owocowa z kremem budyniowym', aliases: ['tarta owocowa', 'fruit tart'], storagePath: 'dania/cakes/cake_05.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_05.webp') },
  { slug: 'miodownik', category: 'kuchnia_polska', labelPl: 'Miodownik', aliases: ['miodownik', 'ciasto miodowe', 'honey cake'], storagePath: 'dania/cakes/cake_06.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_06.webp') },
  { slug: 'mini_pavlova', category: 'kuchnia_polska', labelPl: 'Mini Pavlova', aliases: ['pavlova', 'mini pavlova', 'beza'], storagePath: 'dania/cakes/cake_07.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_07.webp') },
  { slug: 'tiramisu_ciasto', category: 'kuchnia_polska', labelPl: 'Tiramisu klasyczne', aliases: ['tiramisu', 'tiramisu klasyczne'], storagePath: 'dania/cakes/cake_08.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_08.webp') },
  { slug: 'tort_czekoladowy_fudge', category: 'kuchnia_polska', labelPl: 'Tort czekoladowy fudge', aliases: ['tort czekoladowy', 'fudge cake', 'chocolate fudge'], storagePath: 'dania/cakes/cake_09.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_09.webp') },
  { slug: 'red_velvet', category: 'kuchnia_polska', labelPl: 'Ciasto Red Velvet', aliases: ['red velvet', 'czerwony biszkopt'], storagePath: 'dania/cakes/cake_10.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_10.webp') },
  { slug: 'tarta_cytrynowa_beza', category: 'kuchnia_polska', labelPl: 'Tarta cytrynowa z bezą', aliases: ['tarta cytrynowa', 'lemon meringue', 'lemon pie'], storagePath: 'dania/cakes/cake_11.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_11.webp') },
  { slug: 'victoria_sponge', category: 'kuchnia_polska', labelPl: 'Biszkopt Wiktorii', aliases: ['victoria sponge', 'biszkopt wiktorii'], storagePath: 'dania/cakes/cake_12.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_12.webp') },
  { slug: 'tort_szwarcwaldzki', category: 'kuchnia_polska', labelPl: 'Tort Szwarcwaldzki (Czarny Las)', aliases: ['szwarcwaldzki', 'black forest', 'czarny las'], storagePath: 'dania/cakes/cake_13.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_13.webp') },
  { slug: 'chlebek_bananowy', category: 'kuchnia_polska', labelPl: 'Chlebek bananowy z orzechami', aliases: ['chlebek bananowy', 'banana bread'], storagePath: 'dania/cakes/cake_14.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_14.webp') },
  { slug: 'mille_feuille', category: 'kuchnia_polska', labelPl: 'Mille-feuille (Napoleonka)', aliases: ['mille-feuille', 'napoleonka', 'napoleon'], storagePath: 'dania/cakes/cake_15.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_15.webp') },
  { slug: 'makowiec_klasyczny', category: 'kuchnia_polska', labelPl: 'Makowiec klasyczny', aliases: ['makowiec', 'strucla makowa', 'poppy seed roll'], storagePath: 'dania/cakes/cake_16.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_16.webp') },
  { slug: 'babka_marmurkowa', category: 'kuchnia_polska', labelPl: 'Babka piaskowa dwukolorowa', aliases: ['babka marmurkowa', 'babka piaskowa', 'marble cake'], storagePath: 'dania/cakes/cake_17.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_17.webp') },
  { slug: 'tarta_pekan', category: 'kuchnia_polska', labelPl: 'Tarta z orzechami pekan', aliases: ['pecan pie', 'tarta pekan', 'orzechy pekan'], storagePath: 'dania/cakes/cake_18.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_18.webp') },
  { slug: 'key_lime_pie', category: 'kuchnia_polska', labelPl: 'Tarta limonkowa (Key Lime Pie)', aliases: ['key lime', 'tarta limonkowa', 'lime pie'], storagePath: 'dania/cakes/cake_19.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_19.webp') },
  { slug: 'tort_opera', category: 'kuchnia_polska', labelPl: 'Tort Opera', aliases: ['tort opera', 'opera cake'], storagePath: 'dania/cakes/cake_20.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_20.webp') },
  { slug: 'babka_drozdzowa_mini', category: 'kuchnia_polska', labelPl: 'Babka drożdżowa z polewą czekoladową', aliases: ['babka drożdżowa', 'mini babka', 'bundt'], storagePath: 'dania/cakes/cake_21.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_21.webp') },
  { slug: 'ciasto_jagodowe_kruszonka', category: 'kuchnia_polska', labelPl: 'Ciasto drożdżowe z jagodami', aliases: ['ciasto z jagodami', 'blueberry crumble cake'], storagePath: 'dania/cakes/cake_22.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_22.webp') },
  { slug: 'sachertorte', category: 'kuchnia_polska', labelPl: 'Tort Sachera', aliases: ['sacher', 'sachertorte', 'tort sachera'], storagePath: 'dania/cakes/cake_23.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_23.webp') },
  { slug: 'ciasto_borowki_kruszonka', category: 'kuchnia_polska', labelPl: 'Ciasto z borówkami i kruszonką', aliases: ['ciasto z borówkami', 'blueberry cake'], storagePath: 'dania/cakes/cake_24.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_24.webp') },
  { slug: 'tort_truskawkowy', category: 'kuchnia_polska', labelPl: 'Tort truskawkowy', aliases: ['tort truskawkowy', 'strawberry cake'], storagePath: 'dania/cakes/cake_25.webp', localAsset: require('@/assets/premium/dishes/cakes/cake_25.webp') },
];

export const DESSERTS_CUPS_CATALOG: DishImageEntry[] = [
  { slug: 'panna_cotta_maliny', category: 'kuchnia_polska', labelPl: 'Panna Cotta z malinowym coulis', aliases: ['panna cotta', 'panna cotta maliny'], storagePath: 'dania/desserts_cups/dessert_cup_01.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_01.webp') },
  { slug: 'creme_brulee', category: 'kuchnia_polska', labelPl: 'Crème brûlée', aliases: ['creme brulee', 'crème brûlée', 'krem brulee'], storagePath: 'dania/desserts_cups/dessert_cup_02.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_02.webp') },
  { slug: 'fondant_czekoladowy', category: 'kuchnia_polska', labelPl: 'Fondant czekoladowy', aliases: ['fondant', 'fondant czekoladowy', 'chocolate fondant'], storagePath: 'dania/desserts_cups/dessert_cup_03.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_03.webp') },
  { slug: 'mus_mango', category: 'kuchnia_polska', labelPl: 'Mus mango', aliases: ['mus mango', 'mango mousse'], storagePath: 'dania/desserts_cups/dessert_cup_04.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_04.webp') },
  { slug: 'tiramisu_szklo', category: 'kuchnia_polska', labelPl: 'Tiramisu w szkle', aliases: ['tiramisu w szkle', 'tiramisu pucharek'], storagePath: 'dania/desserts_cups/dessert_cup_05.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_05.webp') },
  { slug: 'lava_cake', category: 'kuchnia_polska', labelPl: 'Lava cake', aliases: ['lava cake', 'ciasto lava', 'molten cake'], storagePath: 'dania/desserts_cups/dessert_cup_06.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_06.webp') },
  { slug: 'pudding_chia_kokos', category: 'kuchnia_polska', labelPl: 'Pudding chia na mleku kokosowym', aliases: ['chia kokos', 'pudding chia kokos'], storagePath: 'dania/desserts_cups/dessert_cup_07.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_07.webp') },
  { slug: 'mus_potrojnie_czekoladowy', category: 'kuchnia_polska', labelPl: 'Mus potrójnie czekoladowy', aliases: ['mus czekoladowy', 'triple chocolate', 'verrine'], storagePath: 'dania/desserts_cups/dessert_cup_08.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_08.webp') },
  { slug: 'sernik_truskawkowy_sloik', category: 'kuchnia_polska', labelPl: 'Sernik truskawkowy w słoiczku', aliases: ['sernik w słoiczku', 'strawberry cheesecake jar'], storagePath: 'dania/desserts_cups/dessert_cup_09.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_09.webp') },
  { slug: 'parfait_cytrynowe', category: 'kuchnia_polska', labelPl: 'Parfait cytrynowe z bezą', aliases: ['parfait cytrynowe', 'lemon curd parfait'], storagePath: 'dania/desserts_cups/dessert_cup_10.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_10.webp') },
  { slug: 'banoffee', category: 'kuchnia_polska', labelPl: 'Deser Banoffee', aliases: ['banoffee', 'deser banoffee'], storagePath: 'dania/desserts_cups/dessert_cup_11.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_11.webp') },
  { slug: 'trifle_lesne', category: 'kuchnia_polska', labelPl: 'Trifle z owocami leśnymi', aliases: ['trifle', 'brytyjski trifle'], storagePath: 'dania/desserts_cups/dessert_cup_12.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_12.webp') },
  { slug: 'galaretka_owoce', category: 'kuchnia_polska', labelPl: 'Galaretka z owocami leśnymi', aliases: ['galaretka', 'galaretka z owocami'], storagePath: 'dania/desserts_cups/dessert_cup_13.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_13.webp') },
  { slug: 'mus_matcha', category: 'kuchnia_polska', labelPl: 'Mus z zielonej herbaty Matcha', aliases: ['mus matcha', 'matcha mousse'], storagePath: 'dania/desserts_cups/dessert_cup_14.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_14.webp') },
  { slug: 'espresso_panna_cotta', category: 'kuchnia_polska', labelPl: 'Espresso Panna Cotta', aliases: ['espresso panna cotta', 'kawowa panna cotta'], storagePath: 'dania/desserts_cups/dessert_cup_15.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_15.webp') },
  { slug: 'kopula_marakuja', category: 'kuchnia_polska', labelPl: 'Kopuła z białej czekolady i marakui', aliases: ['kopuła marakuja', 'passion fruit dome'], storagePath: 'dania/desserts_cups/dessert_cup_16.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_16.webp') },
  { slug: 'apple_crumble', category: 'kuchnia_polska', labelPl: 'Apple Crumble', aliases: ['apple crumble', 'jabłka pod kruszonką', 'crumble'], storagePath: 'dania/desserts_cups/dessert_cup_17.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_17.webp') },
  { slug: 'suflet_czekoladowy', category: 'kuchnia_polska', labelPl: 'Suflet czekoladowy', aliases: ['suflet', 'suflet czekoladowy', 'chocolate souffle'], storagePath: 'dania/desserts_cups/dessert_cup_18.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_18.webp') },
  { slug: 'panna_cotta_pistacja', category: 'kuchnia_polska', labelPl: 'Pistacjowa Panna Cotta', aliases: ['panna cotta pistacja', 'pistachio panna cotta'], storagePath: 'dania/desserts_cups/dessert_cup_19.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_19.webp') },
  { slug: 'parfait_jagodowy', category: 'kuchnia_polska', labelPl: 'Parfait z jogurtem jagodowym', aliases: ['parfait jagodowy', 'blueberry parfait'], storagePath: 'dania/desserts_cups/dessert_cup_20.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_20.webp') },
  { slug: 'profiteroles', category: 'kuchnia_polska', labelPl: 'Profiteroles z sosem czekoladowym', aliases: ['profiteroles', 'ptysie', 'ptysie z kremem'], storagePath: 'dania/desserts_cups/dessert_cup_21.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_21.webp') },
  { slug: 'mini_tarte_tatin', category: 'kuchnia_polska', labelPl: 'Mini Tarte Tatin', aliases: ['tarte tatin', 'mini tatin'], storagePath: 'dania/desserts_cups/dessert_cup_22.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_22.webp') },
  { slug: 'pot_de_creme', category: 'kuchnia_polska', labelPl: 'Pot de Crème czekoladowy', aliases: ['pot de creme', 'pot de crème', 'krem czekoladowy'], storagePath: 'dania/desserts_cups/dessert_cup_23.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_23.webp') },
  { slug: 'mus_maliny_biala_czekolada', category: 'kuchnia_polska', labelPl: 'Mus z malin i białej czekolady', aliases: ['mus maliny', 'raspberry white chocolate'], storagePath: 'dania/desserts_cups/dessert_cup_24.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_24.webp') },
  { slug: 'panna_cotta_kokos_mango', category: 'kuchnia_polska', labelPl: 'Kokosowa Panna Cotta z mango', aliases: ['panna cotta kokos', 'coconut mango panna cotta'], storagePath: 'dania/desserts_cups/dessert_cup_25.webp', localAsset: require('@/assets/premium/dishes/desserts_cups/dessert_cup_25.webp') },
];
