/**
 * Katalog grafik — catering / bankiet (plansza 5×5, rządami L→P).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const CATERING_CATALOG: DishImageEntry[] = [
  { slug: 'koryto_biesiadne', category: 'kuchnia_polska', labelPl: 'Koryto biesiadne', aliases: ['koryto biesiadne', 'półmisek mięs', 'golonka kiełbaski'], storagePath: 'dania/catering/catering_01.webp', localAsset: require('@/assets/premium/dishes/catering/catering_01.webp') },
  { slug: 'box_kanapki_bankietowe', category: 'kuchnia_polska', labelPl: 'Catering box z kanapkami bankietowymi', aliases: ['kanapki bankietowe', 'mini kanapki', 'finger sandwiches'], storagePath: 'dania/catering/catering_02.webp', localAsset: require('@/assets/premium/dishes/catering/catering_02.webp') },
  { slug: 'szaszlyki_finger_food', category: 'kuchnia_polska', labelPl: 'Półmisek szaszłyków finger-food', aliases: ['finger food', 'szaszłyki koktajlowe', 'koreczki'], storagePath: 'dania/catering/catering_03.webp', localAsset: require('@/assets/premium/dishes/catering/catering_03.webp') },
  { slug: 'mini_burgery_sliders', category: 'kuchnia_polska', labelPl: 'Zestaw mini-burgerów (Sliders)', aliases: ['sliders', 'mini burgery', 'mini-burgery'], storagePath: 'dania/catering/catering_04.webp', localAsset: require('@/assets/premium/dishes/catering/catering_04.webp') },
  { slug: 'rolls_tortilla', category: 'kuchnia_polska', labelPl: 'Rollsy z tortilli', aliases: ['tortilla rolls', 'wrapy krążki', 'pinwheels'], storagePath: 'dania/catering/catering_05.webp', localAsset: require('@/assets/premium/dishes/catering/catering_05.webp') },
  { slug: 'sushi_catering_party', category: 'kuchnia_polska', labelPl: 'Zestaw sushi catering (Party set)', aliases: ['sushi catering', 'party sushi', 'sushi set'], storagePath: 'dania/catering/catering_06.webp', localAsset: require('@/assets/premium/dishes/catering/catering_06.webp') },
  { slug: 'polmisek_miesa_grill', category: 'kuchnia_polska', labelPl: 'Półmisek mięs z grilla', aliases: ['mięsa z grilla', 'szaszłyki drobiowe', 'skrzydełka catering'], storagePath: 'dania/catering/catering_07.webp', localAsset: require('@/assets/premium/dishes/catering/catering_07.webp') },
  { slug: 'box_slodkie_miniporcje', category: 'kuchnia_polska', labelPl: 'Pudełko ze słodkimi miniporcjami', aliases: ['mini desery', 'mini tarty', 'catering słodki'], storagePath: 'dania/catering/catering_08.webp', localAsset: require('@/assets/premium/dishes/catering/catering_08.webp') },
  { slug: 'patera_owocow', category: 'kuchnia_polska', labelPl: 'Patera świeżych owoców', aliases: ['patera owoców', 'fruit platter', 'owoce catering'], storagePath: 'dania/catering/catering_09.webp', localAsset: require('@/assets/premium/dishes/catering/catering_09.webp') },
  { slug: 'deska_serow_wedlin', category: 'kuchnia_polska', labelPl: 'Deska serów i wędlin premium', aliases: ['cheese board', 'deska serów', 'charcuterie'], storagePath: 'dania/catering/catering_10.webp', localAsset: require('@/assets/premium/dishes/catering/catering_10.webp') },
  { slug: 'zimne_plyty', category: 'kuchnia_polska', labelPl: 'Półmisek tradycyjnych zimnych płyt', aliases: ['zimne płyty', 'wędliny bankietowe', 'cold cuts'], storagePath: 'dania/catering/catering_11.webp', localAsset: require('@/assets/premium/dishes/catering/catering_11.webp') },
  { slug: 'mini_tarty_quiche', category: 'kuchnia_polska', labelPl: 'Taca z mini-tartami i quiche', aliases: ['mini quiche', 'tartaletki', 'mini tarty wytrawne'], storagePath: 'dania/catering/catering_12.webp', localAsset: require('@/assets/premium/dishes/catering/catering_12.webp') },
  { slug: 'box_tenders', category: 'kuchnia_polska', labelPl: 'Box z chrupiącymi polędwiczkami (Tenders)', aliases: ['chicken tenders', 'stripsy', 'polędwiczki panierowane'], storagePath: 'dania/catering/catering_13.webp', localAsset: require('@/assets/premium/dishes/catering/catering_13.webp') },
  { slug: 'seafood_bar', category: 'kuchnia_polska', labelPl: 'Półmisek owoców morza (Seafood Bar)', aliases: ['seafood bar', 'ostrygi', 'owoce morza catering'], storagePath: 'dania/catering/catering_14.webp', localAsset: require('@/assets/premium/dishes/catering/catering_14.webp') },
  { slug: 'vol_au_vent', category: 'kuchnia_polska', labelPl: 'Babeczki vol-au-vent', aliases: ['vol-au-vent', 'vol au vent', 'babeczki francuskie'], storagePath: 'dania/catering/catering_15.webp', localAsset: require('@/assets/premium/dishes/catering/catering_15.webp') },
  { slug: 'mini_hot_dogi', category: 'kuchnia_polska', labelPl: 'Taca imprezowych mini hot-dogów', aliases: ['mini hot dog', 'mini hot-dogi', 'party hot dogs'], storagePath: 'dania/catering/catering_16.webp', localAsset: require('@/assets/premium/dishes/catering/catering_16.webp') },
  { slug: 'koreczki_caprese', category: 'kuchnia_polska', labelPl: 'Koreczki Caprese', aliases: ['caprese', 'koreczki caprese', 'mozzarella pomidor'], storagePath: 'dania/catering/catering_17.webp', localAsset: require('@/assets/premium/dishes/catering/catering_17.webp') },
  { slug: 'box_makaroniki_praliny', category: 'kuchnia_polska', labelPl: 'Catering box z makaronikami i pralinami', aliases: ['makaroniki', 'macarons', 'praliny catering'], storagePath: 'dania/catering/catering_18.webp', localAsset: require('@/assets/premium/dishes/catering/catering_18.webp') },
  { slug: 'mezze_bliskowschodnie', category: 'kuchnia_polska', labelPl: 'Półmisek Mezze', aliases: ['mezze', 'hummus catering', 'falafel pita'], storagePath: 'dania/catering/catering_19.webp', localAsset: require('@/assets/premium/dishes/catering/catering_19.webp') },
  { slug: 'taca_pierogi', category: 'kuchnia_polska', labelPl: 'Taca z tradycyjnymi polskimi pierogami', aliases: ['pierogi catering', 'pierogi bankietowe', 'pierogi z cebulką'], storagePath: 'dania/catering/catering_20.webp', localAsset: require('@/assets/premium/dishes/catering/catering_20.webp') },
  { slug: 'bruschetta_miks', category: 'kuchnia_polska', labelPl: 'Miks chrupiących bruschett', aliases: ['bruschetta', 'grzanki bankietowe'], storagePath: 'dania/catering/catering_21.webp', localAsset: require('@/assets/premium/dishes/catering/catering_21.webp') },
  { slug: 'mini_tacos', category: 'kuchnia_polska', labelPl: 'Zestaw imprezowy mini-tacos', aliases: ['mini tacos', 'party tacos'], storagePath: 'dania/catering/catering_22.webp', localAsset: require('@/assets/premium/dishes/catering/catering_22.webp') },
  { slug: 'salatki_w_kubeczkach', category: 'kuchnia_polska', labelPl: 'Sałatki w kubeczkach', aliases: ['sałatki kubeczki', 'mini sałatki', 'salad cups'], storagePath: 'dania/catering/catering_23.webp', localAsset: require('@/assets/premium/dishes/catering/catering_23.webp') },
  { slug: 'crudites_warzywa', category: 'kuchnia_polska', labelPl: 'Talerz chrupiących warzyw (Crudités)', aliases: ['crudités', 'crudites', 'warzywa z hummusem'], storagePath: 'dania/catering/catering_24.webp', localAsset: require('@/assets/premium/dishes/catering/catering_24.webp') },
  { slug: 'pieczone_warzywa_koryto', category: 'kuchnia_polska', labelPl: 'Koryto z pieczonymi warzywami', aliases: ['pieczone warzywa', 'roasted vegetables', 'warzywa zioła'], storagePath: 'dania/catering/catering_25.webp', localAsset: require('@/assets/premium/dishes/catering/catering_25.webp') },
];
