/**
 * Katalog grafik dań — pierogi/kluski, pizze, makarony (plansze 5×5, lokalne WebP).
 */
type DishImageEntry = {
  slug: string;
  category: 'kuchnia_polska';
  labelPl: string;
  aliases: string[];
  storagePath: string;
  localAsset: number;
};

export const DUMPLINGS_CATALOG: DishImageEntry[] = [
  { slug: 'pierogi_ruskie', category: 'kuchnia_polska', labelPl: 'Pierogi ruskie', aliases: ['pierogi ruskie', 'ruskie'], storagePath: 'dania/dumplings/dumpling_01.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_01.webp') },
  { slug: 'pierogi_z_miesem', category: 'kuchnia_polska', labelPl: 'Pierogi z mięsem', aliases: ['pierogi z mięsem', 'pierogi miesne', 'pierogi mięsne'], storagePath: 'dania/dumplings/dumpling_02.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_02.webp') },
  { slug: 'pierogi_z_jagodami', category: 'kuchnia_polska', labelPl: 'Pierogi z jagodami', aliases: ['pierogi z jagodami', 'jagodowe'], storagePath: 'dania/dumplings/dumpling_03.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_03.webp') },
  { slug: 'pierogi_z_truskawkami', category: 'kuchnia_polska', labelPl: 'Pierogi z truskawkami', aliases: ['pierogi z truskawkami', 'truskawkowe'], storagePath: 'dania/dumplings/dumpling_04.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_04.webp') },
  { slug: 'pierogi_kapusta_grzyby', category: 'kuchnia_polska', labelPl: 'Pierogi z kapustą i grzybami', aliases: ['pierogi z kapustą', 'pierogi kapusta grzyby'], storagePath: 'dania/dumplings/dumpling_05.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_05.webp') },
  { slug: 'kopytka', category: 'kuchnia_polska', labelPl: 'Kopytka tradycyjne', aliases: ['kopytka', 'kopytka tradycyjne'], storagePath: 'dania/dumplings/dumpling_06.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_06.webp') },
  { slug: 'kluski_slaskie', category: 'kuchnia_polska', labelPl: 'Kluski śląskie', aliases: ['kluski śląskie', 'kluski slaskie'], storagePath: 'dania/dumplings/dumpling_07.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_07.webp') },
  { slug: 'placki_ziemniaczane_dump', category: 'kuchnia_polska', labelPl: 'Placki ziemniaczane', aliases: ['placki ziemniaczane', 'placuszki ziemniaczane'], storagePath: 'dania/dumplings/dumpling_08.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_08.webp') },
  { slug: 'nalesniki_slodkie', category: 'kuchnia_polska', labelPl: 'Naleśniki na słodko', aliases: ['naleśniki na słodko', 'nalesniki slodkie', 'naleśniki z twarogiem'], storagePath: 'dania/dumplings/dumpling_09.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_09.webp') },
  { slug: 'nalesniki_wytrawne', category: 'kuchnia_polska', labelPl: 'Naleśniki wytrawne', aliases: ['naleśniki wytrawne', 'nalesniki szpinak feta'], storagePath: 'dania/dumplings/dumpling_10.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_10.webp') },
  { slug: 'knedle_sliwki', category: 'kuchnia_polska', labelPl: 'Knedle ze śliwkami', aliases: ['knedle', 'knedle ze śliwkami', 'knedle ze sliwkami'], storagePath: 'dania/dumplings/dumpling_11.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_11.webp') },
  { slug: 'pampuchy', category: 'kuchnia_polska', labelPl: 'Pampuchy / Kluski na parze', aliases: ['pampuchy', 'kluski na parze', 'pyzy na parze'], storagePath: 'dania/dumplings/dumpling_12.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_12.webp') },
  { slug: 'racuchy_jablka', category: 'kuchnia_polska', labelPl: 'Racuchy z jabłkami', aliases: ['racuchy', 'racuchy z jabłkami'], storagePath: 'dania/dumplings/dumpling_13.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_13.webp') },
  { slug: 'kluski_leniwe', category: 'kuchnia_polska', labelPl: 'Kluski leniwe', aliases: ['kluski leniwe', 'leniwe'], storagePath: 'dania/dumplings/dumpling_14.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_14.webp') },
  { slug: 'baba_ziemniaczana', category: 'kuchnia_polska', labelPl: 'Baba ziemniaczana', aliases: ['baba ziemniaczana', 'babka ziemniaczana'], storagePath: 'dania/dumplings/dumpling_15.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_15.webp') },
  { slug: 'kartacze_cepeliny', category: 'kuchnia_polska', labelPl: 'Kartacze / Cepeliny', aliases: ['kartacze', 'cepeliny'], storagePath: 'dania/dumplings/dumpling_16.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_16.webp') },
  { slug: 'pierogi_ziemniaczane', category: 'kuchnia_polska', labelPl: 'Pierogi z farszem ziemniaczanym', aliases: ['pierogi ziemniaczane', 'pierogi z ziemniakami'], storagePath: 'dania/dumplings/dumpling_17.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_17.webp') },
  { slug: 'pierogi_wisnie', category: 'kuchnia_polska', labelPl: 'Pierogi z wiśniami', aliases: ['pierogi z wiśniami', 'pierogi wisnie'], storagePath: 'dania/dumplings/dumpling_18.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_18.webp') },
  { slug: 'pierogi_dzikie_grzyby', category: 'kuchnia_polska', labelPl: 'Pierogi z dzikimi grzybami', aliases: ['pierogi z grzybami', 'pierogi dzikie grzyby'], storagePath: 'dania/dumplings/dumpling_19.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_19.webp') },
  { slug: 'pierogi_pieczone', category: 'kuchnia_polska', labelPl: 'Pierogi pieczone', aliases: ['pierogi pieczone'], storagePath: 'dania/dumplings/dumpling_20.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_20.webp') },
  { slug: 'pierogi_bialy_ser', category: 'kuchnia_polska', labelPl: 'Pierogi z białym serem', aliases: ['pierogi z serem', 'pierogi z białym serem', 'pierogi na słodko'], storagePath: 'dania/dumplings/dumpling_21.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_21.webp') },
  { slug: 'pierogi_podsmażane', category: 'kuchnia_polska', labelPl: 'Pierogi podsmażane', aliases: ['pierogi podsmażane', 'pierogi smażone'], storagePath: 'dania/dumplings/dumpling_22.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_22.webp') },
  { slug: 'mini_kopytka', category: 'kuchnia_polska', labelPl: 'Mini kopytka ziołowe', aliases: ['mini kopytka', 'kopytka ziołowe'], storagePath: 'dania/dumplings/dumpling_23.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_23.webp') },
  { slug: 'nalesniki_dzem', category: 'kuchnia_polska', labelPl: 'Naleśniki z dżemem', aliases: ['naleśniki z dżemem', 'nalesniki z dżemem'], storagePath: 'dania/dumplings/dumpling_24.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_24.webp') },
  { slug: 'male_kluski_ziemniaczane', category: 'kuchnia_polska', labelPl: 'Małe kluski ziemniaczane', aliases: ['małe kluski', 'kluski ziemniaczane', 'kluski w sosie'], storagePath: 'dania/dumplings/dumpling_25.webp', localAsset: require('@/assets/premium/dishes/dumplings/dumpling_25.webp') },
];

export const PIZZAS_CATALOG: DishImageEntry[] = [
  { slug: 'pizza_margherita', category: 'kuchnia_polska', labelPl: 'Pizza Margherita', aliases: ['margherita', 'pizza margherita'], storagePath: 'dania/pizzas/pizza_01.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_01.webp') },
  { slug: 'pizza_pepperoni', category: 'kuchnia_polska', labelPl: 'Pizza Pepperoni', aliases: ['pepperoni', 'pizza pepperoni'], storagePath: 'dania/pizzas/pizza_02.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_02.webp') },
  { slug: 'pizza_parma', category: 'kuchnia_polska', labelPl: 'Pizza Parma', aliases: ['pizza parma', 'prosciutto', 'pizza z szynką dojrzewającą'], storagePath: 'dania/pizzas/pizza_03.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_03.webp') },
  { slug: 'pizza_quattro_formaggi', category: 'kuchnia_polska', labelPl: 'Pizza Quattro Formaggi', aliases: ['quattro formaggi', 'cztery sery', 'pizza cztery sery'], storagePath: 'dania/pizzas/pizza_04.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_04.webp') },
  { slug: 'pizza_bianca', category: 'kuchnia_polska', labelPl: 'Pizza Bianca', aliases: ['pizza bianca', 'biała pizza'], storagePath: 'dania/pizzas/pizza_05.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_05.webp') },
  { slug: 'pizza_calzone', category: 'kuchnia_polska', labelPl: 'Pizza Calzone', aliases: ['calzone', 'pizza calzone'], storagePath: 'dania/pizzas/pizza_06.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_06.webp') },
  { slug: 'pizza_frutti_di_mare', category: 'kuchnia_polska', labelPl: 'Pizza Frutti di Mare', aliases: ['frutti di mare', 'pizza owoce morza'], storagePath: 'dania/pizzas/pizza_07.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_07.webp') },
  { slug: 'pizza_diavola', category: 'kuchnia_polska', labelPl: 'Pizza Diavola', aliases: ['diavola', 'pizza diavola'], storagePath: 'dania/pizzas/pizza_08.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_08.webp') },
  { slug: 'pizza_capricciosa', category: 'kuchnia_polska', labelPl: 'Pizza Capricciosa', aliases: ['capricciosa', 'pizza capricciosa'], storagePath: 'dania/pizzas/pizza_09.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_09.webp') },
  { slug: 'pizza_hawajska', category: 'kuchnia_polska', labelPl: 'Pizza Hawajska', aliases: ['hawajska', 'pizza hawajska', 'hawaii'], storagePath: 'dania/pizzas/pizza_10.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_10.webp') },
  { slug: 'pizza_wege', category: 'kuchnia_polska', labelPl: 'Pizza Wegetariańska', aliases: ['pizza wegetariańska', 'pizza verdure', 'pizza wege'], storagePath: 'dania/pizzas/pizza_11.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_11.webp') },
  { slug: 'pizza_quattro_stagioni', category: 'kuchnia_polska', labelPl: 'Pizza Quattro Stagioni', aliases: ['quattro stagioni', 'cztery pory roku'], storagePath: 'dania/pizzas/pizza_12.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_12.webp') },
  { slug: 'pizza_marinara', category: 'kuchnia_polska', labelPl: 'Pizza Marinara', aliases: ['marinara', 'pizza marinara'], storagePath: 'dania/pizzas/pizza_13.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_13.webp') },
  { slug: 'pizza_funghi', category: 'kuchnia_polska', labelPl: 'Pizza Funghi', aliases: ['funghi', 'pizza funghi', 'pizza z grzybami'], storagePath: 'dania/pizzas/pizza_14.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_14.webp') },
  { slug: 'pizza_tonno', category: 'kuchnia_polska', labelPl: 'Pizza con Tonno e Cipolla', aliases: ['pizza tonno', 'pizza tuńczyk', 'pizza z tuńczykiem'], storagePath: 'dania/pizzas/pizza_15.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_15.webp') },
  { slug: 'pizza_figi_gorgonzola', category: 'kuchnia_polska', labelPl: 'Pizza z figami i gorgonzolą', aliases: ['pizza z figami', 'pizza gorgonzola figi'], storagePath: 'dania/pizzas/pizza_16.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_16.webp') },
  { slug: 'pizza_napoletana', category: 'kuchnia_polska', labelPl: 'Pizza Napoletana', aliases: ['napoletana', 'pizza napoletana', 'pizza anchovis'], storagePath: 'dania/pizzas/pizza_17.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_17.webp') },
  { slug: 'pizza_chicago', category: 'kuchnia_polska', labelPl: 'Pizza Chicago Deep Dish', aliases: ['chicago', 'deep dish', 'pizza chicago'], storagePath: 'dania/pizzas/pizza_18.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_18.webp') },
  { slug: 'pizza_truflowa', category: 'kuchnia_polska', labelPl: 'Pizza z kremem truflowym', aliases: ['pizza truflowa', 'pizza z truflami'], storagePath: 'dania/pizzas/pizza_19.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_19.webp') },
  { slug: 'pizza_carbonara', category: 'kuchnia_polska', labelPl: 'Pizza Carbonara', aliases: ['pizza carbonara'], storagePath: 'dania/pizzas/pizza_20.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_20.webp') },
  { slug: 'pizza_regina', category: 'kuchnia_polska', labelPl: 'Pizza Regina', aliases: ['regina', 'pizza regina'], storagePath: 'dania/pizzas/pizza_21.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_21.webp') },
  { slug: 'pizza_nduja', category: 'kuchnia_polska', labelPl: 'Pizza z nduja i miodem', aliases: ['nduja', 'pizza nduja'], storagePath: 'dania/pizzas/pizza_22.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_22.webp') },
  { slug: 'pizza_kurczak_pesto', category: 'kuchnia_polska', labelPl: 'Pizza z kurczakiem i pesto', aliases: ['pizza pesto', 'pizza z kurczakiem'], storagePath: 'dania/pizzas/pizza_23.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_23.webp') },
  { slug: 'pizzetta', category: 'kuchnia_polska', labelPl: 'Mini Pizzetta', aliases: ['pizzetta', 'mini pizza'], storagePath: 'dania/pizzas/pizza_24.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_24.webp') },
  { slug: 'focaccia_pizza', category: 'kuchnia_polska', labelPl: 'Focaccia', aliases: ['focaccia'], storagePath: 'dania/pizzas/pizza_25.webp', localAsset: require('@/assets/premium/dishes/pizzas/pizza_25.webp') },
];

export const PASTAS_CATALOG: DishImageEntry[] = [
  { slug: 'spaghetti_carbonara', category: 'kuchnia_polska', labelPl: 'Spaghetti Carbonara', aliases: ['carbonara', 'spaghetti carbonara'], storagePath: 'dania/pastas/pasta_01.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_01.webp') },
  { slug: 'spaghetti_bolognese', category: 'kuchnia_polska', labelPl: 'Spaghetti Bolognese', aliases: ['bolognese', 'spaghetti bolognese'], storagePath: 'dania/pastas/pasta_02.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_02.webp') },
  { slug: 'tagliatelle_owoce_morza', category: 'kuchnia_polska', labelPl: 'Tagliatelle z owocami morza', aliases: ['tagliatelle', 'tagliatelle owoce morza'], storagePath: 'dania/pastas/pasta_03.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_03.webp') },
  { slug: 'lasagne_bolognese', category: 'kuchnia_polska', labelPl: 'Lasagne Bolognese', aliases: ['lasagne', 'lasagna', 'lasagne bolognese'], storagePath: 'dania/pastas/pasta_04.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_04.webp') },
  { slug: 'gnocchi_pomidorowe', category: 'kuchnia_polska', labelPl: 'Gnocchi w sosie pomidorowym', aliases: ['gnocchi', 'gnocchi pomidorowe'], storagePath: 'dania/pastas/pasta_05.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_05.webp') },
  { slug: 'ravioli_szpinak', category: 'kuchnia_polska', labelPl: 'Ravioli ze szpinakiem i ricottą', aliases: ['ravioli', 'ravioli szpinak'], storagePath: 'dania/pastas/pasta_06.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_06.webp') },
  { slug: 'penne_arrabbiata', category: 'kuchnia_polska', labelPl: "Penne all'Arrabbiata", aliases: ['arrabbiata', 'penne arrabbiata'], storagePath: 'dania/pastas/pasta_07.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_07.webp') },
  { slug: 'fettuccine_alfredo', category: 'kuchnia_polska', labelPl: 'Fettuccine Alfredo', aliases: ['alfredo', 'fettuccine alfredo'], storagePath: 'dania/pastas/pasta_08.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_08.webp') },
  { slug: 'aglio_olio', category: 'kuchnia_polska', labelPl: 'Spaghetti aglio e olio', aliases: ['aglio e olio', 'aglio olio'], storagePath: 'dania/pastas/pasta_09.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_09.webp') },
  { slug: 'trofie_pesto', category: 'kuchnia_polska', labelPl: 'Makaron Trofie z pesto', aliases: ['trofie', 'trofie pesto'], storagePath: 'dania/pastas/pasta_10.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_10.webp') },
  { slug: 'orecchiette_brokuly', category: 'kuchnia_polska', labelPl: 'Orecchiette z brokułami', aliases: ['orecchiette', 'orecchiette brokuły'], storagePath: 'dania/pastas/pasta_11.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_11.webp') },
  { slug: 'rigatoni_matriciana', category: 'kuchnia_polska', labelPl: 'Rigatoni alla Matriciana', aliases: ['matriciana', 'rigatoni'], storagePath: 'dania/pastas/pasta_12.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_12.webp') },
  { slug: 'fusilli_warzywa', category: 'kuchnia_polska', labelPl: 'Fusilli z pieczonymi warzywami', aliases: ['fusilli', 'świderki'], storagePath: 'dania/pastas/pasta_13.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_13.webp') },
  { slug: 'pappardelle_grzyby', category: 'kuchnia_polska', labelPl: 'Pappardelle z grzybami', aliases: ['pappardelle', 'pappardelle grzyby'], storagePath: 'dania/pastas/pasta_14.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_14.webp') },
  { slug: 'linguine_vongole', category: 'kuchnia_polska', labelPl: 'Linguine alle Vongole', aliases: ['vongole', 'linguine', 'linguine z małżami'], storagePath: 'dania/pastas/pasta_15.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_15.webp') },
  { slug: 'tortellini_bulion', category: 'kuchnia_polska', labelPl: 'Tortellini w bulionie', aliases: ['tortellini', 'tortellini w bulionie'], storagePath: 'dania/pastas/pasta_16.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_16.webp') },
  { slug: 'farfalle_losos', category: 'kuchnia_polska', labelPl: 'Farfalle z łososiem', aliases: ['farfalle', 'kokardki', 'farfalle łosoś'], storagePath: 'dania/pastas/pasta_17.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_17.webp') },
  { slug: 'cacio_e_pepe', category: 'kuchnia_polska', labelPl: 'Spaghetti Cacio e Pepe', aliases: ['cacio e pepe', 'cacio pepe'], storagePath: 'dania/pastas/pasta_18.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_18.webp') },
  { slug: 'baked_ziti', category: 'kuchnia_polska', labelPl: 'Zapiekanka makaronowa', aliases: ['baked ziti', 'zapiekanka makaronowa'], storagePath: 'dania/pastas/pasta_19.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_19.webp') },
  { slug: 'cannelloni', category: 'kuchnia_polska', labelPl: 'Cannelloni faszerowane', aliases: ['cannelloni'], storagePath: 'dania/pastas/pasta_20.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_20.webp') },
  { slug: 'spaghetti_pomodoro', category: 'kuchnia_polska', labelPl: 'Spaghetti al Pomodoro', aliases: ['pomodoro', 'spaghetti pomodoro'], storagePath: 'dania/pastas/pasta_21.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_21.webp') },
  { slug: 'bucatini_orzechowe', category: 'kuchnia_polska', labelPl: 'Bucatini w sosie orzechowym', aliases: ['bucatini'], storagePath: 'dania/pastas/pasta_22.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_22.webp') },
  { slug: 'gnocchi_gorgonzola', category: 'kuchnia_polska', labelPl: 'Gnocchi w sosie gorgonzola', aliases: ['gnocchi gorgonzola'], storagePath: 'dania/pastas/pasta_23.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_23.webp') },
  { slug: 'squid_ink_pasta', category: 'kuchnia_polska', labelPl: 'Czarny makaron z krewetkami', aliases: ['squid ink', 'czarny makaron', 'makaron z atramentem'], storagePath: 'dania/pastas/pasta_24.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_24.webp') },
  { slug: 'mac_and_cheese_pasta', category: 'kuchnia_polska', labelPl: 'Mac and Cheese', aliases: ['mac and cheese', 'makaron serowy'], storagePath: 'dania/pastas/pasta_25.webp', localAsset: require('@/assets/premium/dishes/pastas/pasta_25.webp') },
];
