/**
 * Katalog grafik — energetyki i napoje (plansza 5×5, rządami L→P).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const ENERGY_DRINKS_CATALOG: DishImageEntry[] = [
  { slug: 'klasyczna_cola_lod', category: 'kuchnia_polska', labelPl: 'Klasyczna Cola z lodem', aliases: ['cola z lodem', 'cola', 'coca cola', 'cola cytryna'], storagePath: 'dania/energy_drinks/energy_01.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_01.webp') },
  { slug: 'napoj_cytrynowo_limonkowy', category: 'kuchnia_polska', labelPl: 'Napój gazowany cytrynowo-limonkowy', aliases: ['sprite', '7up', 'cytryna limonka', 'lemon lime soda'], storagePath: 'dania/energy_drinks/energy_02.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_02.webp') },
  { slug: 'napoj_pomaranczowy', category: 'kuchnia_polska', labelPl: 'Napój gazowany pomarańczowy', aliases: ['fanta', 'orange soda', 'pomarańczowy gazowany'], storagePath: 'dania/energy_drinks/energy_03.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_03.webp') },
  { slug: 'puszka_coli_330', category: 'kuchnia_polska', labelPl: 'Puszka klasycznej Coli 330 ml', aliases: ['puszka coli', 'cola puszka', 'cola 330'], storagePath: 'dania/energy_drinks/energy_04.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_04.webp') },
  { slug: 'energy_drink_czerwony', category: 'kuchnia_polska', labelPl: 'Czerwona puszka napoju energetycznego', aliases: ['energy drink', 'energetyk czerwony', 'red bull', 'energetyk'], storagePath: 'dania/energy_drinks/energy_05.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_05.webp') },
  { slug: 'napoj_izotoniczny_niebieski', category: 'kuchnia_polska', labelPl: 'Niebieski napój izotoniczny', aliases: ['izotonik', 'napój sportowy', 'isotonic', 'powerade', 'gatorade'], storagePath: 'dania/energy_drinks/energy_06.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_06.webp') },
  { slug: 'ginger_ale', category: 'kuchnia_polska', labelPl: 'Ginger Ale', aliases: ['ginger ale', 'piwo imbirowe', 'imbirowy gazowany'], storagePath: 'dania/energy_drinks/energy_07.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_07.webp') },
  { slug: 'root_beer', category: 'kuchnia_polska', labelPl: 'Root Beer', aliases: ['root beer', 'piwo korzenne'], storagePath: 'dania/energy_drinks/energy_08.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_08.webp') },
  { slug: 'rozowa_lemoniada_grejpfrut', category: 'kuchnia_polska', labelPl: 'Różowa lemoniada / napój grejpfrutowy', aliases: ['różowa lemoniada', 'grejpfrutowy', 'pink lemonade'], storagePath: 'dania/energy_drinks/energy_09.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_09.webp') },
  { slug: 'cola_zero_puszka', category: 'kuchnia_polska', labelPl: 'Cola Zero', aliases: ['cola zero', 'coca cola zero', 'cola bez cukru'], storagePath: 'dania/energy_drinks/energy_10.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_10.webp') },
  { slug: 'tonik_premium_butelka', category: 'kuchnia_polska', labelPl: 'Tonik premium w butelce', aliases: ['tonic water', 'tonik', 'schweppes tonic'], storagePath: 'dania/energy_drinks/energy_11.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_11.webp') },
  { slug: 'woda_gazowana_lod', category: 'kuchnia_polska', labelPl: 'Woda gazowana z lodem', aliases: ['woda gazowana', 'sparkling water', 'woda z bąbelkami'], storagePath: 'dania/energy_drinks/energy_12.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_12.webp') },
  { slug: 'energy_drink_zielony_x', category: 'kuchnia_polska', labelPl: 'Zielona puszka energetyka', aliases: ['monster', 'energetyk zielony', 'energy original'], storagePath: 'dania/energy_drinks/energy_13.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_13.webp') },
  { slug: 'cream_soda', category: 'kuchnia_polska', labelPl: 'Cream Soda', aliases: ['cream soda', 'waniliowy gazowany'], storagePath: 'dania/energy_drinks/energy_14.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_14.webp') },
  { slug: 'napoj_winogronowy', category: 'kuchnia_polska', labelPl: 'Fioletowy napój gazowany winogronowy', aliases: ['grape soda', 'napój winogronowy', 'fanta grape'], storagePath: 'dania/energy_drinks/energy_15.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_15.webp') },
  { slug: 'botaniczny_tonik_ogorek', category: 'kuchnia_polska', labelPl: 'Botaniczny tonik z ogórkiem i rozmarynem', aliases: ['botaniczny tonik', 'tonic cucumber', 'tonik ogórek'], storagePath: 'dania/energy_drinks/energy_16.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_16.webp') },
  { slug: 'energy_sugar_free', category: 'kuchnia_polska', labelPl: 'Energetyk bez cukru', aliases: ['energy sugar free', 'energetyk zero', 'sugar free energy'], storagePath: 'dania/energy_drinks/energy_17.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_17.webp') },
  { slug: 'tonik_premium_puszka', category: 'kuchnia_polska', labelPl: 'Puszka toniku premium', aliases: ['tonic can', 'puszka toniku'], storagePath: 'dania/energy_drinks/energy_18.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_18.webp') },
  { slug: 'cola_butelka_szklana', category: 'kuchnia_polska', labelPl: 'Szklana butelka Coli', aliases: ['cola butelka', 'szklana cola', 'cola glass bottle'], storagePath: 'dania/energy_drinks/energy_19.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_19.webp') },
  { slug: 'ginger_beer_butelka', category: 'kuchnia_polska', labelPl: 'Ginger Beer', aliases: ['ginger beer', 'piwo imbirowe butelka'], storagePath: 'dania/energy_drinks/energy_20.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_20.webp') },
  { slug: 'vitamin_water', category: 'kuchnia_polska', labelPl: 'Woda witaminowa', aliases: ['vitamin water', 'woda witaminowa', 'power-c'], storagePath: 'dania/energy_drinks/energy_21.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_21.webp') },
  { slug: 'energy_shot', category: 'kuchnia_polska', labelPl: 'Energy Shot', aliases: ['energy shot', 'shot energetyczny', '5 hour energy'], storagePath: 'dania/energy_drinks/energy_22.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_22.webp') },
  { slug: 'bitter_lemon', category: 'kuchnia_polska', labelPl: 'Bitter Lemon', aliases: ['bitter lemon', 'cytrusowy gazowany'], storagePath: 'dania/energy_drinks/energy_23.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_23.webp') },
  { slug: 'club_soda', category: 'kuchnia_polska', labelPl: 'Club Soda', aliases: ['club soda', 'woda sodowa', 'soda water'], storagePath: 'dania/energy_drinks/energy_24.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_24.webp') },
  { slug: 'slomki_kolorowe', category: 'kuchnia_polska', labelPl: 'Kolorowe słomki papierowe', aliases: ['słomki', 'paper straws', 'słomki papierowe'], storagePath: 'dania/energy_drinks/energy_25.webp', localAsset: require('@/assets/premium/dishes/energy_drinks/energy_25.webp'), recipeEligible: false },
];
