/**
 * Katalog grafik — dania rybne + wege/roślinne (plansze 5×5, WebP).
 */
type DishImageEntry = {
  slug: string;
  category: 'kuchnia_polska';
  labelPl: string;
  aliases: string[];
  storagePath: string;
  localAsset: number;
  recipeEligible?: boolean;
};

export const FISH_CATALOG: DishImageEntry[] = [
  { slug: 'losos_maslo_ziolowe', category: 'kuchnia_polska', labelPl: 'Pieczony filet z łososia z masłem ziołowym', aliases: ['łosoś', 'losos', 'pieczony łosoś', 'salmon', 'filet z łososia', 'masło ziołowe'], storagePath: 'dania/fish/fish_01.webp', localAsset: require('@/assets/premium/dishes/fish/fish_01.webp') },
  { slug: 'dorsz_fish_and_chips', category: 'kuchnia_polska', labelPl: 'Filet z dorsza w cieście piwnym (Fish and Chips)', aliases: ['dorsz', 'fish and chips', 'dorsz w cieście', 'beer battered', 'cieście piwnym'], storagePath: 'dania/fish/fish_02.webp', localAsset: require('@/assets/premium/dishes/fish/fish_02.webp') },
  { slug: 'pstrag_calosc', category: 'kuchnia_polska', labelPl: 'Pieczony pstrąg w całości', aliases: ['pstrąg', 'pstrag', 'pieczony pstrąg', 'trout', 'pstrąg w całości'], storagePath: 'dania/fish/fish_03.webp', localAsset: require('@/assets/premium/dishes/fish/fish_03.webp') },
  { slug: 'fish_and_chips_bar', category: 'kuchnia_polska', labelPl: 'Fish and Chips (porcja barowa)', aliases: ['fish chips bar', 'frytki z rybą', 'tradycyjne fish and chips'], storagePath: 'dania/fish/fish_04.webp', localAsset: require('@/assets/premium/dishes/fish/fish_04.webp') },
  { slug: 'tunczyk_sezam', category: 'kuchnia_polska', labelPl: 'Stek z tuńczyka w sezamie', aliases: ['tuńczyk', 'tunczyk', 'stek z tuńczyka', 'tuna', 'sesame tuna'], storagePath: 'dania/fish/fish_05.webp', localAsset: require('@/assets/premium/dishes/fish/fish_05.webp') },
  { slug: 'labraks_szparagi', category: 'kuchnia_polska', labelPl: 'Grillowany filet z labraksa', aliases: ['labraks', 'okoń morski', 'sea bass', 'grillowany labraks'], storagePath: 'dania/fish/fish_06.webp', localAsset: require('@/assets/premium/dishes/fish/fish_06.webp') },
  { slug: 'sardynki_smażone', category: 'kuchnia_polska', labelPl: 'Chrupiące smażone sardynki', aliases: ['sardynki', 'smażone sardynki', 'fried sardines'], storagePath: 'dania/fish/fish_07.webp', localAsset: require('@/assets/premium/dishes/fish/fish_07.webp') },
  { slug: 'halibut_pomidorki', category: 'kuchnia_polska', labelPl: 'Pieczony halibut z pomidorkami', aliases: ['halibut', 'pieczony halibut'], storagePath: 'dania/fish/fish_08.webp', localAsset: require('@/assets/premium/dishes/fish/fish_08.webp') },
  { slug: 'miecznik_grill', category: 'kuchnia_polska', labelPl: 'Grillowany stek z miecznika', aliases: ['miecznik', 'swordfish', 'stek z miecznika'], storagePath: 'dania/fish/fish_09.webp', localAsset: require('@/assets/premium/dishes/fish/fish_09.webp') },
  { slug: 'dorsz_pergamin', category: 'kuchnia_polska', labelPl: 'Dorsz pieczony w pergaminie', aliases: ['en papillote', 'dorsz w pergaminie', 'papillote'], storagePath: 'dania/fish/fish_10.webp', localAsset: require('@/assets/premium/dishes/fish/fish_10.webp') },
  { slug: 'zupa_rybna', category: 'kuchnia_polska', labelPl: 'Tradycyjna zupa rybna', aliases: ['zupa rybna', 'fish soup', 'bulion rybny'], storagePath: 'dania/fish/fish_11.webp', localAsset: require('@/assets/premium/dishes/fish/fish_11.webp') },
  { slug: 'kotleciki_rybne', category: 'kuchnia_polska', labelPl: 'Kotleciki rybne', aliases: ['kotleciki rybne', 'pulpety rybne', 'fish cakes'], storagePath: 'dania/fish/fish_12.webp', localAsset: require('@/assets/premium/dishes/fish/fish_12.webp') },
  { slug: 'makrela_grill', category: 'kuchnia_polska', labelPl: 'Grillowana makrela', aliases: ['makrela', 'grillowana makrela', 'mackerel'], storagePath: 'dania/fish/fish_13.webp', localAsset: require('@/assets/premium/dishes/fish/fish_13.webp') },
  { slug: 'sandacz_panierowany', category: 'kuchnia_polska', labelPl: 'Panierowany filet z sandacza', aliases: ['sandacz', 'panierowany sandacz', 'pike perch'], storagePath: 'dania/fish/fish_14.webp', localAsset: require('@/assets/premium/dishes/fish/fish_14.webp') },
  { slug: 'dorada_grill', category: 'kuchnia_polska', labelPl: 'Dorada z grilla w całości', aliases: ['dorada', 'sea bream', 'dorada grill'], storagePath: 'dania/fish/fish_15.webp', localAsset: require('@/assets/premium/dishes/fish/fish_15.webp') },
  { slug: 'tatar_losos', category: 'kuchnia_polska', labelPl: 'Tatar z łososia na awokado', aliases: ['tatar z łososia', 'salmon tartare', 'tatar łosoś'], storagePath: 'dania/fish/fish_16.webp', localAsset: require('@/assets/premium/dishes/fish/fish_16.webp') },
  { slug: 'wedzony_losos', category: 'kuchnia_polska', labelPl: 'Wędzony łosoś z kaparami', aliases: ['wędzony łosoś', 'wedzony losos', 'smoked salmon', 'łosoś wędzony'], storagePath: 'dania/fish/fish_17.webp', localAsset: require('@/assets/premium/dishes/fish/fish_17.webp') },
  { slug: 'paluszki_rybne', category: 'kuchnia_polska', labelPl: 'Paluszki rybne', aliases: ['paluszki rybne', 'fish fingers', 'fish sticks'], storagePath: 'dania/fish/fish_18.webp', localAsset: require('@/assets/premium/dishes/fish/fish_18.webp') },
  { slug: 'taco_rybne', category: 'kuchnia_polska', labelPl: 'Taco z rybą', aliases: ['taco z rybą', 'fish taco', 'taco rybne'], storagePath: 'dania/fish/fish_19.webp', localAsset: require('@/assets/premium/dishes/fish/fish_19.webp') },
  { slug: 'sandacz_pomidorki', category: 'kuchnia_polska', labelPl: 'Pieczony sandacz z pomidorkami', aliases: ['sandacz z pomidorkami', 'pieczony sandacz'], storagePath: 'dania/fish/fish_20.webp', localAsset: require('@/assets/premium/dishes/fish/fish_20.webp') },
  { slug: 'szaszlyki_krewetki_ryba', category: 'kuchnia_polska', labelPl: 'Szaszłyki z krewetek i ryby', aliases: ['szaszłyki rybne', 'szaszłyki krewetki', 'fish shrimp skewers'], storagePath: 'dania/fish/fish_21.webp', localAsset: require('@/assets/premium/dishes/fish/fish_21.webp') },
  { slug: 'sos_tatarski', category: 'kuchnia_polska', labelPl: 'Sos tatarski', aliases: ['sos tatarski', 'tartar sauce', 'tatarski'], storagePath: 'dania/fish/fish_22.webp', localAsset: require('@/assets/premium/dishes/fish/fish_22.webp'), recipeEligible: false },
  { slug: 'sos_sweet_chili', category: 'kuchnia_polska', labelPl: 'Sos sweet chili', aliases: ['sweet chili', 'sos chili', 'słono-pikantny chili'], storagePath: 'dania/fish/fish_23.webp', localAsset: require('@/assets/premium/dishes/fish/fish_23.webp'), recipeEligible: false },
  { slug: 'sos_maslowo_czosnkowy', category: 'kuchnia_polska', labelPl: 'Sos masłowo-czosnkowy', aliases: ['sos masłowo-czosnkowy', 'garlic butter', 'masło czosnkowe'], storagePath: 'dania/fish/fish_24.webp', localAsset: require('@/assets/premium/dishes/fish/fish_24.webp'), recipeEligible: false },
  { slug: 'cytryna_czastki', category: 'kuchnia_polska', labelPl: 'Cząstki cytryny', aliases: ['cytryna', 'lemon wedges', 'cząstki cytryny'], storagePath: 'dania/fish/fish_25.webp', localAsset: require('@/assets/premium/dishes/fish/fish_25.webp'), recipeEligible: false },
];

/** Plansza 49 — dania wege główne */
export const VEGAN_CATALOG: DishImageEntry[] = [
  { slug: 'buddha_bowl_wege', category: 'kuchnia_polska', labelPl: 'Wegański Buddha Bowl', aliases: ['buddha bowl', 'wegański bowl', 'bowls wege', 'wegański buddha bowl'], storagePath: 'dania/vegan/vegan_01.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_01.webp') },
  { slug: 'kotlety_ciecierzyca', category: 'kuchnia_polska', labelPl: 'Kotlety z ciecierzycy (Falafle)', aliases: ['kotlety z ciecierzycy', 'falafel', 'falafle', 'ciecierzyca kotlety'], storagePath: 'dania/vegan/vegan_02.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_02.webp') },
  { slug: 'ratatouille', category: 'kuchnia_polska', labelPl: 'Tradycyjne warzywne Ratatouille', aliases: ['ratatouille', 'ratatuj', 'warzywne ratatouille'], storagePath: 'dania/vegan/vegan_03.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_03.webp') },
  { slug: 'strogonow_grzybowy_wege', category: 'kuchnia_polska', labelPl: 'Wegański strogonow grzybowy', aliases: ['strogonow grzybowy', 'mushroom stroganoff', 'wegański strogonow'], storagePath: 'dania/vegan/vegan_04.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_04.webp') },
  { slug: 'gnocchi_bataty', category: 'kuchnia_polska', labelPl: 'Gnocchi z batatów', aliases: ['gnocchi z batatów', 'sweet potato gnocchi', 'kopytka bataty'], storagePath: 'dania/vegan/vegan_05.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_05.webp') },
  { slug: 'stek_kalafior_chimichurri', category: 'kuchnia_polska', labelPl: 'Stek z kalafiora', aliases: ['stek z kalafiora', 'cauliflower steak', 'chimichurri', 'kalafior grill'], storagePath: 'dania/vegan/vegan_06.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_06.webp') },
  { slug: 'steki_boczniakow', category: 'kuchnia_polska', labelPl: 'Steki z boczniaków', aliases: ['steki z boczniaków', 'oyster mushroom steak', 'boczniaki grill'], storagePath: 'dania/vegan/vegan_07.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_07.webp') },
  { slug: 'golabki_soczewica_wege', category: 'kuchnia_polska', labelPl: 'Wegańskie gołąbki z soczewicą', aliases: ['gołąbki z soczewicą', 'wegańskie gołąbki', 'lentil cabbage rolls'], storagePath: 'dania/vegan/vegan_08.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_08.webp') },
  { slug: 'risotto_dynia_pizmova', category: 'kuchnia_polska', labelPl: 'Kremowe risotto z dynią piżmową', aliases: ['risotto z dynią', 'butternut risotto', 'risotto dyniowe', 'risotto'], storagePath: 'dania/vegan/vegan_09.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_09.webp') },
  { slug: 'pad_thai_tofu', category: 'kuchnia_polska', labelPl: 'Wegański Pad Thai z tofu', aliases: ['pad thai', 'wegański pad thai', 'pad thai tofu'], storagePath: 'dania/vegan/vegan_10.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_10.webp') },
  { slug: 'roladki_baklazan', category: 'kuchnia_polska', labelPl: 'Roladki z bakłażana', aliases: ['roladki z bakłażana', 'eggplant rolls', 'bakłażan ricotta'], storagePath: 'dania/vegan/vegan_11.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_11.webp') },
  { slug: 'dahl_ciecierzyca_szpinak', category: 'kuchnia_polska', labelPl: 'Dahl z ciecierzycy i szpinaku', aliases: ['dahl', 'dal', 'dahl ciecierzyca', 'dahl szpinak'], storagePath: 'dania/vegan/vegan_12.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_12.webp') },
  { slug: 'kalafior_tikka_masala', category: 'kuchnia_polska', labelPl: 'Kalafior Tikka Masala', aliases: ['kalafior tikka', 'cauliflower tikka masala', 'tikka masala wege'], storagePath: 'dania/vegan/vegan_13.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_13.webp') },
  { slug: 'lasagne_cukinia_wege', category: 'kuchnia_polska', labelPl: 'Zapiekanka lasagne z cukinii', aliases: ['lasagne cukinia', 'zucchini lasagna', 'lasagne wege', 'wegańska lasagne'], storagePath: 'dania/vegan/vegan_14.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_14.webp') },
  { slug: 'miska_jackfruit', category: 'kuchnia_polska', labelPl: 'Wegańska miska z szarpanym jackfruitem', aliases: ['jackfruit', 'pulled jackfruit', 'miska jackfruit', 'taco jackfruit'], storagePath: 'dania/vegan/vegan_15.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_15.webp') },
  { slug: 'pieczen_soczewica', category: 'kuchnia_polska', labelPl: 'Pieczeń z soczewicy (Lentil Loaf)', aliases: ['pieczeń z soczewicy', 'lentil loaf', 'pasztet soczewica'], storagePath: 'dania/vegan/vegan_16.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_16.webp') },
  { slug: 'paella_wege_karczochy', category: 'kuchnia_polska', labelPl: 'Wegańska paella z karczochami', aliases: ['paella wege', 'vegan paella', 'paella karczochy'], storagePath: 'dania/vegan/vegan_17.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_17.webp') },
  { slug: 'tofu_katsu_curry', category: 'kuchnia_polska', labelPl: 'Chrupiące Tofu Katsu Curry', aliases: ['tofu katsu', 'katsu curry', 'tofu katsu curry'], storagePath: 'dania/vegan/vegan_18.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_18.webp') },
  { slug: 'portobello_faszerowane', category: 'kuchnia_polska', labelPl: 'Faszerowane grzyby Portobello', aliases: ['portobello', 'faszerowane portobello', 'stuffed portobello', 'stek z portobello'], storagePath: 'dania/vegan/vegan_19.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_19.webp') },
  { slug: 'ciepla_salatka_komosa', category: 'kuchnia_polska', labelPl: 'Ciepła sałatka z komosą i warzywami', aliases: ['ciepła sałatka komosa', 'quinoa warm salad', 'sałatka quinoa warzywa'], storagePath: 'dania/vegan/vegan_20.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_20.webp') },
  { slug: 'wok_tempeh', category: 'kuchnia_polska', labelPl: 'Wok z warzywami i tempehem', aliases: ['wok tempeh', 'stir fry tempeh', 'tempeh warzywa', 'smażony tempeh'], storagePath: 'dania/vegan/vegan_21.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_21.webp') },
  { slug: 'shepherds_pie_wege', category: 'kuchnia_polska', labelPl: "Wegańska zapiekanka pasterska (Shepherd's Pie)", aliases: ["shepherd's pie", 'zapiekanka pasterska', 'shepherds pie wege'], storagePath: 'dania/vegan/vegan_22.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_22.webp') },
  { slug: 'mac_and_cheese_wege', category: 'kuchnia_polska', labelPl: 'Wegański Mac and Cheese', aliases: ['mac and cheese', 'wegański mac', 'mac cheese wege'], storagePath: 'dania/vegan/vegan_23.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_23.webp') },
  { slug: 'frytki_polenta_aioli', category: 'kuchnia_polska', labelPl: 'Frytki z polenty z sosem aioli', aliases: ['frytki z polenty', 'polenta fries', 'polenta aioli'], storagePath: 'dania/vegan/vegan_24.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_24.webp') },
  { slug: 'salsa_mango_awokado', category: 'kuchnia_polska', labelPl: 'Salsa z mango i awokado', aliases: ['salsa mango', 'mango salsa', 'salsa awokado', 'salsa z mango'], storagePath: 'dania/vegan/vegan_25.webp', localAsset: require('@/assets/premium/dishes/vegan/vegan_25.webp'), recipeEligible: false },
];
