/**
 * Katalog grafik — soki, smoothie i milkshake'i (plansza 5×5).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const JUICES_CATALOG: DishImageEntry[] = [
  { slug: 'sok_pomaranczowy_miazsz', category: 'kuchnia_polska', labelPl: 'Świeżo wyciskany sok pomarańczowy z miąższem', aliases: ['sok pomarańczowy', 'orange juice', 'świeży sok'], storagePath: 'dania/juices/juice_01.webp', localAsset: require('@/assets/premium/dishes/juices/juice_01.webp') },
  { slug: 'smoothie_detoks_zielone', category: 'kuchnia_polska', labelPl: 'Zielone smoothie detoks ze szpinakiem i jarmużem', aliases: ['zielone smoothie', 'detoks smoothie', 'green smoothie', 'smoothie szpinak'], storagePath: 'dania/juices/juice_02.webp', localAsset: require('@/assets/premium/dishes/juices/juice_02.webp') },
  { slug: 'milkshake_truskawkowy', category: 'kuchnia_polska', labelPl: 'Koktajl truskawkowy (Milkshake) z bitą śmietaną', aliases: ['milkshake truskawkowy', 'truskawkowy shake', 'strawberry milkshake'], storagePath: 'dania/juices/juice_03.webp', localAsset: require('@/assets/premium/dishes/juices/juice_03.webp') },
  { slug: 'sok_burak_jablko', category: 'kuchnia_polska', labelPl: 'Sok detoks z buraka i jabłka', aliases: ['sok z buraka', 'burak jabłko', 'beet juice'], storagePath: 'dania/juices/juice_04.webp', localAsset: require('@/assets/premium/dishes/juices/juice_04.webp') },
  { slug: 'smoothie_mango_banan', category: 'kuchnia_polska', labelPl: 'Gęste smoothie mango-banan', aliases: ['smoothie mango', 'mango banan', 'mango banana smoothie'], storagePath: 'dania/juices/juice_05.webp', localAsset: require('@/assets/premium/dishes/juices/juice_05.webp') },
  { slug: 'shake_awokado_banan', category: 'kuchnia_polska', labelPl: 'Kremowy shake z awokado i banana', aliases: ['shake awokado', 'awokado banan', 'avocado banana'], storagePath: 'dania/juices/juice_06.webp', localAsset: require('@/assets/premium/dishes/juices/juice_06.webp') },
  { slug: 'sok_marchew_imbir', category: 'kuchnia_polska', labelPl: 'Sok z marchewki i imbiru', aliases: ['sok marchewkowy', 'marchew imbir', 'carrot ginger'], storagePath: 'dania/juices/juice_07.webp', localAsset: require('@/assets/premium/dishes/juices/juice_07.webp') },
  { slug: 'milkshake_czekoladowy', category: 'kuchnia_polska', labelPl: 'Klasyczny shake czekoladowy (Milkshake)', aliases: ['shake czekoladowy', 'chocolate milkshake', 'milkshake czekoladowy'], storagePath: 'dania/juices/juice_08.webp', localAsset: require('@/assets/premium/dishes/juices/juice_08.webp') },
  { slug: 'smoothie_ananas_kokos', category: 'kuchnia_polska', labelPl: 'Tropikalne smoothie ananasowo-kokosowe', aliases: ['smoothie ananas', 'ananas kokos', 'pineapple coconut'], storagePath: 'dania/juices/juice_09.webp', localAsset: require('@/assets/premium/dishes/juices/juice_09.webp') },
  { slug: 'sok_arbuzowy', category: 'kuchnia_polska', labelPl: 'Orzeźwiający sok arbuzowy z miętą', aliases: ['sok arbuzowy', 'watermelon juice', 'arbuz'], storagePath: 'dania/juices/juice_10.webp', localAsset: require('@/assets/premium/dishes/juices/juice_10.webp') },
  { slug: 'smoothie_acai_borowki', category: 'kuchnia_polska', labelPl: 'Energetyczne smoothie jagodowe z acai', aliases: ['smoothie acai', 'smoothie jagodowe', 'acai blueberry'], storagePath: 'dania/juices/juice_11.webp', localAsset: require('@/assets/premium/dishes/juices/juice_11.webp') },
  { slug: 'milkshake_malinowy', category: 'kuchnia_polska', labelPl: 'Malinowo-waniliowy koktajl mleczny', aliases: ['milkshake malinowy', 'malina wanilia', 'raspberry milkshake'], storagePath: 'dania/juices/juice_12.webp', localAsset: require('@/assets/premium/dishes/juices/juice_12.webp') },
  { slug: 'sok_granatowy', category: 'kuchnia_polska', labelPl: 'Antyoksydacyjny sok z granatu', aliases: ['sok z granatu', 'pomegranate juice', 'granat'], storagePath: 'dania/juices/juice_13.webp', localAsset: require('@/assets/premium/dishes/juices/juice_13.webp') },
  { slug: 'sok_kiwi_jablko', category: 'kuchnia_polska', labelPl: 'Zielony sok z kiwi i jabłka', aliases: ['sok kiwi', 'kiwi jabłko', 'kiwi apple juice'], storagePath: 'dania/juices/juice_14.webp', localAsset: require('@/assets/premium/dishes/juices/juice_14.webp') },
  { slug: 'shake_maslo_orzechowe', category: 'kuchnia_polska', labelPl: 'Proteinowy shake z masłem orzechowym i bananem', aliases: ['shake proteinowy', 'masło orzechowe banan', 'peanut butter shake'], storagePath: 'dania/juices/juice_15.webp', localAsset: require('@/assets/premium/dishes/juices/juice_15.webp') },
  { slug: 'sok_seler_ogorek', category: 'kuchnia_polska', labelPl: 'Oczyszczający sok z selera naciowego i ogórka', aliases: ['sok z selera', 'seler ogórek', 'celery cucumber'], storagePath: 'dania/juices/juice_16.webp', localAsset: require('@/assets/premium/dishes/juices/juice_16.webp') },
  { slug: 'sok_odpornosc', category: 'kuchnia_polska', labelPl: 'Sok na odporność (Immunity) — pomarańcza, marchew, imbir', aliases: ['immunity shot', 'sok na odporność', 'immunity juice'], storagePath: 'dania/juices/juice_17.webp', localAsset: require('@/assets/premium/dishes/juices/juice_17.webp') },
  { slug: 'smoothie_owoce_lesne', category: 'kuchnia_polska', labelPl: 'Miks smoothie z owoców leśnych', aliases: ['smoothie owoce leśne', 'mixed berry smoothie', 'owoce leśne'], storagePath: 'dania/juices/juice_18.webp', localAsset: require('@/assets/premium/dishes/juices/juice_18.webp') },
  { slug: 'milkshake_oreo', category: 'kuchnia_polska', labelPl: 'Koktajl Cookies & Cream (Oreo Milkshake)', aliases: ['oreo milkshake', 'cookies and cream', 'milkshake oreo'], storagePath: 'dania/juices/juice_19.webp', localAsset: require('@/assets/premium/dishes/juices/juice_19.webp') },
  { slug: 'sok_grejpfrutowy', category: 'kuchnia_polska', labelPl: 'Świeży sok grejpfrutowy', aliases: ['sok grejpfrutowy', 'grapefruit juice', 'grejpfrut'], storagePath: 'dania/juices/juice_20.webp', localAsset: require('@/assets/premium/dishes/juices/juice_20.webp') },
  { slug: 'smoothie_pumpkin_spice', category: 'kuchnia_polska', labelPl: 'Korzenne smoothie dyniowe (Pumpkin Spice)', aliases: ['pumpkin spice smoothie', 'smoothie dyniowe', 'dynia cynamon'], storagePath: 'dania/juices/juice_21.webp', localAsset: require('@/assets/premium/dishes/juices/juice_21.webp') },
  { slug: 'sok_guawa_marakuja', category: 'kuchnia_polska', labelPl: 'Egzotyczny sok z różowej guawy i marakui', aliases: ['sok guawa', 'guava passion', 'marakuja guawa'], storagePath: 'dania/juices/juice_22.webp', localAsset: require('@/assets/premium/dishes/juices/juice_22.webp') },
  { slug: 'shake_matcha_mieta', category: 'kuchnia_polska', labelPl: 'Proteinowy shake Matcha z miętą', aliases: ['shake matcha', 'matcha mint', 'matcha shake'], storagePath: 'dania/juices/juice_23.webp', localAsset: require('@/assets/premium/dishes/juices/juice_23.webp') },
  { slug: 'milkshake_waniliowy', category: 'kuchnia_polska', labelPl: 'Klasyczny koktajl waniliowy (Milkshake)', aliases: ['milkshake waniliowy', 'vanilla milkshake', 'shake waniliowy'], storagePath: 'dania/juices/juice_24.webp', localAsset: require('@/assets/premium/dishes/juices/juice_24.webp') },
  { slug: 'miks_owocow_dekoracja', category: 'kuchnia_polska', labelPl: 'Miseczka z miksem świeżych owoców', aliases: ['miks owoców', 'fruit bowl', 'owoce dekoracja'], storagePath: 'dania/juices/juice_25.webp', localAsset: require('@/assets/premium/dishes/juices/juice_25.webp'), recipeEligible: false },
];
