/**
 * Katalog grafik — lemoniady i napoje orzeźwiające (plansza 5×5, rządami L→P).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const LEMONADES_CATALOG: DishImageEntry[] = [
  { slug: 'lemoniada_cytrynowa', category: 'kuchnia_polska', labelPl: 'Klasyczna lemoniada cytrynowa', aliases: ['lemoniada cytrynowa', 'lemoniada klasyczna', 'lemonade', 'lemoniada z miętą'], storagePath: 'dania/lemonades/lemonade_01.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_01.webp') },
  { slug: 'lemoniada_ogorkowa_bazylia', category: 'kuchnia_polska', labelPl: 'Lemoniada ogórkowa z bazylią', aliases: ['lemoniada ogórkowa', 'ogórek bazylia', 'cucumber lemonade'], storagePath: 'dania/lemonades/lemonade_02.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_02.webp') },
  { slug: 'lemoniada_arbuzowa', category: 'kuchnia_polska', labelPl: 'Lemoniada arbuzowa z limonką', aliases: ['lemoniada arbuzowa', 'arbuz limonka', 'watermelon lemonade'], storagePath: 'dania/lemonades/lemonade_03.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_03.webp') },
  { slug: 'iced_tea_brzoskwinia_domowa', category: 'kuchnia_polska', labelPl: 'Domowa mrożona herbata brzoskwiniowa', aliases: ['mrożona herbata brzoskwiniowa', 'peach iced tea', 'iced tea brzoskwinia'], storagePath: 'dania/lemonades/lemonade_04.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_04.webp') },
  { slug: 'woda_cytryna_mieta', category: 'kuchnia_polska', labelPl: 'Dzbanek wody z cytryną i miętą', aliases: ['woda z cytryną', 'woda miętowa', 'infused water', 'dzbanek wody'], storagePath: 'dania/lemonades/lemonade_05.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_05.webp') },
  { slug: 'lemoniada_truskawkowa', category: 'kuchnia_polska', labelPl: 'Lemoniada truskawkowa z miętą', aliases: ['lemoniada truskawkowa', 'truskawka mięta', 'strawberry lemonade'], storagePath: 'dania/lemonades/lemonade_06.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_06.webp') },
  { slug: 'lemoniada_marakuja', category: 'kuchnia_polska', labelPl: 'Egzotyczna lemoniada z marakui', aliases: ['lemoniada marakuja', 'passion fruit', 'marakuja'], storagePath: 'dania/lemonades/lemonade_07.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_07.webp') },
  { slug: 'lemoniada_lawendowa', category: 'kuchnia_polska', labelPl: 'Lemoniada lawendowa', aliases: ['lemoniada lawendowa', 'lavender lemonade', 'lawenda napój'], storagePath: 'dania/lemonades/lemonade_08.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_08.webp') },
  { slug: 'ginger_beer', category: 'kuchnia_polska', labelPl: 'Tradycyjne piwo imbirowe (Ginger Beer)', aliases: ['ginger beer', 'piwo imbirowe', 'imbir napój'], storagePath: 'dania/lemonades/lemonade_09.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_09.webp') },
  { slug: 'lemoniada_blue_curacao', category: 'kuchnia_polska', labelPl: 'Lemoniada Blue Curacao', aliases: ['blue curacao', 'niebieska lemoniada', 'blue lemonade'], storagePath: 'dania/lemonades/lemonade_10.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_10.webp') },
  { slug: 'mrozona_zielona_herbata', category: 'kuchnia_polska', labelPl: 'Mrożona zielona herbata z miodem i miętą', aliases: ['mrożona zielona herbata', 'iced green tea', 'zielona iced'], storagePath: 'dania/lemonades/lemonade_11.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_11.webp') },
  { slug: 'elderflower', category: 'kuchnia_polska', labelPl: 'Napój z czarnego bzu (Elderflower)', aliases: ['czarny bez', 'elderflower', 'napój z bzu', 'bez'], storagePath: 'dania/lemonades/lemonade_12.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_12.webp') },
  { slug: 'spritzer_zurawinowy', category: 'kuchnia_polska', labelPl: 'Spritzer żurawinowy z limonką', aliases: ['spritzer żurawinowy', 'żurawina', 'cranberry spritzer'], storagePath: 'dania/lemonades/lemonade_13.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_13.webp') },
  { slug: 'woda_grejpfrut_rozmaryn', category: 'kuchnia_polska', labelPl: 'Woda infuzowana grejpfrutem i rozmarynem', aliases: ['grejpfrut rozmaryn', 'woda grejpfrutowa', 'grapefruit rosemary'], storagePath: 'dania/lemonades/lemonade_14.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_14.webp') },
  { slug: 'chlodnik_kiwi', category: 'kuchnia_polska', labelPl: 'Chłodnik z kiwi i mięty', aliases: ['lemoniada kiwi', 'kiwi mięta', 'kiwi lemonade'], storagePath: 'dania/lemonades/lemonade_15.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_15.webp') },
  { slug: 'ananas_kokos', category: 'kuchnia_polska', labelPl: 'Orzeźwiający napój ananasowo-kokosowy', aliases: ['ananas kokos', 'pineapple coconut', 'napój ananasowy'], storagePath: 'dania/lemonades/lemonade_16.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_16.webp') },
  { slug: 'mango_habanero', category: 'kuchnia_polska', labelPl: 'Pikantna lemoniada mango-habanero', aliases: ['mango habanero', 'lemoniada mango', 'mango chili'], storagePath: 'dania/lemonades/lemonade_17.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_17.webp') },
  { slug: 'mocktail_granatowy', category: 'kuchnia_polska', labelPl: 'Mocktail granatowy z rozmarynem', aliases: ['mocktail granatowy', 'granat rozmaryn', 'pomegranate mocktail'], storagePath: 'dania/lemonades/lemonade_18.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_18.webp') },
  { slug: 'woda_gazowana_lemon_twist', category: 'kuchnia_polska', labelPl: 'Woda gazowana z lemon twist', aliases: ['woda gazowana', 'lemon twist', 'sparkling water', 'soda z cytryną'], storagePath: 'dania/lemonades/lemonade_19.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_19.webp') },
  { slug: 'lemoniada_rabarbarowa', category: 'kuchnia_polska', labelPl: 'Lemoniada rabarbarowo-waniliowa', aliases: ['lemoniada rabarbarowa', 'rabarbar', 'rhubarb lemonade'], storagePath: 'dania/lemonades/lemonade_20.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_20.webp') },
  { slug: 'pomarancza_bazylia', category: 'kuchnia_polska', labelPl: 'Zimny napar pomarańczowo-bazyliowy', aliases: ['pomarańcza bazylia', 'orange basil', 'napar pomarańczowy'], storagePath: 'dania/lemonades/lemonade_21.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_21.webp') },
  { slug: 'lemoniada_wisniowa', category: 'kuchnia_polska', labelPl: 'Lemoniada wiśniowo-limonkowa', aliases: ['lemoniada wiśniowa', 'wiśnia limonka', 'cherry lime'], storagePath: 'dania/lemonades/lemonade_22.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_22.webp') },
  { slug: 'spritzer_borowkowy', category: 'kuchnia_polska', labelPl: 'Spritzer borówkowo-miętowy', aliases: ['spritzer borówkowy', 'borówka mięta', 'blueberry mint'], storagePath: 'dania/lemonades/lemonade_23.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_23.webp') },
  { slug: 'hibiskus_mrozony', category: 'kuchnia_polska', labelPl: 'Mrożony napój z hibiskusa (Karkade)', aliases: ['mrożony hibiskus', 'karkade iced', 'hibiscus iced'], storagePath: 'dania/lemonades/lemonade_24.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_24.webp') },
  { slug: 'kostki_lodu', category: 'kuchnia_polska', labelPl: 'Miseczka z czystymi kostkami lodu', aliases: ['lód', 'kostki lodu', 'ice cubes'], storagePath: 'dania/lemonades/lemonade_25.webp', localAsset: require('@/assets/premium/dishes/lemonades/lemonade_25.webp'), recipeEligible: false },
];
