/**
 * Katalog grafik — kuchnia śródziemnomorska + kaukaska/gruzińska (plansze 5×5, WebP).
 */
type DishImageEntry = {
  slug: string;
  category: 'kuchnia_polska';
  labelPl: string;
  aliases: string[];
  storagePath: string;
  localAsset: number;
  recipeEligible?: boolean;
};

export const MEDITERRANEAN_CATALOG: DishImageEntry[] = [
  { slug: 'paella_owoce_morza', category: 'kuchnia_polska', labelPl: 'Paella z owocami morza', aliases: ['paella', 'paella owoce morza', 'seafood paella'], storagePath: 'dania/mediterranean/mediterranean_01.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_01.webp') },
  { slug: 'gyros_talerz', category: 'kuchnia_polska', labelPl: 'Gyros na talerzu', aliases: ['gyros', 'gyros na talerzu', 'gyro'], storagePath: 'dania/mediterranean/mediterranean_02.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_02.webp') },
  { slug: 'souvlaki_kurczak', category: 'kuchnia_polska', labelPl: 'Souvlaki z kurczaka', aliases: ['souvlaki', 'souvlaki kurczak', 'szaszłyk grecki'], storagePath: 'dania/mediterranean/mediterranean_03.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_03.webp') },
  { slug: 'kalmary_w_ciescie', category: 'kuchnia_polska', labelPl: 'Kalmary w cieście', aliases: ['kalmary', 'calamari', 'kalmary w cieście'], storagePath: 'dania/mediterranean/mediterranean_04.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_04.webp') },
  { slug: 'mule_w_winie', category: 'kuchnia_polska', labelPl: 'Mule w winie', aliases: ['mule', 'małże', 'mule w winie', 'mussels'], storagePath: 'dania/mediterranean/mediterranean_05.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_05.webp') },
  { slug: 'osmiornica_grill', category: 'kuchnia_polska', labelPl: 'Ośmiornica z grilla', aliases: ['ośmiornica', 'osmiornica', 'octopus', 'grillowana ośmiornica'], storagePath: 'dania/mediterranean/mediterranean_06.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_06.webp') },
  { slug: 'musaka', category: 'kuchnia_polska', labelPl: 'Musaka', aliases: ['moussaka', 'musaka', 'musakka'], storagePath: 'dania/mediterranean/mediterranean_07.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_07.webp') },
  { slug: 'pastitsio', category: 'kuchnia_polska', labelPl: 'Pastitsio', aliases: ['pastitsio', 'pastichio'], storagePath: 'dania/mediterranean/mediterranean_08.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_08.webp') },
  { slug: 'spanakopita', category: 'kuchnia_polska', labelPl: 'Spanakopita', aliases: ['spanakopita', 'szpinak filo'], storagePath: 'dania/mediterranean/mediterranean_09.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_09.webp') },
  { slug: 'salatka_grecka', category: 'kuchnia_polska', labelPl: 'Sałatka grecka', aliases: ['sałatka grecka', 'choriatiki', 'greek salad'], storagePath: 'dania/mediterranean/mediterranean_10.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_10.webp') },
  { slug: 'tzatziki', category: 'kuchnia_polska', labelPl: 'Sos Tzatziki', aliases: ['tzatziki', 'sos tzatziki'], storagePath: 'dania/mediterranean/mediterranean_11.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_11.webp') },
  { slug: 'miks_oliwek', category: 'kuchnia_polska', labelPl: 'Miks oliwek', aliases: ['oliwki', 'miks oliwek', 'olives'], storagePath: 'dania/mediterranean/mediterranean_12.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_12.webp') },
  { slug: 'szaszlyki_caprese', category: 'kuchnia_polska', labelPl: 'Szaszłyki Caprese', aliases: ['caprese', 'szaszłyki caprese'], storagePath: 'dania/mediterranean/mediterranean_13.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_13.webp') },
  { slug: 'dolmades', category: 'kuchnia_polska', labelPl: 'Dolmades', aliases: ['dolmades', 'gołąbki winogron', 'sarma'], storagePath: 'dania/mediterranean/mediterranean_14.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_14.webp') },
  { slug: 'halloumi_grill', category: 'kuchnia_polska', labelPl: 'Grillowany halloumi', aliases: ['halloumi', 'grillowany halloumi', 'ser halloumi'], storagePath: 'dania/mediterranean/mediterranean_15.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_15.webp') },
  { slug: 'patatas_bravas', category: 'kuchnia_polska', labelPl: 'Patatas Bravas', aliases: ['patatas bravas', 'bravas'], storagePath: 'dania/mediterranean/mediterranean_16.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_16.webp') },
  { slug: 'gambas_al_ajillo', category: 'kuchnia_polska', labelPl: 'Gambas al Ajillo', aliases: ['gambas', 'gambas al ajillo', 'krewetki czosnek'], storagePath: 'dania/mediterranean/mediterranean_17.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_17.webp') },
  { slug: 'gemista', category: 'kuchnia_polska', labelPl: 'Gemista', aliases: ['gemista', 'faszerowany pomidor'], storagePath: 'dania/mediterranean/mediterranean_18.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_18.webp') },
  { slug: 'sardynki_grill', category: 'kuchnia_polska', labelPl: 'Sardynki z grilla', aliases: ['sardynki', 'sardynki grill', 'grilled sardines'], storagePath: 'dania/mediterranean/mediterranean_19.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_19.webp') },
  { slug: 'hummus_klasyczny', category: 'kuchnia_polska', labelPl: 'Hummus klasyczny', aliases: ['hummus', 'hummus klasyczny'], storagePath: 'dania/mediterranean/mediterranean_20.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_20.webp') },
  { slug: 'tirokafteri', category: 'kuchnia_polska', labelPl: 'Tirokafteri', aliases: ['tirokafteri', 'tyrokafteri'], storagePath: 'dania/mediterranean/mediterranean_21.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_21.webp') },
  { slug: 'falafel_chrupiace', category: 'kuchnia_polska', labelPl: 'Chrupiące falafle', aliases: ['falafel', 'falafle', 'chrupiące falafle'], storagePath: 'dania/mediterranean/mediterranean_22.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_22.webp') },
  { slug: 'chlebki_pita', category: 'kuchnia_polska', labelPl: 'Chlebki pita', aliases: ['pita', 'chlebki pita', 'chlebek pita'], storagePath: 'dania/mediterranean/mediterranean_23.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_23.webp') },
  { slug: 'taramasalata', category: 'kuchnia_polska', labelPl: 'Taramasalata', aliases: ['taramasalata', 'tarama'], storagePath: 'dania/mediterranean/mediterranean_24.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_24.webp') },
  { slug: 'wino_biale_med', category: 'kuchnia_polska', labelPl: 'Kieliszek białego wina', aliases: ['białe wino', 'wino białe', 'white wine'], storagePath: 'dania/mediterranean/mediterranean_25.webp', localAsset: require('@/assets/premium/dishes/mediterranean/mediterranean_25.webp') },
];

/** Plansza 50 — kuchnia gruzińska / kaukaska */
export const CAUCASIAN_CATALOG: DishImageEntry[] = [
  { slug: 'chaczapuri_adzarskie', category: 'kuchnia_polska', labelPl: 'Chaczapuri adżarskie', aliases: ['chaczapuri', 'khachapuri', 'adżarskie', 'adzharskie'], storagePath: 'dania/caucasian/caucasian_01.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_01.webp') },
  { slug: 'chaczapuri_imeretynskie', category: 'kuchnia_polska', labelPl: 'Chaczapuri imeretyńskie', aliases: ['imeretyńskie', 'imeretian khachapuri'], storagePath: 'dania/caucasian/caucasian_02.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_02.webp') },
  { slug: 'chinkali', category: 'kuchnia_polska', labelPl: 'Chinkali', aliases: ['chinkali', 'khinkali', 'pierogi gruzińskie'], storagePath: 'dania/caucasian/caucasian_03.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_03.webp') },
  { slug: 'szaszlyk_kaukaski', category: 'kuchnia_polska', labelPl: 'Szaszłyk kaukaski', aliases: ['szaszłyk kaukaski', 'shashlik', 'szaszłyk'], storagePath: 'dania/caucasian/caucasian_04.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_04.webp') },
  { slug: 'lula_kebab', category: 'kuchnia_polska', labelPl: 'Lula kebab', aliases: ['lula kebab', 'lula', 'lyulya'], storagePath: 'dania/caucasian/caucasian_05.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_05.webp') },
  { slug: 'zupa_charczo', category: 'kuchnia_polska', labelPl: 'Zupa Charczo', aliases: ['charczo', 'kharcho', 'zupa charczo'], storagePath: 'dania/caucasian/caucasian_06.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_06.webp') },
  { slug: 'chashushuli', category: 'kuchnia_polska', labelPl: 'Czaganczuli (Chashushuli)', aliases: ['chashushuli', 'czaganczuli', 'chaganuli'], storagePath: 'dania/caucasian/caucasian_07.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_07.webp') },
  { slug: 'lobio', category: 'kuchnia_polska', labelPl: 'Lobio', aliases: ['lobio', 'fasola gruzińska'], storagePath: 'dania/caucasian/caucasian_08.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_08.webp') },
  { slug: 'pkhali', category: 'kuchnia_polska', labelPl: 'Phali (Pkhali)', aliases: ['pkhali', 'phali', 'pali'], storagePath: 'dania/caucasian/caucasian_09.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_09.webp') },
  { slug: 'badrijani', category: 'kuchnia_polska', labelPl: 'Badridżani (Badrijani Nigvzit)', aliases: ['badrijani', 'badridżani', 'bakłażan orzechowy', 'badrijani nigvzit'], storagePath: 'dania/caucasian/caucasian_10.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_10.webp') },
  { slug: 'szkmeruli', category: 'kuchnia_polska', labelPl: 'Kurczak Szkmeruli (Shkmeruli)', aliases: ['szkmeruli', 'shkmeruli', 'kurczak szkmeruli'], storagePath: 'dania/caucasian/caucasian_11.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_11.webp') },
  { slug: 'szoti', category: 'kuchnia_polska', labelPl: 'Chlebek Szoti (Shotis Puri)', aliases: ['szoti', 'shoti', 'shotis puri'], storagePath: 'dania/caucasian/caucasian_12.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_12.webp') },
  { slug: 'mchadi', category: 'kuchnia_polska', labelPl: 'Mcwadi (Mchadi)', aliases: ['mchadi', 'mcwadi', 'placek kukurydziany'], storagePath: 'dania/caucasian/caucasian_13.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_13.webp') },
  { slug: 'pstrag_pieczony', category: 'kuchnia_polska', labelPl: 'Pstrąg pieczony w całości', aliases: ['pstrąg', 'pstrąg pieczony', 'trout', 'pstrąg w całości'], storagePath: 'dania/caucasian/caucasian_14.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_14.webp') },
  { slug: 'czachochbili', category: 'kuchnia_polska', labelPl: 'Czachochbili (Chakhokhbili)', aliases: ['chakhokhbili', 'czachochbili'], storagePath: 'dania/caucasian/caucasian_15.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_15.webp') },
  { slug: 'adzapsandali', category: 'kuchnia_polska', labelPl: 'Adżapsandali (Ajapsandali)', aliases: ['ajapsandali', 'adżapsandali', 'adzapsandali'], storagePath: 'dania/caucasian/caucasian_16.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_16.webp') },
  { slug: 'kubdari', category: 'kuchnia_polska', labelPl: 'Kubdari', aliases: ['kubdari', 'kubdari placek'], storagePath: 'dania/caucasian/caucasian_17.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_17.webp') },
  { slug: 'satsivi', category: 'kuchnia_polska', labelPl: 'Saciwi (Satsivi)', aliases: ['satsivi', 'saciwi'], storagePath: 'dania/caucasian/caucasian_18.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_18.webp') },
  { slug: 'adzika', category: 'kuchnia_polska', labelPl: 'Adżika (Ajika)', aliases: ['ajika', 'adżika', 'adzika'], storagePath: 'dania/caucasian/caucasian_19.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_19.webp'), recipeEligible: false },
  { slug: 'tkemali', category: 'kuchnia_polska', labelPl: 'Sos Tkemali', aliases: ['tkemali', 'sos tkemali'], storagePath: 'dania/caucasian/caucasian_20.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_20.webp'), recipeEligible: false },
  { slug: 'salatka_gruzinska', category: 'kuchnia_polska', labelPl: 'Sałatka gruzińska', aliases: ['sałatka gruzińska', 'salatka gruzinska'], storagePath: 'dania/caucasian/caucasian_21.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_21.webp') },
  { slug: 'jonjoli', category: 'kuchnia_polska', labelPl: 'Dżondżoli (Jonjoli)', aliases: ['jonjoli', 'dżondżoli', 'dzondzoli'], storagePath: 'dania/caucasian/caucasian_22.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_22.webp') },
  { slug: 'ryz_kaukaski', category: 'kuchnia_polska', labelPl: 'Aromatyczny ryż po kaukasku', aliases: ['ryż kaukaski', 'ryz po kaukasku', 'aromatyczny ryż'], storagePath: 'dania/caucasian/caucasian_23.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_23.webp') },
  { slug: 'churchkhela', category: 'kuchnia_polska', labelPl: 'Czurchczela (Churchkhela)', aliases: ['churchkhela', 'czurchczela', 'churchkela'], storagePath: 'dania/caucasian/caucasian_24.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_24.webp') },
  { slug: 'wino_czerwone_gruz', category: 'kuchnia_polska', labelPl: 'Kieliszek czerwonego wina', aliases: ['wino gruzińskie', 'czerwone wino', 'georgian wine', 'kieliszek czerwonego wina'], storagePath: 'dania/caucasian/caucasian_25.webp', localAsset: require('@/assets/premium/dishes/caucasian/caucasian_25.webp'), recipeEligible: false },
];
