/**
 * Katalog grafik — polskie klasyki (plansza 5×5).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const POLISH_CATALOG: DishImageEntry[] = [
  { slug: 'golabki_tradycyjne', category: 'kuchnia_polska', labelPl: 'Gołąbki tradycyjne', aliases: ['gołąbki', 'gołąbki w sosie pomidorowym'], storagePath: 'dania/polish/polish_01.webp', localAsset: require('@/assets/premium/dishes/polish/polish_01.webp') },
  { slug: 'pyzy_z_miesem', category: 'kuchnia_polska', labelPl: 'Pyzy ziemniaczane z mięsem', aliases: ['pyzy', 'pyzy z mięsem', 'pyzy ziemniaczane'], storagePath: 'dania/polish/polish_02.webp', localAsset: require('@/assets/premium/dishes/polish/polish_02.webp') },
  { slug: 'kluski_slaskie_sos', category: 'kuchnia_polska', labelPl: 'Kluski śląskie z sosem pieczeniowym', aliases: ['kluski śląskie', 'śląskie z sosem'], storagePath: 'dania/polish/polish_03.webp', localAsset: require('@/assets/premium/dishes/polish/polish_03.webp') },
  { slug: 'kopytka_maslo', category: 'kuchnia_polska', labelPl: 'Kopytka tradycyjne z masłem', aliases: ['kopytka', 'kopytka z masłem'], storagePath: 'dania/polish/polish_04.webp', localAsset: require('@/assets/premium/dishes/polish/polish_04.webp') },
  { slug: 'placki_ziemniaczane', category: 'kuchnia_polska', labelPl: 'Placki ziemniaczane chrupiące', aliases: ['placki ziemniaczane', 'placki ze śmietaną'], storagePath: 'dania/polish/polish_05.webp', localAsset: require('@/assets/premium/dishes/polish/polish_05.webp') },
  { slug: 'placek_po_zbojnicku', category: 'kuchnia_polska', labelPl: 'Placek po zbójnicku', aliases: ['placek po zbójnicku', 'placek po węgiersku', 'placek z gulaszem'], storagePath: 'dania/polish/polish_06.webp', localAsset: require('@/assets/premium/dishes/polish/polish_06.webp') },
  { slug: 'kartacze_cepeliny', category: 'kuchnia_polska', labelPl: 'Kartacze / Cepeliny z mięsem', aliases: ['kartacze', 'cepeliny', 'kartacze z mięsem'], storagePath: 'dania/polish/polish_07.webp', localAsset: require('@/assets/premium/dishes/polish/polish_07.webp') },
  { slug: 'knedle_ze_sliwkami', category: 'kuchnia_polska', labelPl: 'Knedle ze śliwkami', aliases: ['knedle', 'knedle ze śliwkami', 'knedle owocowe'], storagePath: 'dania/polish/polish_08.webp', localAsset: require('@/assets/premium/dishes/polish/polish_08.webp') },
  { slug: 'kluski_leniwe', category: 'kuchnia_polska', labelPl: 'Kluski leniwe na słodko', aliases: ['leniwe', 'kluski leniwe', 'leniwe z cynamonem'], storagePath: 'dania/polish/polish_09.webp', localAsset: require('@/assets/premium/dishes/polish/polish_09.webp') },
  { slug: 'pampuchy', category: 'kuchnia_polska', labelPl: 'Pampuchy / Kluski na parze', aliases: ['pampuchy', 'kluski na parze', 'bułki na parze'], storagePath: 'dania/polish/polish_10.webp', localAsset: require('@/assets/premium/dishes/polish/polish_10.webp') },
  { slug: 'baba_ziemniaczana', category: 'kuchnia_polska', labelPl: 'Baba ziemniaczana', aliases: ['baba ziemniaczana', 'zapiekanka ziemniaczana'], storagePath: 'dania/polish/polish_11.webp', localAsset: require('@/assets/premium/dishes/polish/polish_11.webp') },
  { slug: 'pulpety_koperkowe', category: 'kuchnia_polska', labelPl: 'Pulpety w sosie koperkowym', aliases: ['pulpety', 'pulpety w koperku', 'klopsiki koperkowe'], storagePath: 'dania/polish/polish_12.webp', localAsset: require('@/assets/premium/dishes/polish/polish_12.webp') },
  { slug: 'pierogi_ruskie_podsmazane', category: 'kuchnia_polska', labelPl: 'Pierogi ruskie podsmażane', aliases: ['pierogi ruskie', 'ruskie podsmażane'], storagePath: 'dania/polish/polish_13.webp', localAsset: require('@/assets/premium/dishes/polish/polish_13.webp') },
  { slug: 'mini_kopytka_grzybowe', category: 'kuchnia_polska', labelPl: 'Mini kopytka w sosie grzybowym', aliases: ['kopytka grzybowe', 'mini kopytka'], storagePath: 'dania/polish/polish_14.webp', localAsset: require('@/assets/premium/dishes/polish/polish_14.webp') },
  { slug: 'pyzy_bez_miesa', category: 'kuchnia_polska', labelPl: 'Pyzy bez mięsa (lizańce)', aliases: ['lizańce', 'pyzy bez mięsa', 'pyzy ze skwarkami'], storagePath: 'dania/polish/polish_15.webp', localAsset: require('@/assets/premium/dishes/polish/polish_15.webp') },
  { slug: 'pierogi_pieczone_kapusta', category: 'kuchnia_polska', labelPl: 'Pierogi pieczone z kapustą i grzybami', aliases: ['pierogi pieczone', 'pierogi wigilijne', 'pierogi z kapustą'], storagePath: 'dania/polish/polish_16.webp', localAsset: require('@/assets/premium/dishes/polish/polish_16.webp') },
  { slug: 'pierogi_slodkie_twarog', category: 'kuchnia_polska', labelPl: 'Pierogi na słodko z twarogiem', aliases: ['pierogi z twarogiem', 'pierogi na słodko', 'pierogi z serem'], storagePath: 'dania/polish/polish_17.webp', localAsset: require('@/assets/premium/dishes/polish/polish_17.webp') },
  { slug: 'kluski_przecierane', category: 'kuchnia_polska', labelPl: 'Kluski przecierane ze skwarkami', aliases: ['kluski przecierane', 'zacierki', 'kluseczki ze skwarkami'], storagePath: 'dania/polish/polish_18.webp', localAsset: require('@/assets/premium/dishes/polish/polish_18.webp') },
  { slug: 'kluski_slaskie_rosol', category: 'kuchnia_polska', labelPl: 'Kluski śląskie w czystym rosole', aliases: ['kluski w rosole', 'śląskie w bulionie'], storagePath: 'dania/polish/polish_19.webp', localAsset: require('@/assets/premium/dishes/polish/polish_19.webp') },
  { slug: 'paluszki_ziemniaczane', category: 'kuchnia_polska', labelPl: 'Paluszki ziemniaczane panierowane', aliases: ['paluszki ziemniaczane', 'krokiety ziemniaczane'], storagePath: 'dania/polish/polish_20.webp', localAsset: require('@/assets/premium/dishes/polish/polish_20.webp') },
  { slug: 'racuchy_z_jablkami', category: 'kuchnia_polska', labelPl: 'Racuchy z jabłkami na słodko', aliases: ['racuchy', 'racuchy z jabłkami'], storagePath: 'dania/polish/polish_21.webp', localAsset: require('@/assets/premium/dishes/polish/polish_21.webp') },
  { slug: 'rolada_slaska', category: 'kuchnia_polska', labelPl: 'Rolada śląska z modrą kapustą', aliases: ['rolada śląska', 'rolada z kapustą'], storagePath: 'dania/polish/polish_22.webp', localAsset: require('@/assets/premium/dishes/polish/polish_22.webp') },
  { slug: 'bigos_staropolski', category: 'kuchnia_polska', labelPl: 'Bigos staropolski', aliases: ['bigos', 'bigos staropolski', 'hunter stew'], storagePath: 'dania/polish/polish_23.webp', localAsset: require('@/assets/premium/dishes/polish/polish_23.webp') },
  { slug: 'biala_kielbasa_cebulka', category: 'kuchnia_polska', labelPl: 'Biała kiełbasa zasmażana z cebulką', aliases: ['biała kiełbasa z cebulką', 'kiełbasa zasmażana'], storagePath: 'dania/polish/polish_24.webp', localAsset: require('@/assets/premium/dishes/polish/polish_24.webp') },
  { slug: 'smietana_kwasna', category: 'kuchnia_polska', labelPl: 'Gęsta kwaśna śmietana', aliases: ['śmietana', 'kwaśna śmietana'], storagePath: 'dania/polish/polish_25.webp', localAsset: require('@/assets/premium/dishes/polish/polish_25.webp'), recipeEligible: false },
];
