/**
 * Katalog grafik — pieczenie i mięsa świąteczne (plansza 5×5).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const ROASTS_CATALOG: DishImageEntry[] = [
  { slug: 'karp_wigilijny', category: 'kuchnia_polska', labelPl: 'Karp wigilijny smażony', aliases: ['karp', 'karp wigilijny', 'karp smażony'], storagePath: 'dania/roasts/roast_01.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_01.webp') },
  { slug: 'schab_ze_sliwka', category: 'kuchnia_polska', labelPl: 'Schab pieczony ze śliwką', aliases: ['schab ze śliwką', 'schab pieczony', 'pieczeń ze śliwką'], storagePath: 'dania/roasts/roast_02.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_02.webp') },
  { slug: 'pasztet_swiateczny', category: 'kuchnia_polska', labelPl: 'Pasztet świąteczny z żurawiną', aliases: ['pasztet', 'pasztet świąteczny', 'pasztet z żurawiną'], storagePath: 'dania/roasts/roast_03.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_03.webp') },
  { slug: 'ges_nadziewana', category: 'kuchnia_polska', labelPl: 'Gęś nadziewana owocami', aliases: ['gęś', 'gęś pieczona', 'pieczona gęś'], storagePath: 'dania/roasts/roast_04.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_04.webp') },
  { slug: 'szynka_swiateczna', category: 'kuchnia_polska', labelPl: 'Szynka świąteczna glazurowana', aliases: ['szynka świąteczna', 'szynka glazurowana', 'christmas ham'], storagePath: 'dania/roasts/roast_05.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_05.webp') },
  { slug: 'udo_kaczki', category: 'kuchnia_polska', labelPl: 'Pieczone udo z kaczki', aliases: ['udo kaczki', 'kaczka udo', 'duck leg', 'udko z kaczki', 'chrupiące udko z kaczki', 'udko kaczki'], storagePath: 'dania/roasts/roast_06.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_06.webp') },
  { slug: 'boczek_zwijany', category: 'kuchnia_polska', labelPl: 'Boczek pieczony zwijany', aliases: ['boczek pieczony', 'rolada z boczku', 'boczek zwijany'], storagePath: 'dania/roasts/roast_07.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_07.webp') },
  { slug: 'beef_wellington', category: 'kuchnia_polska', labelPl: 'Polędwica Beef Wellington', aliases: ['beef wellington', 'wellington', 'wołowina w cieście'], storagePath: 'dania/roasts/roast_08.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_08.webp') },
  { slug: 'piers_indyka', category: 'kuchnia_polska', labelPl: 'Pieczeń z piersi indyka', aliases: ['indyk', 'pierś indyka', 'turkey roast'], storagePath: 'dania/roasts/roast_09.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_09.webp') },
  { slug: 'dorsz_pieczony', category: 'kuchnia_polska', labelPl: 'Dorsz pieczony z warzywami', aliases: ['dorsz', 'dorsz pieczony', 'baked cod'], storagePath: 'dania/roasts/roast_10.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_10.webp') },
  { slug: 'pieczen_dziczyzna', category: 'kuchnia_polska', labelPl: 'Pieczeń z dziczyzny', aliases: ['dziczyzna', 'jeleń', 'dzik pieczeń'], storagePath: 'dania/roasts/roast_11.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_11.webp') },
  { slug: 'karkowka_z_cebula', category: 'kuchnia_polska', labelPl: 'Karkówka pieczona z cebulą', aliases: ['karkówka', 'karkówka pieczona', 'karkówka z cebulą'], storagePath: 'dania/roasts/roast_12.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_12.webp') },
  { slug: 'losos_maslo_ziolowe', category: 'kuchnia_polska', labelPl: 'Filet z łososia z masłem ziołowym', aliases: ['łosoś', 'filet z łososia', 'łosoś pieczony'], storagePath: 'dania/roasts/roast_13.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_13.webp') },
  { slug: 'zeberka_miod', category: 'kuchnia_polska', labelPl: 'Żeberka pieczone w miodzie', aliases: ['żeberka', 'żeberka miodowe', 'honey ribs'], storagePath: 'dania/roasts/roast_14.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_14.webp') },
  { slug: 'rolada_kurczak', category: 'kuchnia_polska', labelPl: 'Rolada z kurczaka z nadzieniem', aliases: ['rolada z kurczaka', 'faszerowany kurczak'], storagePath: 'dania/roasts/roast_15.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_15.webp') },
  { slug: 'biala_kielbasa_zapiekana', category: 'kuchnia_polska', labelPl: 'Biała kiełbasa zapiekana z cebulą', aliases: ['biała kiełbasa', 'kiełbasa z cebulą'], storagePath: 'dania/roasts/roast_16.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_16.webp') },
  { slug: 'pieczen_rzymska', category: 'kuchnia_polska', labelPl: 'Pieczeń rzymska z jajkiem', aliases: ['pieczeń rzymska', 'klops z jajkiem', 'meatloaf egg'], storagePath: 'dania/roasts/roast_17.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_17.webp') },
  { slug: 'gicz_cielęca', category: 'kuchnia_polska', labelPl: 'Gicz cielęca / wołowa w sosie', aliases: ['gicz', 'gicz cielęca', 'osso buco'], storagePath: 'dania/roasts/roast_18.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_18.webp') },
  { slug: 'korona_jagnieca', category: 'kuchnia_polska', labelPl: 'Korona z żeberek jagnięcych', aliases: ['korona jagnięca', 'crown roast', 'żeberka jagnięce'], storagePath: 'dania/roasts/roast_19.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_19.webp') },
  { slug: 'kaczka_porcja', category: 'kuchnia_polska', labelPl: 'Pieczona kaczka', aliases: ['kaczka', 'pieczona kaczka', 'roast duck'], storagePath: 'dania/roasts/roast_20.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_20.webp') },
  { slug: 'pstrag_calosci', category: 'kuchnia_polska', labelPl: 'Pstrąg pieczony w całości', aliases: ['pstrąg', 'pstrąg pieczony', 'trout'], storagePath: 'dania/roasts/roast_21.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_21.webp') },
  { slug: 'tarta_grzyby_kapusta', category: 'kuchnia_polska', labelPl: 'Wytrawna tarta z grzybami i kapustą', aliases: ['tarta grzybowa', 'tarta z kapustą'], storagePath: 'dania/roasts/roast_22.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_22.webp') },
  { slug: 'brisket_mostek', category: 'kuchnia_polska', labelPl: 'Mostek wołowy (Brisket)', aliases: ['brisket', 'mostek wołowy', 'mostek pieczony'], storagePath: 'dania/roasts/roast_23.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_23.webp') },
  { slug: 'golonka_na_kapuscie', category: 'kuchnia_polska', labelPl: 'Golonka pieczona na kapuście', aliases: ['golonka', 'golonka pieczona', 'golonka na kapuście'], storagePath: 'dania/roasts/roast_24.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_24.webp') },
  { slug: 'sos_zurawinowy', category: 'kuchnia_polska', labelPl: 'Domowy sos żurawinowy', aliases: ['sos żurawinowy', 'żurawina', 'cranberry sauce'], storagePath: 'dania/roasts/roast_25.webp', localAsset: require('@/assets/premium/dishes/roasts/roast_25.webp'), recipeEligible: false },
];
