/**
 * Katalog grafik — sosy (plansza 45, 5×5, rządami L→P).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const SAUCES_CATALOG: DishImageEntry[] = [
  { slug: 'sos_smietankowo_ziolowy', category: 'kuchnia_polska', labelPl: 'Sos śmietankowo-ziołowy', aliases: ['sos śmietankowy', 'cream herb sauce', 'sos ziołowy śmietankowy', 'sos smietankowo ziolowy'], storagePath: 'dania/sauces/sauce_01.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_01.webp') },
  { slug: 'sos_curry', category: 'kuchnia_polska', labelPl: 'Sos curry', aliases: ['curry sauce', 'sos curry żółty'], storagePath: 'dania/sauces/sauce_02.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_02.webp') },
  { slug: 'sos_grzybowy_kurkowy', category: 'kuchnia_polska', labelPl: 'Sos grzybowy (kurkowy)', aliases: ['sos grzybowy', 'sos kurkowy', 'chanterelle sauce', 'mushroom sauce'], storagePath: 'dania/sauces/sauce_03.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_03.webp') },
  { slug: 'sos_pieczeniowy_gravy', category: 'kuchnia_polska', labelPl: 'Ciemny sos pieczeniowy (Gravy)', aliases: ['gravy', 'sos pieczeniowy', 'brown gravy', 'dark gravy'], storagePath: 'dania/sauces/sauce_04.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_04.webp') },
  { slug: 'sos_pieprzowy', category: 'kuchnia_polska', labelPl: 'Sos pieprzowy', aliases: ['pepper sauce', 'peppercorn sauce', 'sos z pieprzem'], storagePath: 'dania/sauces/sauce_05.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_05.webp') },
  { slug: 'sos_chrzanowy', category: 'kuchnia_polska', labelPl: 'Sos chrzanowy', aliases: ['horseradish sauce', 'chrzan', 'sos z chrzanem'], storagePath: 'dania/sauces/sauce_06.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_06.webp') },
  { slug: 'sos_borowkowy', category: 'kuchnia_polska', labelPl: 'Sos borówkowy do mięs', aliases: ['sos borówkowy', 'blueberry sauce', 'lingonberry', 'sos jagodowy do mięs'], storagePath: 'dania/sauces/sauce_07.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_07.webp') },
  { slug: 'sos_serowy_fondue', category: 'kuchnia_polska', labelPl: 'Sos serowy (Fondue)', aliases: ['sos serowy', 'cheese sauce', 'fondue', 'cheese fondue'], storagePath: 'dania/sauces/sauce_08.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_08.webp') },
  { slug: 'sos_koperkowo_cytrynowy', category: 'kuchnia_polska', labelPl: 'Sos koperkowo-cytrynowy do ryb', aliases: ['sos koperkowy', 'dill lemon sauce', 'sos cytrynowy do ryb', 'sos koperkowo cytrynowy'], storagePath: 'dania/sauces/sauce_09.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_09.webp') },
  { slug: 'sos_holenderski', category: 'kuchnia_polska', labelPl: 'Sos holenderski', aliases: ['hollandaise', 'holenderski'], storagePath: 'dania/sauces/sauce_10.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_10.webp') },
  { slug: 'sos_bernenski', category: 'kuchnia_polska', labelPl: 'Sos berneński (Béarnaise)', aliases: ['béarnaise', 'bearnaise', 'sos berneński', 'bernenski'], storagePath: 'dania/sauces/sauce_11.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_11.webp') },
  { slug: 'sos_bourbon_bbq', category: 'kuchnia_polska', labelPl: 'Glazurowany sos Bourbon BBQ', aliases: ['bourbon bbq', 'bbq bourbon', 'sos bbq bourbon', 'glaze bourbon'], storagePath: 'dania/sauces/sauce_12.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_12.webp') },
  { slug: 'sos_buffalo', category: 'kuchnia_polska', labelPl: 'Ostry sos Buffalo', aliases: ['buffalo sauce', 'sos buffalo', 'hot buffalo'], storagePath: 'dania/sauces/sauce_13.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_13.webp') },
  { slug: 'sos_sojowo_miodowy', category: 'kuchnia_polska', labelPl: 'Sos sojowo-miodowy z czosnkiem', aliases: ['sos sojowo miodowy', 'honey soy garlic', 'soy honey sauce'], storagePath: 'dania/sauces/sauce_14.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_14.webp') },
  { slug: 'sos_aioli_pieczony_czosnek', category: 'kuchnia_polska', labelPl: 'Sos czosnkowy aioli z pieczonym czosnkiem', aliases: ['aioli', 'sos czosnkowy', 'garlic aioli', 'aioli pieczony czosnek', 'roasted garlic aioli'], storagePath: 'dania/sauces/sauce_15.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_15.webp') },
  { slug: 'sos_demi_glace', category: 'kuchnia_polska', labelPl: 'Gęsty sos Demi-Glace', aliases: ['demi-glace', 'demi glace', 'sos demi'], storagePath: 'dania/sauces/sauce_16.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_16.webp') },
  { slug: 'sos_jogurtowo_mietowy', category: 'kuchnia_polska', labelPl: 'Sos jogurtowo-miętowy', aliases: ['sos miętowy', 'yogurt mint', 'mint yogurt sauce', 'raita'], storagePath: 'dania/sauces/sauce_17.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_17.webp') },
  { slug: 'sos_sliwkowy', category: 'kuchnia_polska', labelPl: 'Sos śliwkowy do mięs', aliases: ['sos śliwkowy', 'plum sauce', 'sos sliwkowy'], storagePath: 'dania/sauces/sauce_18.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_18.webp') },
  { slug: 'sos_orzechowy_satay', category: 'kuchnia_polska', labelPl: 'Pikantny sos orzechowy (Satay)', aliases: ['sos orzechowy', 'satay', 'peanut sauce', 'sos satay'], storagePath: 'dania/sauces/sauce_19.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_19.webp') },
  { slug: 'sos_zurawinowy', category: 'kuchnia_polska', labelPl: 'Tradycyjny sos żurawinowy', aliases: ['sos żurawinowy', 'cranberry sauce', 'zurawina'], storagePath: 'dania/sauces/sauce_20.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_20.webp') },
  { slug: 'sos_carbonara', category: 'kuchnia_polska', labelPl: 'Sos Carbonara', aliases: ['carbonara sauce', 'sos carbonara'], storagePath: 'dania/sauces/sauce_21.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_21.webp') },
  { slug: 'sos_bolognese', category: 'kuchnia_polska', labelPl: 'Sos mięsny Bolognese', aliases: ['bolognese', 'sos boloński', 'meat sauce', 'ragu', 'sos pomidorowy mięsny', 'sos pomidorowy', 'tomato sauce', 'marinara', 'arrabbiata', 'napoletana', 'sos napoli'], storagePath: 'dania/sauces/sauce_22.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_22.webp') },
  { slug: 'sos_slodko_kwasny', category: 'kuchnia_polska', labelPl: 'Sos słodko-kwaśny z imbirem', aliases: ['sos słodko kwaśny', 'sweet and sour', 'sweet sour ginger'], storagePath: 'dania/sauces/sauce_23.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_23.webp') },
  { slug: 'sos_cajun', category: 'kuchnia_polska', labelPl: 'Sos Cajun', aliases: ['cajun sauce', 'sos cajun'], storagePath: 'dania/sauces/sauce_24.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_24.webp') },
  { slug: 'miseczka_grissini', category: 'kuchnia_polska', labelPl: 'Miseczka z grissini', aliases: ['grissini', 'paluszki chlebowe', 'breadsticks'], storagePath: 'dania/sauces/sauce_25.webp', localAsset: require('@/assets/premium/dishes/sauces/sauce_25.webp'), recipeEligible: false },
];
