/**
 * Katalog grafik dań — surówki / kebaby / obiady (plansze 5×5, lokalne WebP).
 */
type DishImageEntry = {
  slug: string;
  category: 'kuchnia_polska';
  labelPl: string;
  aliases: string[];
  storagePath: string;
  localAsset: number;
};

export const SIDES_CATALOG: DishImageEntry[] = [
  { slug: 'coleslaw', category: 'kuchnia_polska', labelPl: 'Surówka Coleslaw', aliases: ['coleslaw', 'surówka coleslaw', 'kapusta marchewka', 'biała czerwona kapusta'], storagePath: 'dania/sides/side_01.webp', localAsset: require('@/assets/premium/dishes/sides/side_01.webp') },
  { slug: 'mizeria', category: 'kuchnia_polska', labelPl: 'Mizeria', aliases: ['mizeria', 'mizeria z ogórków', 'ogórki śmietana'], storagePath: 'dania/sides/side_02.webp', localAsset: require('@/assets/premium/dishes/sides/side_02.webp') },
  { slug: 'buraczki_tarte', category: 'kuchnia_polska', labelPl: 'Buraczki tarte', aliases: ['buraczki tarte', 'buraki tarte', 'buraczki z cebulką'], storagePath: 'dania/sides/side_03.webp', localAsset: require('@/assets/premium/dishes/sides/side_03.webp') },
  { slug: 'kapusta_zasmażana_kminek', category: 'kuchnia_polska', labelPl: 'Kapusta zasmażana', aliases: ['kapusta zasmażana', 'kapusta kwaszona', 'kapusta z kminkiem'], storagePath: 'dania/sides/side_04.webp', localAsset: require('@/assets/premium/dishes/sides/side_04.webp') },
  { slug: 'warzywa_grillowane', category: 'kuchnia_polska', labelPl: 'Warzywa grillowane', aliases: ['warzywa grillowane', 'grillowane warzywa', 'cukinia papryka bakłażan'], storagePath: 'dania/sides/side_05.webp', localAsset: require('@/assets/premium/dishes/sides/side_05.webp') },
  { slug: 'surowka_marchew_jablko', category: 'kuchnia_polska', labelPl: 'Surówka z marchewki i jabłka', aliases: ['marchewka jabłko', 'surówka marchewka', 'carrot apple'], storagePath: 'dania/sides/side_06.webp', localAsset: require('@/assets/premium/dishes/sides/side_06.webp') },
  { slug: 'surowka_por_kapusta', category: 'kuchnia_polska', labelPl: 'Surówka z pora i białej kapusty', aliases: ['surówka z pora', 'por kapusta', 'leek salad'], storagePath: 'dania/sides/side_07.webp', localAsset: require('@/assets/premium/dishes/sides/side_07.webp') },
  { slug: 'surowka_boczniak', category: 'kuchnia_polska', labelPl: 'Surówka z boczniaka', aliases: ['boczniaki', 'surówka boczniak', 'smażone boczniaki'], storagePath: 'dania/sides/side_08.webp', localAsset: require('@/assets/premium/dishes/sides/side_08.webp') },
  { slug: 'ogorki_kiszone', category: 'kuchnia_polska', labelPl: 'Ogórki kiszone', aliases: ['ogórki kiszone', 'kiszone ogórki', 'pickles'], storagePath: 'dania/sides/side_09.webp', localAsset: require('@/assets/premium/dishes/sides/side_09.webp') },
  { slug: 'surowka_czerwona_kapusta', category: 'kuchnia_polska', labelPl: 'Surówka z czerwonej kapusty', aliases: ['czerwona kapusta', 'surówka czerwona kapusta', 'red cabbage'], storagePath: 'dania/sides/side_10.webp', localAsset: require('@/assets/premium/dishes/sides/side_10.webp') },
  { slug: 'surowka_rzodkiewka', category: 'kuchnia_polska', labelPl: 'Surówka z rzodkiewki', aliases: ['rzodkiewka', 'surówka rzodkiewka', 'radish salad'], storagePath: 'dania/sides/side_11.webp', localAsset: require('@/assets/premium/dishes/sides/side_11.webp') },
  { slug: 'surowka_kiszona_kapusta_marchew', category: 'kuchnia_polska', labelPl: 'Surówka z kiszonej kapusty z marchewką', aliases: ['kiszona kapusta marchewka', 'kapusta kiszona z marchewką'], storagePath: 'dania/sides/side_12.webp', localAsset: require('@/assets/premium/dishes/sides/side_12.webp') },
  { slug: 'pieczone_warzywa_korzeniowe', category: 'kuchnia_polska', labelPl: 'Pieczone warzywa korzeniowe', aliases: ['warzywa korzeniowe', 'pieczone korzeniowe', 'roasted root'], storagePath: 'dania/sides/side_13.webp', localAsset: require('@/assets/premium/dishes/sides/side_13.webp') },
  { slug: 'buraczki_marynowane', category: 'kuchnia_polska', labelPl: 'Buraczki marynowane', aliases: ['buraczki marynowane', 'buraki w plasterkach', 'marinated beets'], storagePath: 'dania/sides/side_14.webp', localAsset: require('@/assets/premium/dishes/sides/side_14.webp') },
  { slug: 'szpinak_zasmażany', category: 'kuchnia_polska', labelPl: 'Szpinak zasmażany', aliases: ['szpinak zasmażany', 'szpinak ze śmietaną', 'creamed spinach'], storagePath: 'dania/sides/side_15.webp', localAsset: require('@/assets/premium/dishes/sides/side_15.webp') },
  { slug: 'marchewka_groszek', category: 'kuchnia_polska', labelPl: 'Marchewka z groszkiem', aliases: ['marchewka z groszkiem', 'groszek marchewka', 'peas and carrots'], storagePath: 'dania/sides/side_16.webp', localAsset: require('@/assets/premium/dishes/sides/side_16.webp') },
  { slug: 'brokuly_na_parze', category: 'kuchnia_polska', labelPl: 'Brokuły na parze', aliases: ['brokuły', 'brokuły na parze', 'steamed broccoli'], storagePath: 'dania/sides/side_17.webp', localAsset: require('@/assets/premium/dishes/sides/side_17.webp') },
  { slug: 'salatka_kukurydza_papryka', category: 'kuchnia_polska', labelPl: 'Sałatka z kukurydzy i papryki', aliases: ['kukurydza papryka', 'sałatka kukurydza', 'corn pepper'], storagePath: 'dania/sides/side_18.webp', localAsset: require('@/assets/premium/dishes/sides/side_18.webp') },
  { slug: 'pieczony_kalafior', category: 'kuchnia_polska', labelPl: 'Pieczone cząstki kalafiora', aliases: ['kalafior', 'pieczony kalafior', 'roasted cauliflower'], storagePath: 'dania/sides/side_19.webp', localAsset: require('@/assets/premium/dishes/sides/side_19.webp') },
  { slug: 'marynowane_karczochy', category: 'kuchnia_polska', labelPl: 'Marynowane karczochy', aliases: ['karczochy', 'marynowane karczochy', 'artichokes'], storagePath: 'dania/sides/side_20.webp', localAsset: require('@/assets/premium/dishes/sides/side_20.webp') },
  { slug: 'cebulki_konserwowe', category: 'kuchnia_polska', labelPl: 'Cebulki konserwowe', aliases: ['cebulki konserwowe', 'cebulki perłowe', 'pearl onions'], storagePath: 'dania/sides/side_21.webp', localAsset: require('@/assets/premium/dishes/sides/side_21.webp') },
  { slug: 'salatka_pomidor_cebula', category: 'kuchnia_polska', labelPl: 'Sałatka z pomidorów i czerwonej cebuli', aliases: ['pomidory cebula', 'sałatka pomidorowa', 'tomato onion'], storagePath: 'dania/sides/side_22.webp', localAsset: require('@/assets/premium/dishes/sides/side_22.webp') },
  { slug: 'surowka_seler', category: 'kuchnia_polska', labelPl: 'Surówka z selera korzeniowego', aliases: ['seler korzeniowy', 'surówka seler', 'celeriac', 'seler rodzynki'], storagePath: 'dania/sides/side_23.webp', localAsset: require('@/assets/premium/dishes/sides/side_23.webp') },
  { slug: 'pieczona_dynia', category: 'kuchnia_polska', labelPl: 'Pieczona dynia', aliases: ['pieczona dynia', 'dynia w kostkę', 'roasted pumpkin'], storagePath: 'dania/sides/side_24.webp', localAsset: require('@/assets/premium/dishes/sides/side_24.webp') },
  { slug: 'salatka_ogrodowa_sides', category: 'kuchnia_polska', labelPl: 'Klasyczna sałatka ogrodowa', aliases: ['sałatka ogrodowa', 'garden salad', 'sałatka ze świeżych warzyw'], storagePath: 'dania/sides/side_25.webp', localAsset: require('@/assets/premium/dishes/sides/side_25.webp') },
];

export const KEBABS_CATALOG: DishImageEntry[] = [
  { slug: 'kebab_rollo', category: 'kuchnia_polska', labelPl: 'Kebab w rollo', aliases: ['kebab w rollo', 'rollo', 'kebab tortilla', 'kebab wrap'], storagePath: 'dania/kebabs/kebab_01.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_01.webp') },
  { slug: 'kebab_talerz', category: 'kuchnia_polska', labelPl: 'Kebab na talerzu', aliases: ['kebab na talerzu', 'kebab z frytkami', 'plate kebab'], storagePath: 'dania/kebabs/kebab_02.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_02.webp') },
  { slug: 'falafel_tahini_kebab', category: 'kuchnia_polska', labelPl: 'Chrupiące falafle z sosem tahini', aliases: ['falafel', 'falafle', 'chrupiące falafle', 'tahini'], storagePath: 'dania/kebabs/kebab_03.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_03.webp') },
  { slug: 'szawarma_kurczak', category: 'kuchnia_polska', labelPl: 'Szawarma z kurczaka', aliases: ['szawarma', 'shawarma', 'szawarma z kurczaka'], storagePath: 'dania/kebabs/kebab_04.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_04.webp') },
  { slug: 'adana_kebab', category: 'kuchnia_polska', labelPl: 'Adana kebab', aliases: ['adana', 'adana kebab'], storagePath: 'dania/kebabs/kebab_05.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_05.webp') },
  { slug: 'shish_taouk', category: 'kuchnia_polska', labelPl: 'Shish taouk', aliases: ['shish taouk', 'szaszłyki kurczak', 'taouk'], storagePath: 'dania/kebabs/kebab_06.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_06.webp') },
  { slug: 'kofta_wolowa', category: 'kuchnia_polska', labelPl: 'Kofta wołowa', aliases: ['kofta', 'kofta wołowa', 'mięso na patykach'], storagePath: 'dania/kebabs/kebab_07.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_07.webp') },
  { slug: 'pita_faszerowana', category: 'kuchnia_polska', labelPl: 'Chlebki pita faszerowane', aliases: ['pita faszerowana', 'chlebki pita', 'pita z mięsem'], storagePath: 'dania/kebabs/kebab_08.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_08.webp') },
  { slug: 'lahmacun', category: 'kuchnia_polska', labelPl: 'Lahmacun', aliases: ['lahmacun', 'turecka pizza', 'lahmacun pizza'], storagePath: 'dania/kebabs/kebab_09.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_09.webp') },
  { slug: 'fatayer_szpinak', category: 'kuchnia_polska', labelPl: 'Fatayer ze szpinakiem', aliases: ['fatayer', 'fatayer szpinak', 'pierożki szpinak'], storagePath: 'dania/kebabs/kebab_10.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_10.webp') },
  { slug: 'kibbeh', category: 'kuchnia_polska', labelPl: 'Chrupiące kibbeh', aliases: ['kibbeh', 'chrupiące kibbeh', 'bulgur mięso'], storagePath: 'dania/kebabs/kebab_11.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_11.webp') },
  { slug: 'hummus_klasyczny', category: 'kuchnia_polska', labelPl: 'Hummus klasyczny', aliases: ['hummus', 'hummus klasyczny', 'hummus z ciecierzycą'], storagePath: 'dania/kebabs/kebab_12.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_12.webp') },
  { slug: 'baba_ghanoush', category: 'kuchnia_polska', labelPl: 'Baba ghanoush', aliases: ['baba ghanoush', 'baba ganoush', 'pasta bakłażan'], storagePath: 'dania/kebabs/kebab_13.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_13.webp') },
  { slug: 'halloumi_grill', category: 'kuchnia_polska', labelPl: 'Grillowany ser halloumi', aliases: ['halloumi', 'grillowany halloumi', 'ser halloumi'], storagePath: 'dania/kebabs/kebab_14.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_14.webp') },
  { slug: 'muhammara', category: 'kuchnia_polska', labelPl: 'Muhammara', aliases: ['muhammara', 'dip papryka orzechy'], storagePath: 'dania/kebabs/kebab_15.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_15.webp') },
  { slug: 'dolma_sarma', category: 'kuchnia_polska', labelPl: 'Dolma / Sarma', aliases: ['dolma', 'sarma', 'liście winogron'], storagePath: 'dania/kebabs/kebab_16.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_16.webp') },
  { slug: 'naan', category: 'kuchnia_polska', labelPl: 'Chlebki naan', aliases: ['naan', 'chlebki naan', 'chleb naan'], storagePath: 'dania/kebabs/kebab_17.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_17.webp') },
  { slug: 'tabbouleh', category: 'kuchnia_polska', labelPl: 'Sałatka tabbouleh', aliases: ['tabbouleh', 'tabule', 'sałatka pietruszka'], storagePath: 'dania/kebabs/kebab_18.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_18.webp') },
  { slug: 'fattoush', category: 'kuchnia_polska', labelPl: 'Sałatka fattoush', aliases: ['fattoush', 'sałatka fattoush', 'pita sałatka'], storagePath: 'dania/kebabs/kebab_19.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_19.webp') },
  { slug: 'talerz_pikli', category: 'kuchnia_polska', labelPl: 'Talerz pikli', aliases: ['pikle', 'talerz pikli', 'turshi', 'marynowana rzepa'], storagePath: 'dania/kebabs/kebab_20.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_20.webp') },
  { slug: 'ryz_pilaw', category: 'kuchnia_polska', labelPl: 'Ryż pilaw / basmati', aliases: ['pilaw', 'ryż pilaw', 'basmati', 'ryż basmati'], storagePath: 'dania/kebabs/kebab_21.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_21.webp') },
  { slug: 'chipsy_pita', category: 'kuchnia_polska', labelPl: 'Chipsy z pity', aliases: ['chipsy z pity', 'pita chips', 'chrupiące chipsy pita'], storagePath: 'dania/kebabs/kebab_22.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_22.webp') },
  { slug: 'pieczona_ciecierzyca_kebab', category: 'kuchnia_polska', labelPl: 'Pieczona ciecierzyca', aliases: ['pieczona ciecierzyca', 'ciecierzyca chrupiąca', 'roasted chickpeas'], storagePath: 'dania/kebabs/kebab_23.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_23.webp') },
  { slug: 'grillowane_papryczki', category: 'kuchnia_polska', labelPl: 'Grillowane ostre papryczki', aliases: ['ostre papryczki', 'grillowane papryczki', 'chili grill'], storagePath: 'dania/kebabs/kebab_24.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_24.webp') },
  { slug: 'sos_toum', category: 'kuchnia_polska', labelPl: 'Sos toum', aliases: ['toum', 'sos toum', 'sos czosnkowy'], storagePath: 'dania/kebabs/kebab_25.webp', localAsset: require('@/assets/premium/dishes/kebabs/kebab_25.webp') },
];

export const DINNERS_CATALOG: DishImageEntry[] = [
  { slug: 'kotlet_schabowy', category: 'kuchnia_polska', labelPl: 'Kotlet schabowy', aliases: ['schabowy', 'kotlet schabowy', 'schab'], storagePath: 'dania/dinners/dinner_01.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_01.webp') },
  { slug: 'kotlet_mielony', category: 'kuchnia_polska', labelPl: 'Kotlet mielony', aliases: ['kotlet mielony', 'mielony'], storagePath: 'dania/dinners/dinner_02.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_02.webp') },
  { slug: 'rolada_slaska', category: 'kuchnia_polska', labelPl: 'Rolada śląska', aliases: ['rolada śląska', 'rolada slaska', 'kluski śląskie'], storagePath: 'dania/dinners/dinner_03.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_03.webp') },
  { slug: 'pieczona_kaczka', category: 'kuchnia_polska', labelPl: 'Pieczona kaczka', aliases: ['kaczka', 'pieczona kaczka', 'kaczka z jabłkami'], storagePath: 'dania/dinners/dinner_04.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_04.webp') },
  { slug: 'gulasz_wolowy', category: 'kuchnia_polska', labelPl: 'Gulasz wołowy', aliases: ['gulasz', 'gulasz wołowy', 'beef stew'], storagePath: 'dania/dinners/dinner_05.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_05.webp') },
  { slug: 'golabki', category: 'kuchnia_polska', labelPl: 'Gołąbki', aliases: ['gołąbki', 'golabki', 'gołąbki w sosie'], storagePath: 'dania/dinners/dinner_06.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_06.webp') },
  { slug: 'kotlet_de_volaille', category: 'kuchnia_polska', labelPl: 'Kotlet de Volaille', aliases: ['de volaille', 'kotlet de volaille', 'volaille'], storagePath: 'dania/dinners/dinner_07.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_07.webp') },
  { slug: 'placki_ziemniaczane', category: 'kuchnia_polska', labelPl: 'Placuszki ziemniaczane', aliases: ['placki ziemniaczane', 'placuszki', 'potato pancakes'], storagePath: 'dania/dinners/dinner_08.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_08.webp') },
  { slug: 'barszcz_z_uszkami', category: 'kuchnia_polska', labelPl: 'Barszcz czerwony z uszkami', aliases: ['barszcz z uszkami', 'barszcz czerwony', 'uszka'], storagePath: 'dania/dinners/dinner_09.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_09.webp') },
  { slug: 'zurek_staropolski', category: 'kuchnia_polska', labelPl: 'Żurek staropolski', aliases: ['żurek staropolski', 'zurek z jajkiem', 'żurek z kiełbasą'], storagePath: 'dania/dinners/dinner_10.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_10.webp') },
  { slug: 'schab_ze_sliwka', category: 'kuchnia_polska', labelPl: 'Schab pieczony ze śliwką', aliases: ['schab ze śliwką', 'schab pieczony', 'schab śliwka'], storagePath: 'dania/dinners/dinner_11.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_11.webp') },
  { slug: 'bitki_wolowe', category: 'kuchnia_polska', labelPl: 'Duszone bity wołowe', aliases: ['bitki', 'bity wołowe', 'bitki wołowe'], storagePath: 'dania/dinners/dinner_12.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_12.webp') },
  { slug: 'golonka_pieczona', category: 'kuchnia_polska', labelPl: 'Golonka pieczona', aliases: ['golonka', 'golonka pieczona'], storagePath: 'dania/dinners/dinner_13.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_13.webp') },
  { slug: 'rosol_tradycyjny', category: 'kuchnia_polska', labelPl: 'Tradycyjny rosół', aliases: ['rosół', 'tradycyjny rosół', 'rosół z makaronem'], storagePath: 'dania/dinners/dinner_14.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_14.webp') },
  { slug: 'flaki_wolowe', category: 'kuchnia_polska', labelPl: 'Flaki wołowe', aliases: ['flaki', 'flaki wołowe', 'flaki po zamojsku'], storagePath: 'dania/dinners/dinner_15.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_15.webp') },
  { slug: 'klopsiki_pulpety', category: 'kuchnia_polska', labelPl: 'Klopsiki / pulpety', aliases: ['klopsiki', 'pulpety', 'klopsiki w sosie koperkowym'], storagePath: 'dania/dinners/dinner_16.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_16.webp') },
  { slug: 'bigos_staropolski', category: 'kuchnia_polska', labelPl: 'Bigos staropolski', aliases: ['bigos', 'bigos staropolski'], storagePath: 'dania/dinners/dinner_17.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_17.webp') },
  { slug: 'mlode_ziemniaki', category: 'kuchnia_polska', labelPl: 'Młode ziemniaki', aliases: ['młode ziemniaki', 'ziemniaki z koperkiem'], storagePath: 'dania/dinners/dinner_18.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_18.webp') },
  { slug: 'kapusta_zasmażana_obiad', category: 'kuchnia_polska', labelPl: 'Kapusta zasmażana z boczkiem', aliases: ['kapusta zasmażana', 'kapusta z boczkiem'], storagePath: 'dania/dinners/dinner_19.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_19.webp') },
  { slug: 'mizeria_obiad', category: 'kuchnia_polska', labelPl: 'Mizeria z ogórków', aliases: ['mizeria', 'mizeria z ogórków'], storagePath: 'dania/dinners/dinner_20.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_20.webp') },
  { slug: 'pstrag_pieczony', category: 'kuchnia_polska', labelPl: 'Pstrąg pieczony', aliases: ['pstrąg', 'pstrąg pieczony', 'trout'], storagePath: 'dania/dinners/dinner_21.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_21.webp') },
  { slug: 'karkowka_pieczona', category: 'kuchnia_polska', labelPl: 'Karkówka pieczona', aliases: ['karkówka', 'karkówka pieczona', 'karkowka'], storagePath: 'dania/dinners/dinner_22.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_22.webp') },
  { slug: 'gulasz_grzybowy', category: 'kuchnia_polska', labelPl: 'Gulasz z leśnych grzybów', aliases: ['gulasz grzybowy', 'gulasz z grzybów', 'leśne grzyby'], storagePath: 'dania/dinners/dinner_23.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_23.webp') },
  { slug: 'pieczen_rzymska', category: 'kuchnia_polska', labelPl: 'Pieczeń rzymska', aliases: ['pieczeń rzymska', 'pieczen rzymska', 'klops mięsny'], storagePath: 'dania/dinners/dinner_24.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_24.webp') },
  { slug: 'chlodnik_litewski', category: 'kuchnia_polska', labelPl: 'Chłodnik litewski', aliases: ['chłodnik', 'chłodnik litewski', 'chlodnik'], storagePath: 'dania/dinners/dinner_25.webp', localAsset: require('@/assets/premium/dishes/dinners/dinner_25.webp') },
];
