/**
 * Katalog grafik — klasyczne zupy polskie (plansza 46, 5×5).
 * Osobny folder `soups_polish` — nie nadpisuje starszego `soups_pl`.
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const SOUPS_POLISH_CATALOG: DishImageEntry[] = [
  { slug: 'zupa_ogorkowa_pl', category: 'kuchnia_polska', labelPl: 'Zupa ogórkowa', aliases: ['ogórkowa', 'pickle soup', 'zupa z ogórków kiszonych', 'dill pickle soup'], storagePath: 'dania/soups_polish/soup_pl_classic_01.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_01.webp') },
  { slug: 'krupnik_staropolski', category: 'kuchnia_polska', labelPl: 'Krupnik staropolski', aliases: ['krupnik', 'barley soup', 'zupa z kaszą jęczmienną'], storagePath: 'dania/soups_polish/soup_pl_classic_02.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_02.webp') },
  { slug: 'zupa_szczawiowa', category: 'kuchnia_polska', labelPl: 'Zupa szczawiowa', aliases: ['szczawiowa', 'sorrel soup', 'zupa ze szczawiu'], storagePath: 'dania/soups_polish/soup_pl_classic_03.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_03.webp') },
  { slug: 'zupa_gulaszowa_pikantna', category: 'kuchnia_polska', labelPl: 'Zupa gulaszowa pikantna', aliases: ['gulaszowa', 'goulash soup', 'pikantna gulaszowa'], storagePath: 'dania/soups_polish/soup_pl_classic_04.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_04.webp') },
  { slug: 'zupa_ogonowa', category: 'kuchnia_polska', labelPl: 'Zupa ogonowa', aliases: ['ogonowa', 'oxtail soup', 'zupa na ogonach'], storagePath: 'dania/soups_polish/soup_pl_classic_05.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_05.webp') },
  { slug: 'barszcz_czerwony_uszka', category: 'kuchnia_polska', labelPl: 'Barszcz czerwony z uszkami', aliases: ['barszcz czerwony', 'barszcz z uszkami', 'red borscht', 'uszka'], storagePath: 'dania/soups_polish/soup_pl_classic_06.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_06.webp') },
  { slug: 'barszcz_ukrainski_classic', category: 'kuchnia_polska', labelPl: 'Barszcz ukraiński', aliases: ['barszcz ukraiński', 'ukraiński', 'ukrainian borscht'], storagePath: 'dania/soups_polish/soup_pl_classic_07.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_07.webp') },
  { slug: 'zurek_staropolski', category: 'kuchnia_polska', labelPl: 'Żurek staropolski', aliases: ['żurek', 'zurek staropolski', 'żurek z kiełbasą'], storagePath: 'dania/soups_polish/soup_pl_classic_08.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_08.webp') },
  { slug: 'rosol_z_kury_tradycyjny', category: 'kuchnia_polska', labelPl: 'Tradycyjny rosół z kury', aliases: ['rosół z kury', 'rosół tradycyjny', 'chicken broth', 'rosol z makaronem'], storagePath: 'dania/soups_polish/soup_pl_classic_09.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_09.webp') },
  { slug: 'zupa_grzybowa_borowiki', category: 'kuchnia_polska', labelPl: 'Zupa grzybowa z leśnych borowików', aliases: ['zupa grzybowa', 'borowiki', 'porcini soup', 'zupa z borowików'], storagePath: 'dania/soups_polish/soup_pl_classic_10.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_10.webp') },
  { slug: 'kapusniak_mloda_kapusta', category: 'kuchnia_polska', labelPl: 'Kapuśniak z młodej kapusty', aliases: ['kapuśniak', 'cabbage soup', 'kapusniak'], storagePath: 'dania/soups_polish/soup_pl_classic_11.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_11.webp') },
  { slug: 'flaki_wolowe', category: 'kuchnia_polska', labelPl: 'Flaki wołowe', aliases: ['flaki', 'flaczki', 'tripe soup', 'flaki wołowe'], storagePath: 'dania/soups_polish/soup_pl_classic_12.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_12.webp') },
  { slug: 'grochowka_wojskowa', category: 'kuchnia_polska', labelPl: 'Grochówka wojskowa', aliases: ['grochówka', 'pea soup', 'grochowka', 'grochówka z żeberkiem'], storagePath: 'dania/soups_polish/soup_pl_classic_13.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_13.webp') },
  { slug: 'zupa_kalarepa', category: 'kuchnia_polska', labelPl: 'Zupa z kalarepy', aliases: ['kalarepa', 'kohlrabi soup', 'zupa kalarepowa'], storagePath: 'dania/soups_polish/soup_pl_classic_14.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_14.webp') },
  { slug: 'krem_dyni_classic', category: 'kuchnia_polska', labelPl: 'Krem z dyni', aliases: ['krem dyniowy', 'pumpkin soup', 'zupa dyniowa'], storagePath: 'dania/soups_polish/soup_pl_classic_15.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_15.webp') },
  { slug: 'zupa_pomidorowa_ryz', category: 'kuchnia_polska', labelPl: 'Zupa pomidorowa z ryżem', aliases: ['pomidorowa z ryżem', 'tomato rice soup', 'pomidorowa'], storagePath: 'dania/soups_polish/soup_pl_classic_16.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_16.webp') },
  { slug: 'barszcz_bialy_chrzan', category: 'kuchnia_polska', labelPl: 'Barszcz biały z chrzanem', aliases: ['barszcz biały', 'white borscht', 'barszcz z chrzanem'], storagePath: 'dania/soups_polish/soup_pl_classic_17.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_17.webp') },
  { slug: 'zupa_ziemniaczano_porowa', category: 'kuchnia_polska', labelPl: 'Zupa ziemniaczano-porowa', aliases: ['ziemniaczano-porowa', 'leek potato soup', 'zupa porowa'], storagePath: 'dania/soups_polish/soup_pl_classic_18.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_18.webp') },
  { slug: 'chlodnik_litewski_classic', category: 'kuchnia_polska', labelPl: 'Chłodnik litewski', aliases: ['chłodnik', 'chlodnik litewski', 'cold beet soup', 'botwinka'], storagePath: 'dania/soups_polish/soup_pl_classic_19.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_19.webp') },
  { slug: 'krem_z_kurek', category: 'kuchnia_polska', labelPl: 'Zupa krem z kurek', aliases: ['krem z kurek', 'chanterelle cream', 'zupa z kurek', 'kurki krem'], storagePath: 'dania/soups_polish/soup_pl_classic_20.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_20.webp') },
  { slug: 'zupa_fasolowa_classic', category: 'kuchnia_polska', labelPl: 'Zupa fasolowa', aliases: ['fasolowa', 'bean soup', 'zupa z fasoli'], storagePath: 'dania/soups_polish/soup_pl_classic_21.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_21.webp') },
  { slug: 'zupa_rybna_polska', category: 'kuchnia_polska', labelPl: 'Polska zupa rybna', aliases: ['zupa rybna', 'fish soup', 'rybna polska'], storagePath: 'dania/soups_polish/soup_pl_classic_22.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_22.webp') },
  { slug: 'zupa_pokrzywa', category: 'kuchnia_polska', labelPl: 'Zupa z pokrzywy', aliases: ['pokrzywa', 'nettle soup', 'zupa pokrzywowa'], storagePath: 'dania/soups_polish/soup_pl_classic_23.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_23.webp') },
  { slug: 'zupa_owocowa_makaron', category: 'kuchnia_polska', labelPl: 'Zupa owocowa z makaronem', aliases: ['zupa owocowa', 'fruit soup', 'owocowa z kluseczkami'], storagePath: 'dania/soups_polish/soup_pl_classic_24.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_24.webp') },
  { slug: 'miseczka_grzanki', category: 'kuchnia_polska', labelPl: 'Miseczka z chrupiącymi grzankami chlebowymi', aliases: ['grzanki', 'croutons', 'miseczka z grzankami', 'chrupiące grzanki'], storagePath: 'dania/soups_polish/soup_pl_classic_25.webp', localAsset: require('@/assets/premium/dishes/soups_polish/soup_pl_classic_25.webp'), recipeEligible: false },
];
