/**
 * Katalog grafik dań — przystawki (plansza 51) + sałatki (plansze 5×5, lokalne WebP).
 */
type DishImageEntry = {
  slug: string;
  category: 'kuchnia_polska';
  labelPl: string;
  aliases: string[];
  storagePath: string;
  localAsset: number;
  recipeEligible?: boolean;
};

export const STARTERS_CATALOG: DishImageEntry[] = [
  { slug: 'carpaccio_wolowe', category: 'kuchnia_polska', labelPl: 'Carpaccio wołowe', aliases: ['carpaccio', 'carpaccio wołowe', 'beef carpaccio'], storagePath: 'dania/starters/starter_01.webp', localAsset: require('@/assets/premium/dishes/starters/starter_01.webp') },
  { slug: 'tatar_wolowy_premium', category: 'kuchnia_polska', labelPl: 'Tatar wołowy premium', aliases: ['tatar', 'tatar wołowy', 'beef tartare', 'tatar premium'], storagePath: 'dania/starters/starter_02.webp', localAsset: require('@/assets/premium/dishes/starters/starter_02.webp') },
  { slug: 'swieza_ostryga', category: 'kuchnia_polska', labelPl: 'Świeża ostryga', aliases: ['ostryga', 'oysters', 'świeża ostryga', 'ostrygi'], storagePath: 'dania/starters/starter_03.webp', localAsset: require('@/assets/premium/dishes/starters/starter_03.webp') },
  { slug: 'przegrzebek_sw_jakuba', category: 'kuchnia_polska', labelPl: 'Przegrzebek (małża św. Jakuba)', aliases: ['przegrzebek', 'scallops', 'małża św. Jakuba', 'pan-seared scallops'], storagePath: 'dania/starters/starter_04.webp', localAsset: require('@/assets/premium/dishes/starters/starter_04.webp') },
  { slug: 'tartaletka_losos_kawior', category: 'kuchnia_polska', labelPl: 'Mini-tartaletka z łososiem i kawiorem', aliases: ['tartaletka z łososiem', 'caviar tartlet', 'mini tartaletka kawior', 'łosoś kawior'], storagePath: 'dania/starters/starter_05.webp', localAsset: require('@/assets/premium/dishes/starters/starter_05.webp') },
  { slug: 'szaszlyk_krewetka_tygrysia', category: 'kuchnia_polska', labelPl: 'Szaszłyk z krewetki tygrysiej', aliases: ['szaszłyk krewetka', 'krewetka tygrysia', 'tiger prawn skewer', 'krewetki grill'], storagePath: 'dania/starters/starter_06.webp', localAsset: require('@/assets/premium/dishes/starters/starter_06.webp') },
  { slug: 'tataki_tunczyka', category: 'kuchnia_polska', labelPl: 'Tataki z tuńczyka', aliases: ['tataki', 'tuna tataki', 'tuńczyk tataki'], storagePath: 'dania/starters/starter_07.webp', localAsset: require('@/assets/premium/dishes/starters/starter_07.webp') },
  { slug: 'pieczony_ser_brie', category: 'kuchnia_polska', labelPl: 'Pieczony ser brie', aliases: ['pieczony brie', 'baked brie', 'brie z miodem', 'camembert pieczony'], storagePath: 'dania/starters/starter_08.webp', localAsset: require('@/assets/premium/dishes/starters/starter_08.webp') },
  { slug: 'sajgonka_kaczka', category: 'kuchnia_polska', labelPl: 'Chrupiąca sajgonka z kaczką', aliases: ['sajgonka z kaczką', 'duck spring roll', 'sajgonki kaczka'], storagePath: 'dania/starters/starter_09.webp', localAsset: require('@/assets/premium/dishes/starters/starter_09.webp') },
  { slug: 'koreczek_parmenska_melon', category: 'kuchnia_polska', labelPl: 'Koreczek z szynki parmeńskiej i melona', aliases: ['szynka parmeńska melon', 'prosciutto melon', 'koreczek melon', 'prosciutto e melone'], storagePath: 'dania/starters/starter_10.webp', localAsset: require('@/assets/premium/dishes/starters/starter_10.webp') },
  { slug: 'crostini_figa_kozi', category: 'kuchnia_polska', labelPl: 'Crostini z figą i serem kozim', aliases: ['crostini figa', 'fig goat cheese', 'crostini kozi ser'], storagePath: 'dania/starters/starter_11.webp', localAsset: require('@/assets/premium/dishes/starters/starter_11.webp') },
  { slug: 'mini_lobster_roll', category: 'kuchnia_polska', labelPl: 'Mini Lobster Roll', aliases: ['lobster roll', 'mini lobster', 'bułeczka z homarem'], storagePath: 'dania/starters/starter_12.webp', localAsset: require('@/assets/premium/dishes/starters/starter_12.webp') },
  { slug: 'kostka_sera_trufla', category: 'kuchnia_polska', labelPl: 'Kostka sera z truflą', aliases: ['ser z truflą', 'truffle cheese', 'kostka sera trufla'], storagePath: 'dania/starters/starter_13.webp', localAsset: require('@/assets/premium/dishes/starters/starter_13.webp') },
  { slug: 'arancini_szafran', category: 'kuchnia_polska', labelPl: 'Arancini z szafranem', aliases: ['arancini', 'arancini szafran', 'kulki ryżowe'], storagePath: 'dania/starters/starter_14.webp', localAsset: require('@/assets/premium/dishes/starters/starter_14.webp') },
  { slug: 'roladka_bresaola', category: 'kuchnia_polska', labelPl: 'Roladka z bresaoli z serkiem', aliases: ['bresaola', 'roladka bresaola', 'bresaola roulade'], storagePath: 'dania/starters/starter_15.webp', localAsset: require('@/assets/premium/dishes/starters/starter_15.webp') },
  { slug: 'kotlecik_krabowy', category: 'kuchnia_polska', labelPl: 'Kotlecik krabowy (Crab Cake)', aliases: ['crab cake', 'kotlecik krabowy', 'crab cakes'], storagePath: 'dania/starters/starter_16.webp', localAsset: require('@/assets/premium/dishes/starters/starter_16.webp') },
  { slug: 'slimak_burgundzki', category: 'kuchnia_polska', labelPl: 'Ślimak po burgundzku', aliases: ['ślimak burgundzki', 'escargot', 'ślimaki po burgundzku'], storagePath: 'dania/starters/starter_17.webp', localAsset: require('@/assets/premium/dishes/starters/starter_17.webp') },
  { slug: 'pieczarka_faszerowana', category: 'kuchnia_polska', labelPl: 'Pieczona pieczarka faszerowana', aliases: ['pieczarka faszerowana', 'stuffed mushroom', 'faszerowany grzyb'], storagePath: 'dania/starters/starter_18.webp', localAsset: require('@/assets/premium/dishes/starters/starter_18.webp') },
  { slug: 'mini_szaszlyk_caprese', category: 'kuchnia_polska', labelPl: 'Mini-szaszłyk Caprese', aliases: ['caprese', 'szaszłyki caprese', 'mini caprese', 'caprese skewers'], storagePath: 'dania/starters/starter_19.webp', localAsset: require('@/assets/premium/dishes/starters/starter_19.webp') },
  { slug: 'roza_losos_sashimi', category: 'kuchnia_polska', labelPl: 'Róża z łososia sashimi', aliases: ['róża z łososia', 'salmon rose', 'sashimi łosoś', 'łosoś sashimi'], storagePath: 'dania/starters/starter_20.webp', localAsset: require('@/assets/premium/dishes/starters/starter_20.webp') },
  { slug: 'boczek_glazura_klonowa', category: 'kuchnia_polska', labelPl: 'Chrupiący boczek w glazurze klonowej', aliases: ['boczek glazura', 'maple glazed bacon', 'chrupiący boczek', 'pork belly maple'], storagePath: 'dania/starters/starter_21.webp', localAsset: require('@/assets/premium/dishes/starters/starter_21.webp') },
  { slug: 'vitello_tonnato', category: 'kuchnia_polska', labelPl: 'Vitello Tonnato', aliases: ['vitello tonnato', 'cielęcina tuńczyk'], storagePath: 'dania/starters/starter_22.webp', localAsset: require('@/assets/premium/dishes/starters/starter_22.webp') },
  { slug: 'tatar_mango_awokado', category: 'kuchnia_polska', labelPl: 'Tatar z mango i awokado', aliases: ['tatar mango', 'mango avocado tartare', 'tatar awokado'], storagePath: 'dania/starters/starter_23.webp', localAsset: require('@/assets/premium/dishes/starters/starter_23.webp') },
  { slug: 'pasztet_gesie_watrobki', category: 'kuchnia_polska', labelPl: 'Pasztet z gęsich wątróbek (Pâté) na brioche', aliases: ['pasztet gęsi', 'pâté', 'foie gras pate', 'pasztet wątróbki', 'pate brioche'], storagePath: 'dania/starters/starter_24.webp', localAsset: require('@/assets/premium/dishes/starters/starter_24.webp') },
  { slug: 'miks_oliwek_premium', category: 'kuchnia_polska', labelPl: 'Miks oliwek premium', aliases: ['miks oliwek', 'oliwki', 'premium olives', 'marynowane oliwki'], storagePath: 'dania/starters/starter_25.webp', localAsset: require('@/assets/premium/dishes/starters/starter_25.webp'), recipeEligible: false },
];

export const SALADS_CATALOG: DishImageEntry[] = [
  { slug: 'caesar_chicken', category: 'kuchnia_polska', labelPl: 'Sałatka Cezar z kurczakiem', aliases: ['cezar', 'caesar', 'sałatka cezar', 'caesar salad'], storagePath: 'dania/salads/salad_01.webp', localAsset: require('@/assets/premium/dishes/salads/salad_01.webp') },
  { slug: 'greek_salad', category: 'kuchnia_polska', labelPl: 'Sałatka grecka', aliases: ['grecka', 'greek salad', 'sałatka grecka', 'feta oliwki'], storagePath: 'dania/salads/salad_02.webp', localAsset: require('@/assets/premium/dishes/salads/salad_02.webp') },
  { slug: 'goat_cheese_walnut', category: 'kuchnia_polska', labelPl: 'Sałatka z kozim serem', aliases: ['kozi ser', 'goat cheese salad', 'sałatka kozi'], storagePath: 'dania/salads/salad_03.webp', localAsset: require('@/assets/premium/dishes/salads/salad_03.webp') },
  { slug: 'nicoise', category: 'kuchnia_polska', labelPl: 'Sałatka Niçoise', aliases: ['nicoise', 'niçoise', 'sałatka nicoise', 'tuńczyk sałatka'], storagePath: 'dania/salads/salad_04.webp', localAsset: require('@/assets/premium/dishes/salads/salad_04.webp') },
  { slug: 'duck_pomegranate', category: 'kuchnia_polska', labelPl: 'Sałatka z kaczką i granatem', aliases: ['sałatka kaczka', 'duck salad', 'granat sałatka'], storagePath: 'dania/salads/salad_05.webp', localAsset: require('@/assets/premium/dishes/salads/salad_05.webp') },
  { slug: 'quinoa_avocado', category: 'kuchnia_polska', labelPl: 'Sałatka z quinoa i awokado', aliases: ['quinoa', 'komosa', 'sałatka quinoa', 'edamame sałatka'], storagePath: 'dania/salads/salad_06.webp', localAsset: require('@/assets/premium/dishes/salads/salad_06.webp') },
  { slug: 'waldorf', category: 'kuchnia_polska', labelPl: 'Sałatka Waldorf', aliases: ['waldorf', 'sałatka waldorf'], storagePath: 'dania/salads/salad_07.webp', localAsset: require('@/assets/premium/dishes/salads/salad_07.webp') },
  { slug: 'caprese_salad', category: 'kuchnia_polska', labelPl: 'Sałatka Caprese', aliases: ['caprese sałatka', 'sałatka caprese', 'caprese salad'], storagePath: 'dania/salads/salad_08.webp', localAsset: require('@/assets/premium/dishes/salads/salad_08.webp') },
  { slug: 'beet_feta', category: 'kuchnia_polska', labelPl: 'Sałatka z burakiem i fetą', aliases: ['burak feta', 'beet salad', 'sałatka burak'], storagePath: 'dania/salads/salad_09.webp', localAsset: require('@/assets/premium/dishes/salads/salad_09.webp') },
  { slug: 'asian_chicken_sesame', category: 'kuchnia_polska', labelPl: 'Sałatka azjatycka z kurczakiem', aliases: ['azjatycka', 'sesame chicken salad', 'sałatka sezam'], storagePath: 'dania/salads/salad_10.webp', localAsset: require('@/assets/premium/dishes/salads/salad_10.webp') },
  { slug: 'cobb_salad', category: 'kuchnia_polska', labelPl: 'Sałatka Cobb', aliases: ['cobb', 'sałatka cobb', 'cobb salad'], storagePath: 'dania/salads/salad_11.webp', localAsset: require('@/assets/premium/dishes/salads/salad_11.webp') },
  { slug: 'taco_salad', category: 'kuchnia_polska', labelPl: 'Sałatka Taco', aliases: ['taco salad', 'sałatka taco', 'miska tortilla'], storagePath: 'dania/salads/salad_12.webp', localAsset: require('@/assets/premium/dishes/salads/salad_12.webp') },
  { slug: 'mediterranean_couscous', category: 'kuchnia_polska', labelPl: 'Sałatka kuskus śródziemnomorska', aliases: ['kuskus', 'couscous salad', 'sałatka kuskus'], storagePath: 'dania/salads/salad_13.webp', localAsset: require('@/assets/premium/dishes/salads/salad_13.webp') },
  { slug: 'pear_gorgonzola', category: 'kuchnia_polska', labelPl: 'Sałatka z gruszką i gorgonzolą', aliases: ['gruszka gorgonzola', 'pear gorgonzola', 'sałatka gruszka'], storagePath: 'dania/salads/salad_14.webp', localAsset: require('@/assets/premium/dishes/salads/salad_14.webp') },
  { slug: 'shrimp_avocado_salad', category: 'kuchnia_polska', labelPl: 'Sałatka z krewetkami i awokado', aliases: ['krewetki awokado', 'shrimp avocado salad', 'sałatka krewetki'], storagePath: 'dania/salads/salad_15.webp', localAsset: require('@/assets/premium/dishes/salads/salad_15.webp') },
  { slug: 'tex_mex_salad', category: 'kuchnia_polska', labelPl: 'Sałatka Tex-Mex', aliases: ['tex-mex', 'tex mex', 'sałatka fasola kukurydza'], storagePath: 'dania/salads/salad_16.webp', localAsset: require('@/assets/premium/dishes/salads/salad_16.webp') },
  { slug: 'pumpkin_quinoa', category: 'kuchnia_polska', labelPl: 'Sałatka z dynią i quinoa', aliases: ['dynia quinoa', 'pumpkin salad', 'sałatka dynia'], storagePath: 'dania/salads/salad_17.webp', localAsset: require('@/assets/premium/dishes/salads/salad_17.webp') },
  { slug: 'smoked_salmon_asparagus', category: 'kuchnia_polska', labelPl: 'Sałatka z wędzonym łososiem', aliases: ['łosoś wędzony sałatka', 'smoked salmon salad', 'szparagi sałatka'], storagePath: 'dania/salads/salad_18.webp', localAsset: require('@/assets/premium/dishes/salads/salad_18.webp') },
  { slug: 'thai_beef_salad', category: 'kuchnia_polska', labelPl: 'Ostra tajska sałatka z wołowiną', aliases: ['tajska', 'thai beef', 'sałatka wołowina limonka'], storagePath: 'dania/salads/salad_19.webp', localAsset: require('@/assets/premium/dishes/salads/salad_19.webp') },
  { slug: 'creamy_fruit_veg', category: 'kuchnia_polska', labelPl: 'Kremowa sałatka owocowo-warzywna', aliases: ['kremowa sałatka', 'sałatka majonezowa', 'owocowo-warzywna'], storagePath: 'dania/salads/salad_20.webp', localAsset: require('@/assets/premium/dishes/salads/salad_20.webp') },
  { slug: 'waldorf_light', category: 'kuchnia_polska', labelPl: 'Sałatka Waldorf jasna', aliases: ['waldorf jasna', 'light waldorf'], storagePath: 'dania/salads/salad_21.webp', localAsset: require('@/assets/premium/dishes/salads/salad_21.webp') },
  { slug: 'lentil_tomato_feta', category: 'kuchnia_polska', labelPl: 'Sałatka z soczewicy', aliases: ['soczewica sałatka', 'lentil salad', 'sałatka soczewica'], storagePath: 'dania/salads/salad_22.webp', localAsset: require('@/assets/premium/dishes/salads/salad_22.webp') },
  { slug: 'buddha_bowl', category: 'kuchnia_polska', labelPl: 'Buddha bowl z tofu', aliases: ['buddha bowl', 'buddha', 'tofu awokado bowl'], storagePath: 'dania/salads/salad_23.webp', localAsset: require('@/assets/premium/dishes/salads/salad_23.webp') },
  { slug: 'spinach_strawberry', category: 'kuchnia_polska', labelPl: 'Sałatka ze szpinakiem i truskawkami', aliases: ['szpinak truskawki', 'spinach strawberry', 'sałatka truskawki'], storagePath: 'dania/salads/salad_24.webp', localAsset: require('@/assets/premium/dishes/salads/salad_24.webp') },
  { slug: 'garden_salad', category: 'kuchnia_polska', labelPl: 'Klasyczna sałatka ogrodowa', aliases: ['ogrodowa', 'garden salad', 'sałatka mieszana', 'sałatka', 'salatka'], storagePath: 'dania/salads/salad_25.webp', localAsset: require('@/assets/premium/dishes/salads/salad_25.webp') },
];
