/**
 * Katalog grafik — herbaty i napary (plansza 5×5, rządami L→P).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const TEAS_CATALOG: DishImageEntry[] = [
  { slug: 'herbata_zimowa_pomarancza', category: 'kuchnia_polska', labelPl: 'Herbata zimowa z pomarańczą', aliases: ['herbata zimowa', 'herbata z pomarańczą', 'zimowa z goździkami', 'winter tea'], storagePath: 'dania/teas/tea_01.webp', localAsset: require('@/assets/premium/dishes/teas/tea_01.webp') },
  { slug: 'zielona_herbata_czajniczek', category: 'kuchnia_polska', labelPl: 'Zielona herbata w czajniczku', aliases: ['zielona herbata', 'green tea', 'herbata zielona', 'imbryk zielona'], storagePath: 'dania/teas/tea_02.webp', localAsset: require('@/assets/premium/dishes/teas/tea_02.webp') },
  { slug: 'matcha_latte', category: 'kuchnia_polska', labelPl: 'Matcha Latte z latte art', aliases: ['matcha latte', 'matcha', 'latte matcha'], storagePath: 'dania/teas/tea_03.webp', localAsset: require('@/assets/premium/dishes/teas/tea_03.webp') },
  { slug: 'napar_rumianek', category: 'kuchnia_polska', labelPl: 'Napar z rumianku', aliases: ['rumianek', 'herbata rumiankowa', 'chamomile', 'napar rumiankowy'], storagePath: 'dania/teas/tea_04.webp', localAsset: require('@/assets/premium/dishes/teas/tea_04.webp') },
  { slug: 'earl_grey_cytryna', category: 'kuchnia_polska', labelPl: 'Herbata Earl Grey z cytryną', aliases: ['earl grey', 'herbata earl grey', 'earl grey z cytryną'], storagePath: 'dania/teas/tea_05.webp', localAsset: require('@/assets/premium/dishes/teas/tea_05.webp') },
  { slug: 'hibiskus_karkade', category: 'kuchnia_polska', labelPl: 'Herbata z hibiskusa (Karkade)', aliases: ['hibiskus', 'karkade', 'herbata hibiskus', 'malwa'], storagePath: 'dania/teas/tea_06.webp', localAsset: require('@/assets/premium/dishes/teas/tea_06.webp') },
  { slug: 'marokanska_mieta', category: 'kuchnia_polska', labelPl: 'Tradycyjna marokańska herbata miętowa', aliases: ['herbata marokańska', 'marokańska miętowa', 'mint tea', 'herbata miętowa marokańska'], storagePath: 'dania/teas/tea_07.webp', localAsset: require('@/assets/premium/dishes/teas/tea_07.webp') },
  { slug: 'chai_latte_cynamon', category: 'kuchnia_polska', labelPl: 'Chai Latte z cynamonem', aliases: ['chai latte', 'chai', 'masala chai latte', 'herbata chai'], storagePath: 'dania/teas/tea_08.webp', localAsset: require('@/assets/premium/dishes/teas/tea_08.webp') },
  { slug: 'matcha_chasen', category: 'kuchnia_polska', labelPl: 'Miska do matchy z bambusową trzepaczką (Chasen)', aliases: ['matcha chasen', 'ceremonia matcha', 'miska matcha', 'chasen'], storagePath: 'dania/teas/tea_09.webp', localAsset: require('@/assets/premium/dishes/teas/tea_09.webp') },
  { slug: 'iced_tea_brzoskwinia', category: 'kuchnia_polska', labelPl: 'Mrożona herbata brzoskwiniowa (Iced Tea)', aliases: ['iced tea', 'mrożona herbata', 'herbata brzoskwiniowa', 'peach iced tea'], storagePath: 'dania/teas/tea_10.webp', localAsset: require('@/assets/premium/dishes/teas/tea_10.webp') },
  { slug: 'yerba_mate', category: 'kuchnia_polska', labelPl: 'Yerba Mate w tykwie (Matera)', aliases: ['yerba mate', 'mate', 'matera', 'bombilla'], storagePath: 'dania/teas/tea_11.webp', localAsset: require('@/assets/premium/dishes/teas/tea_11.webp') },
  { slug: 'napar_lawendowy', category: 'kuchnia_polska', labelPl: 'Napar lawendowy', aliases: ['lawenda', 'herbata lawendowa', 'lavender tea', 'napar z lawendy'], storagePath: 'dania/teas/tea_12.webp', localAsset: require('@/assets/premium/dishes/teas/tea_12.webp') },
  { slug: 'rooibos', category: 'kuchnia_polska', labelPl: 'Herbata Rooibos', aliases: ['rooibos', 'czerwonokrzew', 'herbata rooibos'], storagePath: 'dania/teas/tea_13.webp', localAsset: require('@/assets/premium/dishes/teas/tea_13.webp') },
  { slug: 'blooming_tea', category: 'kuchnia_polska', labelPl: 'Herbata kwitnąca (Blooming tea)', aliases: ['blooming tea', 'herbata kwitnąca', 'kwitnąca herbata', 'jaśmin blooming'], storagePath: 'dania/teas/tea_14.webp', localAsset: require('@/assets/premium/dishes/teas/tea_14.webp') },
  { slug: 'imbir_cytryna', category: 'kuchnia_polska', labelPl: 'Napar imbirowo-cytrynowy', aliases: ['imbir cytryna', 'herbata imbirowa', 'ginger lemon', 'napar imbirowy'], storagePath: 'dania/teas/tea_15.webp', localAsset: require('@/assets/premium/dishes/teas/tea_15.webp') },
  { slug: 'owoce_lesne', category: 'kuchnia_polska', labelPl: 'Napar z owoców leśnych', aliases: ['owoce leśne', 'herbata owocowa', 'forest berries', 'maliny borówki'], storagePath: 'dania/teas/tea_16.webp', localAsset: require('@/assets/premium/dishes/teas/tea_16.webp') },
  { slug: 'oolong', category: 'kuchnia_polska', labelPl: 'Herbata Oolong (Ulong)', aliases: ['oolong', 'ulong', 'herbata oolong', 'wulong'], storagePath: 'dania/teas/tea_17.webp', localAsset: require('@/assets/premium/dishes/teas/tea_17.webp') },
  { slug: 'masala_chai_glina', category: 'kuchnia_polska', labelPl: 'Masala Chai w glinianym kubku', aliases: ['masala chai', 'chai gliniany', 'indyjska herbata', 'chai'], storagePath: 'dania/teas/tea_18.webp', localAsset: require('@/assets/premium/dishes/teas/tea_18.webp') },
  { slug: 'iced_matcha_tonic', category: 'kuchnia_polska', labelPl: 'Iced Matcha Tonic', aliases: ['iced matcha', 'matcha tonic', 'mrożona matcha'], storagePath: 'dania/teas/tea_19.webp', localAsset: require('@/assets/premium/dishes/teas/tea_19.webp') },
  { slug: 'herbata_platki_roz', category: 'kuchnia_polska', labelPl: 'Herbata z płatkami róż', aliases: ['herbata różana', 'płatki róż', 'rose tea', 'herbata z różą'], storagePath: 'dania/teas/tea_20.webp', localAsset: require('@/assets/premium/dishes/teas/tea_20.webp') },
  { slug: 'mieta_pieprzowa', category: 'kuchnia_polska', labelPl: 'Napar ze świeżej mięty pieprzowej', aliases: ['mięta pieprzowa', 'napar miętowy', 'fresh mint', 'herbata miętowa'], storagePath: 'dania/teas/tea_21.webp', localAsset: require('@/assets/premium/dishes/teas/tea_21.webp') },
  { slug: 'trawa_cytrynowa_imbir', category: 'kuchnia_polska', labelPl: 'Herbata z trawy cytrynowej i imbiru', aliases: ['trawa cytrynowa', 'lemongrass', 'herbata lemongrass', 'cytrusowy napar'], storagePath: 'dania/teas/tea_22.webp', localAsset: require('@/assets/premium/dishes/teas/tea_22.webp') },
  { slug: 'zlote_mleko', category: 'kuchnia_polska', labelPl: 'Złote mleko (Turmeric Latte)', aliases: ['złote mleko', 'turmeric latte', 'golden milk', 'kurkuma latte'], storagePath: 'dania/teas/tea_23.webp', localAsset: require('@/assets/premium/dishes/teas/tea_23.webp') },
  { slug: 'bawarka', category: 'kuchnia_polska', labelPl: 'Klasyczna herbata z mlekiem (Bawarka)', aliases: ['bawarka', 'herbata z mlekiem', 'tea with milk', 'czarna z mlekiem'], storagePath: 'dania/teas/tea_24.webp', localAsset: require('@/assets/premium/dishes/teas/tea_24.webp') },
  { slug: 'miod_do_herbaty', category: 'kuchnia_polska', labelPl: 'Miseczka z miodem i czerpakiem', aliases: ['miód', 'honey', 'miód do herbaty'], storagePath: 'dania/teas/tea_25.webp', localAsset: require('@/assets/premium/dishes/teas/tea_25.webp'), recipeEligible: false },
];
