/**
 * Katalog grafik — wina i akcesoria (plansza 5×5).
 */
import type { DishImageEntry } from '@/lib/dishImagesCatalog';

export const WINES_CATALOG: DishImageEntry[] = [
  { slug: 'wino_czerwone_bordeaux', category: 'kuchnia_polska', labelPl: 'Wino czerwone wytrawne (Bordeaux)', aliases: ['wino czerwone', 'czerwone wytrawne', 'bordeaux', 'red wine'], storagePath: 'dania/wines/wine_01.webp', localAsset: require('@/assets/premium/dishes/wines/wine_01.webp') },
  { slug: 'wino_biale_wytrawne', category: 'kuchnia_polska', labelPl: 'Wino białe wytrawne', aliases: ['wino białe', 'białe wytrawne', 'white wine'], storagePath: 'dania/wines/wine_02.webp', localAsset: require('@/assets/premium/dishes/wines/wine_02.webp') },
  { slug: 'wino_rozowe', category: 'kuchnia_polska', labelPl: 'Wino różowe (Rosé)', aliases: ['wino różowe', 'rosé', 'rose', 'różowe'], storagePath: 'dania/wines/wine_03.webp', localAsset: require('@/assets/premium/dishes/wines/wine_03.webp') },
  { slug: 'szampan_flute', category: 'kuchnia_polska', labelPl: 'Szampan / Wino musujące (flute)', aliases: ['szampan', 'champagne', 'wino musujące', 'sparkling'], storagePath: 'dania/wines/wine_04.webp', localAsset: require('@/assets/premium/dishes/wines/wine_04.webp') },
  { slug: 'prosecco_lemon_twist', category: 'kuchnia_polska', labelPl: 'Prosecco / Cava z lemon twist', aliases: ['prosecco', 'cava', 'prosecco lemon'], storagePath: 'dania/wines/wine_05.webp', localAsset: require('@/assets/premium/dishes/wines/wine_05.webp') },
  { slug: 'wino_deserowe', category: 'kuchnia_polska', labelPl: 'Słodkie wino deserowe', aliases: ['wino deserowe', 'dessert wine', 'słodkie wino'], storagePath: 'dania/wines/wine_06.webp', localAsset: require('@/assets/premium/dishes/wines/wine_06.webp') },
  { slug: 'butelka_czerwonego_wina', category: 'kuchnia_polska', labelPl: 'Butelka czerwonego wina', aliases: ['butelka czerwonego', 'butelka wina czerwonego'], storagePath: 'dania/wines/wine_07.webp', localAsset: require('@/assets/premium/dishes/wines/wine_07.webp') },
  { slug: 'butelka_bialego_wina', category: 'kuchnia_polska', labelPl: 'Butelka białego wina', aliases: ['butelka białego', 'chablis butelka', 'butelka wina białego'], storagePath: 'dania/wines/wine_08.webp', localAsset: require('@/assets/premium/dishes/wines/wine_08.webp') },
  { slug: 'dekantor', category: 'kuchnia_polska', labelPl: 'Szklana karafka (Dekanter)', aliases: ['dekantor', 'dekanter', 'karafka'], storagePath: 'dania/wines/wine_09.webp', localAsset: require('@/assets/premium/dishes/wines/wine_09.webp'), recipeEligible: false },
  { slug: 'mini_prosecco', category: 'kuchnia_polska', labelPl: 'Mini butelka szampana / prosecco 200 ml', aliases: ['mini prosecco', 'mini szampan', '200 ml'], storagePath: 'dania/wines/wine_10.webp', localAsset: require('@/assets/premium/dishes/wines/wine_10.webp') },
  { slug: 'schladzacz_gliniany', category: 'kuchnia_polska', labelPl: 'Gliniany schładzacz do wina', aliases: ['schładzacz', 'cooler wino', 'wine cooler'], storagePath: 'dania/wines/wine_11.webp', localAsset: require('@/assets/premium/dishes/wines/wine_11.webp'), recipeEligible: false },
  { slug: 'porto', category: 'kuchnia_polska', labelPl: 'Wino wzmacniane (Porto)', aliases: ['porto', 'port', 'wino wzmacniane'], storagePath: 'dania/wines/wine_12.webp', localAsset: require('@/assets/premium/dishes/wines/wine_12.webp') },
  { slug: 'orange_wine', category: 'kuchnia_polska', labelPl: 'Wino pomarańczowe (Orange wine)', aliases: ['orange wine', 'wino pomarańczowe', 'amber wine'], storagePath: 'dania/wines/wine_13.webp', localAsset: require('@/assets/premium/dishes/wines/wine_13.webp') },
  { slug: 'szampan_coupe', category: 'kuchnia_polska', labelPl: 'Szampan w kieliszku coupe', aliases: ['coupe', 'szampanka', 'champagne coupe'], storagePath: 'dania/wines/wine_14.webp', localAsset: require('@/assets/premium/dishes/wines/wine_14.webp') },
  { slug: 'stemless_red', category: 'kuchnia_polska', labelPl: 'Wino czerwone w szkle bez nóżki', aliases: ['stemless', 'szkło bez nóżki'], storagePath: 'dania/wines/wine_15.webp', localAsset: require('@/assets/premium/dishes/wines/wine_15.webp') },
  { slug: 'sangria', category: 'kuchnia_polska', labelPl: 'Sangria z cytrusami i cynamonem', aliases: ['sangria', 'sangría'], storagePath: 'dania/wines/wine_16.webp', localAsset: require('@/assets/premium/dishes/wines/wine_16.webp') },
  { slug: 'grzaniec', category: 'kuchnia_polska', labelPl: 'Grzane wino zimowe (Grzaniec)', aliases: ['grzaniec', 'grzane wino', 'mulled wine'], storagePath: 'dania/wines/wine_17.webp', localAsset: require('@/assets/premium/dishes/wines/wine_17.webp') },
  { slug: 'sherry', category: 'kuchnia_polska', labelPl: 'Sherry (copita)', aliases: ['sherry', 'jerez', 'copita'], storagePath: 'dania/wines/wine_18.webp', localAsset: require('@/assets/premium/dishes/wines/wine_18.webp') },
  { slug: 'vermut', category: 'kuchnia_polska', labelPl: 'Wytrawny Vermouth (Wermut)', aliases: ['vermut', 'vermouth', 'wermut'], storagePath: 'dania/wines/wine_19.webp', localAsset: require('@/assets/premium/dishes/wines/wine_19.webp') },
  { slug: 'chablis_sauvignon', category: 'kuchnia_polska', labelPl: 'Wino białe Chablis / Sauvignon Blanc', aliases: ['chablis', 'sauvignon blanc', 'sauvignon'], storagePath: 'dania/wines/wine_20.webp', localAsset: require('@/assets/premium/dishes/wines/wine_20.webp') },
  { slug: 'burgund', category: 'kuchnia_polska', labelPl: 'Wino czerwone typu Burgund', aliases: ['burgund', 'burgundy', 'pinot noir'], storagePath: 'dania/wines/wine_21.webp', localAsset: require('@/assets/premium/dishes/wines/wine_21.webp') },
  { slug: 'tinto_de_verano', category: 'kuchnia_polska', labelPl: 'Tinto de Verano', aliases: ['tinto de verano', 'tinto verano'], storagePath: 'dania/wines/wine_22.webp', localAsset: require('@/assets/premium/dishes/wines/wine_22.webp') },
  { slug: 'ice_bucket_szampan', category: 'kuchnia_polska', labelPl: 'Wiaderko z lodem (Ice bucket)', aliases: ['ice bucket', 'wiaderko z lodem', 'cooler bucket'], storagePath: 'dania/wines/wine_23.webp', localAsset: require('@/assets/premium/dishes/wines/wine_23.webp'), recipeEligible: false },
  { slug: 'korki_wina', category: 'kuchnia_polska', labelPl: 'Miseczka z korkami od wina', aliases: ['korki', 'wine corks'], storagePath: 'dania/wines/wine_24.webp', localAsset: require('@/assets/premium/dishes/wines/wine_24.webp'), recipeEligible: false },
  { slug: 'winogrona_zielone', category: 'kuchnia_polska', labelPl: 'Miseczka ze świeżymi winogronami', aliases: ['winogrona', 'green grapes'], storagePath: 'dania/wines/wine_25.webp', localAsset: require('@/assets/premium/dishes/wines/wine_25.webp'), recipeEligible: false },
];
