import { Platform, StyleSheet } from 'react-native';
import { CATALOG_SCAN_C as C } from './catalogScanColors';

export const catalogScanStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  b: { fontWeight: '700' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  headerIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 16, fontWeight: '700' },
  subtitle: { fontSize: 12, marginTop: 1 },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderWidth: 1,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 10,
    padding: 12,
  },
  errorText: { flex: 1, fontSize: 12, lineHeight: 17 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingHorizontal: 28 },
  processingOrb: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    marginBottom: 4,
  },
  processingCard: {
    alignSelf: 'stretch',
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    gap: 10,
    marginTop: 8,
  },
  processingCardText: { fontSize: 13, lineHeight: 19, textAlign: 'center' },
  elapsed: { fontSize: 13, fontWeight: '700', textAlign: 'center' },
  bgBtn: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
  },
  bgBtnText: { fontSize: 14, fontWeight: '600' },
  chooseWrap: { padding: 16, gap: 12 },
  hintCard: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
  },
  hintText: { flex: 1, fontSize: 13, lineHeight: 19 },
  sourceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
  },
  sourceIcon: { width: 48, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  sourceTitle: { fontSize: 15, fontWeight: '700' },
  sourceSub: { fontSize: 12, marginTop: 2 },
  analyzingTitle: { fontSize: 17, fontWeight: '700', marginTop: 6, textAlign: 'center' },
  analyzingSub: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  invHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 6,
  },
  invTotal: { fontSize: 15, fontWeight: '800' },
  invHint: { fontSize: 12, paddingHorizontal: 16, paddingBottom: 8, lineHeight: 16 },
  previewContent: { paddingHorizontal: 12, paddingTop: 4 },
  supplierMetaCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 14,
    marginBottom: 12,
    gap: 8,
  },
  supplierMetaTitle: { fontSize: 14, fontWeight: '800' },
  supplierMetaSub: { fontSize: 11, lineHeight: 15 },
  supplierMetaGrid: { gap: 6, marginTop: 2 },
  supplierMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  supplierMetaLabel: {
    width: 108,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    paddingTop: 1,
  },
  supplierMetaValue: { flex: 1, fontSize: 13, fontWeight: '600', lineHeight: 18 },
  bankInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
  },
  rowName: { fontSize: 14, fontWeight: '600' },
  editFieldsRow: { flexDirection: 'row', gap: 8 },
  editField: { flex: 1, gap: 3 },
  editLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
  editInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  editInput: { flex: 1, fontSize: 13, fontWeight: '600', paddingVertical: 0 },
  editSuffix: { fontSize: 11, fontWeight: '600', marginLeft: 4 },
  catChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  catChipText: { fontSize: 12, fontWeight: '700' },
  footer: { padding: 16, borderTopWidth: 1 },
  destLabel: { fontSize: 12, fontWeight: '700', marginBottom: 8 },
  destRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  destChip: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
  },
  destChipText: { fontSize: 11, fontWeight: '700' },
  confirmBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    paddingVertical: 15,
  },
  confirmBtnText: { fontSize: 15, fontWeight: '700' },
  resultWrap: { padding: 20, alignItems: 'center', gap: 8 },
  successCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  typeBadgeText: { fontSize: 12, fontWeight: '700' },
  resultTitle: { fontSize: 19, fontWeight: '800', marginTop: 4 },
  resultSub: { fontSize: 13, textAlign: 'center' },
  statsRow: { flexDirection: 'row', gap: 12, marginTop: 14, alignSelf: 'stretch' },
  statCard: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    alignItems: 'center',
    gap: 4,
  },
  statNum: { fontSize: 26, fontWeight: '800', letterSpacing: -0.5 },
  statLabel: { fontSize: 11, textAlign: 'center', lineHeight: 15 },
  resultNote: { fontSize: 12, marginTop: 10 },
  warnBox: {
    alignSelf: 'stretch',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    gap: 4,
  },
  warnText: { fontSize: 11, lineHeight: 16 },
  primaryBtn: {
    alignSelf: 'stretch',
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: Platform.OS === 'ios' ? 20 : 8,
  },
  primaryBtnText: { fontSize: 15, fontWeight: '700' },
  pickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  pickerSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 32 : 20,
  },
  pickerTitle: { fontSize: 15, fontWeight: '800', marginBottom: 10 },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  pickerRowText: { fontSize: 14, fontWeight: '500' },
});
